### ISSUE TITLE
Make navigation work on mobile

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#1]
Currently, the mobile navigation is broken and has z-index issues. 

![Screenshot 2022-07-21 at 15 21 12](https://user-images.githubusercontent.com/12615742/180237591-8b96f63a-eaac-4d8e-a0cf-1c3b19515d52.png)

**Comment by praveen-quizizz** [comment]
Adding a  `z-10` on `Popover.Panel` will fix the issue

Could be marked as a good-first-issue

**Comment by NiallJoeMaher** [comment]
Yes! I'll do it later if nobody picks it up but could be low-hanging fruit for someone.
