### ISSUE TITLE
Alter settings page, to include first and last name.

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1004]
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

Connected to issue #1003 
Create a migration script to split the name field into firstname and lastname.

We plan to introduce an onboarding form to collect user metrics. This form will have separate fields for firstName and surName.

## Expected Behavior

The profile settings page should be edited to remove the 'Full Name' input and replace it with two new inputs, 'First name' and 'Surname'.
These inputs correspond to firstname and lastname in the database.
The zod validations should align with those found on the additional-details form. (AKA the onboarding form)

## Current Behavior

The current settings page has a 'Full name' input, which corresponds to the 'name' field in the database.

![Screenshot of the error message](https://github.com/user-attachments/assets/0eba34f0-8edf-4c65-a336-8c009ac09b90)

## Additional info

The settings page is found at :

app>(app)>settings>_client.tsx>Settings

The new onboarding form is found at  

app>(app)>alpha>additional-details

Any questions feel free to ask.

Connected issues
#1003
#1004 
#1005 
#1006 
#1008 
#1009
#1011

**Comment by anjalit03** [comment]
Hello! Can you please assign this me? This will be my very first open-source contribution.

**Comment by John-Paul-Larkin** [comment]
> Hello! Can you please assign this me? This will be my very first open-source contribution.

Hey @anjalit03 
We have chosen to keep the fullname intact rather than splitting it, for practical reasons.
I will close this issue now. I hope you grab another one.
