### ISSUE TITLE
Refactor settings page to include catalyst components. FIGMA DESIGNS ADDED

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1005]
## Context

Check out the [Figma Designs](https://www.figma.com/design/eQMBEWfFu471ZAGoZxF4MC/Settings?node-id=0-1&t=f7ZOwLgVmLxyNoJw-1) Which will show you how the settings page should look.

Codu is planning to do a redesign of the site in the near future. This will be done incrementally, because there is quite a lot involved.
In preparation for this, we will introduce the [Catalyst](https://tailwindui.com/templates/catalyst) component library from tailwind UI.

> It's a collection of beautiful, production-ready UI components you drop into your projects alongside your own code that are yours to customize, adapt, and make your own.

This will provide us with accessible, reusable components to provide a standard theme across the site.

We will leave the default styles on the component, and we will edit them later when we begin the redesign.

## Expected Behavior

The Profile Settings page should be edited to use the Catalyst inputs. 

As an example, the additional-details (onboarding form) is currently using these components.

![Slide one of onboarding form](https://github.com/user-attachments/assets/800aab24-6030-4444-aa44-56ed288cae8d)

## Current Behavior

This is the settings page as it is currently:

![Current Profile settings page](https://github.com/user-attachments/assets/7c7a0dfd-7283-4fd0-b35a-46dddcab7c85)

## Additional info

Note: The catalyst components can be found at :

components>ui-components

The settings page is found at :

app>(app)>settings>_client.tsx>Settings

The new onboarding form is found at

app>(app)>alpha>additional-details

Any questions feel free to ask.

Connected issues
#1003
#1004 
#1005 
#1006 
#1008 
#1009
#1011

**Comment by AuraOfDivinity** [comment]
I would like to work on this issue.

**Comment by John-Paul-Larkin** [comment]
Awesome, Thanks @AuraOfDivinity 
I assigned you.

**Comment by NiallJoeMaher** [comment]
Is this still WIP or should I reassign? Any more information needed to be added to this?

**Comment by AuraOfDivinity** [comment]
Hey @NiallJoeMaher Still working on this. Been a bit busy with work. I will have a PR ready soon.
