### ISSUE TITLE
codu.co prefix label not lining up correctly on onboarding-form. 

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1006]
## Context

On slide one of the additional-details (onboarding form) there is a prefix label which does not line up correctly.
We are using the [Catalyst](https://tailwindui.com/templates/catalyst) component library from tailwind UI. 
Currently the prefix is contained within a span with the catalyst input to the right.

## Expected Behavior

Remove the current div with the span and input, and replace it something that looks better. 
You could possibly replace it with the "Input with leading icon" or "Input with add on" component.
[Catalyst components](https://tailwindui.com/components/application-ui/forms/input-groups#component-d6ba419d2b33a8ab4fd662189bfd8a31) 

Note: Please do not edit the Catalyst components default styles.

## Current Behavior

![Current input not aligning](https://github.com/user-attachments/assets/ec038fa6-b6f3-4828-9ddc-19a1d9d0c3c0)

It is more obvious with a focus ring.
![Current input with focus](https://github.com/user-attachments/assets/3501084d-42eb-41f0-985d-8e318051cadf)

## Additional info

Note: The catalyst components can be found at :

components> ui-components

The onboarding form is found at

app>(app)>alpha>additional-details

Any questions feel free to ask.

Connected issues
#1003
#1004 
#1005 
#1006 
#1008 
#1009
#1011

**Comment by CarolinaCobo** [comment]
I'll take this one. Just as a note it's probably not clear to newcomers that there's an alpha section. 🗡️

**Comment by John-Paul-Larkin** [comment]
> I'll take this one. Just as a note it's probably not clear to newcomers that there's an alpha section. 🗡️

Awesome. 
You are right about the Alpha section. It took me a while to figure that out to. 
I will add a piece to the readme about it, although Niall has mentioned adding PostHog to the project for this purpose.
