### ISSUE TITLE
Add avatar to the onboarding flow

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1008]
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

On slide one of the additional-details (onboarding form) we want to add an Avatar, similar to how is it is shown on the current settings page.  The avatar is populated through the users Github account
We are using the [Catalyst](https://tailwindui.com/templates/catalyst) component library from tailwind UI.
The Catalyst docs have a section showcasing Avatars.

## Expected Behavior

Currently there are three slides, and they are a fixed height to match each other. 
Slide one already has four fields 'First name', 'Surname', 'Username' and 'Location'.
Slide two only has two fields, 'Gender' and 'Date of birth'.
It might make sense to move the 'Location' and/or 'Username' fields to slide two. 
You can decide which you think looks/works best, just please keep the styles and height consistent across the slides.

## Current Behavior

Current slide one.

![Current slide one](https://github.com/user-attachments/assets/2faf864c-4cdc-4b57-91e3-b1f46cce5929)
Current slide two.
![Current slide two](https://github.com/user-attachments/assets/dfeec762-8fb8-43d5-a53b-ad834b95d43e)

This is the avatar on the settings page

![Avatar on settings page](https://github.com/user-attachments/assets/13f2e287-44d5-4904-ad4b-d4be65f6af02)

## Additional info

Note: The catalyst components can be found at :

components> ui-components

The onboarding form is found at

app>(app)>alpha>additional-details

Any questions feel free to ask.

Connected issues
#1003
#1004 
#1005 
#1006 
#1008 
#1009
#1011

**Comment by Aditya-PS-05** [comment]
Hey @NiallJoeMaher ,
I am interested in solving this issue. Please assign it to me.

**Comment by NiallJoeMaher** [comment]
@Aditya-PS-05 are you working on this one or should I re-assign?

**Comment by Aditya-PS-05** [comment]
@NiallJoeMaher 
Working on it. 
My college exams are going on. So, I am not getting enough time to do it. 
If I didn't submit a pr by Sunday, you can re-assign it.

**Comment by NiallJoeMaher** [comment]
Hey @Aditya-PS-05, going to unassign while you are busy! Let me know when your done your exams or want another issue and I'll try get you something (just jump into the ol' Discord). 

Best of luck with the exams, you got this 🦾

**Comment by sahilpatel2712** [comment]
hey @NiallJoeMaher I like to work on this issue.

**Comment by dineshsutihar** [comment]
Hey @NiallJoeMaher  I'd like to work on this. Could you please assign it to me?

**Comment by sahilpatel2712** [comment]
Hi, @NiallJoeMaher I have a doubt, should the profile picture be editable in the onboarding form?

**Comment by DeveloperAyushKumar** [comment]
can I work on it ?
