### ISSUE TITLE
Add "Years of experience" field to onboarding form

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1009]
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

On slide three of the additional-details (onboarding form) the user is presented with a dropdown, from which they select whether they are a "Working professional", "Current student" or "None of the above".

If they select "Working professional" they are presented with two further questions. 
"Where are you working?" and "What is your job title?".
Additionally to this we would like to ask for "Years of experience".
A dropdown would work, but you could alternatively add a text input.
Either way please include Zod schema for the validation of a reasonable number.
Please use the catalyst components and remain consistent with the form styling.
A new field will be required on the user table. 
 
## Current Behaviour

![Current Slide three](https://github.com/user-attachments/assets/4707e9d1-a281-411b-b78a-1cb651d2ecbb)

## Additional info

Note: The catalyst components can be found at :

components> ui-components

The onboarding form is found at

app>(app)>alpha>additional-details

Any questions feel free to ask.

Connected issues
#1003
#1004 
#1005 
#1006 
#1008 
#1009
#1011

**Comment by NiallJoeMaher** [comment]
We should probably select a range of years so it's not just a random number. Let me see if I can find some sensible ranges.

**Comment by John-Paul-Larkin** [comment]
> We should probably select a range of years so it's not just a random number. Let me see if I can find some sensible ranges.

How about this for ranges???
0-2
3-5
5-10
10+
20+

**Comment by leslyclopez11** [comment]
@John-Paul-Larkin hey again, can I work on this issue?

**Comment by John-Paul-Larkin** [comment]
@leslyclopez11 
Absolutely. I assigned you. Thanks Lesly.

**Comment by leslyclopez11** [comment]
@John-Paul-Larkin Thank you! I'll get working on this

**Comment by NiallJoeMaher** [comment]
Thanks @leslyclopez11! 

As for ranges, could we make it:
0-1 years 
1-3 years 
3-5 years 
5-8 years 
8-12 years
12+ years

**Comment by leslyclopez11** [comment]
@John-Paul-Larkin @NiallJoeMaher I think I finished but I want to test it. I'm not sure where to go to test it though. Any help would be appreciated : )

**Comment by John-Paul-Larkin** [comment]
Hi @leslyclopez11 
Do a PR and we will look over it. Thanks.

**Comment by leslyclopez11** [comment]
@John-Paul-Larkin https://github.com/codu-code/codu/pull/1092. Let me know if i broke anything : (

**Comment by leslyclopez11** [comment]
@John-Paul-Larkin Also, I'm currently looking for another issue that's similar to this one. Please let me know if you know about any! thank you : )

**Comment by DeveloperAyushKumar** [comment]
can I work on this ?
