### ISSUE TITLE
Remove parallax effect from hero screen on mobile.

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1012]
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

On the Hero section of the Codú site, there is a parallex effect on the image. When we hover our mouse on the page the spaceman moves relative to the moon.
This works as intended on desktop, however on mobile, the input is being captured, preventing the user from scrolling down the page.

## Expected Behavior

On mobile devices, disable the parallax effect and display the hero section as a static image.

## Screenshots

![Parallax effect astronaut on 0](https://github.com/user-attachments/assets/a36e368a-d7da-4d9d-a0e8-33860858c1d9)

## Additional info

Provide any additional information here

**Comment by NawinKumarSharma** [comment]
@NiallJoeMaher  can you assign me?

**Comment by NiallJoeMaher** [comment]
Open in case anyone wants to grab it!

**Comment by aman124598** [comment]
Hey @NiallJoeMaher Can I start working  on this project

**Comment by John-Paul-Larkin** [comment]
Hey @Stranger1298 
I assigned you

**Comment by NiallJoeMaher** [comment]
@Stranger1298 are you still working on this?
