### ISSUE TITLE
Remove code relataing to the "Events & Communities" section 

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1014]
## Context

The code associated with "Events and communities" is no longer in use and should be removed from the project.
This is a substantial feature, with over 3000 lines of code. 
The entire feature was included in one PR [MVP Events & Communities #611](https://github.com/codu-code/codu/pull/611)
It is possible to revert this PR, but conflicts are likely to arise and will need to be resolved.

The project has migrated from Prisma to Drizzle since this PR, so it will be required to remove any seed data from the schema.

**Comment by JohnAllenTech** [comment]
@John-Paul-Larkin can you throw this in my name. I have a PR open already

**Comment by John-Paul-Larkin** [comment]
@JohnAllenTech 
I assigned it to you John
You are a beast with the late night PRs 💪 🤣

**Comment by JohnAllenTech** [comment]
> @JohnAllenTech I assigned it to you John You are a beast with the late night PRs 💪 🤣

I am in the US these days so its more like 6pm PRs. 🤣

**Comment by John-Paul-Larkin** [comment]
> I am in the US these days so its more like 6pm PRs. 🤣

Ah, thats makes more sense. 🤣  I was wondering if you ever actually sleep.

<img src="https://media1.giphy.com/media/VTtANKl0beDFQRLDTh/giphy.gif"/>
