### ISSUE TITLE
Modify Issues description to hide instructions

### ISSUE THREAD

**Issue by CarolinaCobo** [codu-code/codu#1021]
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

Currently when adding a description in an issue the instructions have to be manually deleted. 

## Expected Behavior

Edit the Description template to hide the description of the required steps as follows: 

`<!-- Description here -->`

## Current Behaviour

Here an example of it in the Write section: 

<img width="328" alt="Screenshot 2024-09-22 at 20 32 39" src="https://github.com/user-attachments/assets/aba84208-660f-4955-87c2-c277bf2a883c">

Here the Preview not showing the one in between `<!--  -->`
<img width="531" alt="Screenshot 2024-09-22 at 20 32 52" src="https://github.com/user-attachments/assets/169d3983-27e2-4821-889c-b8f3d2e6a228">

## Screenshots

Drag and drop screenshots here to better describe your issue

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Step 1
2. Step 2
3. etc

## Additional info

Provide any additional information here

**Comment by TheSoumenMondal** [comment]
I would like to work on this issue...

**Comment by John-Paul-Larkin** [comment]
Awesome @TheSoumenMondal 
I assigned you.

**Comment by John-Paul-Larkin** [comment]
@TheSoumenMondal 
Have you made any progress on this, or should I un-assign you and make it available to someone else?

**Comment by jayambe36** [comment]
assign me, I want to solve this issue.

**Comment by bnelsonemail** [comment]
If you have any other beginner friendly open source, I would love to try.  I am just now getting brave enough to look to contribute.

**Comment by CarolinaCobo** [comment]
@jayambe36 have you made any progress on this? If you haven't I'll un-assign it as other people are interested in. this task. Thanks

**Comment by NiallJoeMaher** [comment]
> If you have any other beginner friendly open source, I would love to try. I am just now getting brave enough to look to contribute.

@bnelsonemail - Do you still want this?

**Comment by Zaid-B24** [comment]
Can you assign this to me? this would be my 2nd open-source contribution.

**Comment by John-Paul-Larkin** [comment]
Thanks @Zaid-B24 
I assigned you.

**Comment by Zaid-B24** [comment]
@John-Paul-Larkin I Created a PR #1194, for issue #1021 can you please review it.
