### ISSUE TITLE
Supplemental information for README.md

### ISSUE THREAD

**Issue by chvainickas** [codu-code/codu#1023]
## Context

Add supplemental information to the steps in the README

## Expected Behavior

Add more context to what each line of code is doing in the README

## Current Behavior

Step by step works perfectly, just would like to add more information to answer some questions people might have starting out in setting up the environment.

## Screenshots

Drag and drop screenshots here to better describe your issue

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Step 1
2. Step 2
3. etc

## Additional info

Provide any additional information here

**Comment by John-Paul-Larkin** [comment]
Hi Edward,
Thank you for reviewing the README. The easier the information is to parse, the more accessible it will be for beginners.

I have assigned this issue to you. 
Let us know if you need any info, or help.
