### ISSUE TITLE
Remove the preview button to make editor WYSIWYG

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1024]
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

As part of "Meta issue : Editor #1022" we need to remove the preview button. This is a step towards making the editor WYSIWYG.

## Expected Behavior
The button should be removed, along with any associated code.

## Current Behavior

When we press the button it opens a preview of how the article will look when it is published. This implements all of the markdown shortcuts we added while editing the text.

## Screenshots
![Editor with preview button](https://github.com/user-attachments/assets/0a7261f5-cfb1-4c3c-8910-dc3a2a385f9f)

## Additional info

The alpha editor can be found at :

app>(app)>alpha>new

Any questions feel free to ask.

**Comment by Prakhar29Sharma** [comment]
Hi @John-Paul-Larkin!
I'm new to open source, I would like to work on this.

**Comment by John-Paul-Larkin** [comment]
> Hi @John-Paul-Larkin! I'm new to open source, I would like to work on this.

Awesome Prakhar. 
Thanks for taking this issue!

**Comment by Prakhar29Sharma** [comment]
Hi @John-Paul-Larkin

Thank you for assigning this task to me. I’ve raised a pull request and would appreciate it if you could review it. Please let me know if there are any issues or further changes required.

This is my first time contributing to open source, so any feedback is welcome!

**Comment by John-Paul-Larkin** [comment]
Thanks @Prakhar29Sharma 

Great to see your first contribution. Hopefully the first of many.
We will review this PR and get back to you soon.
