### ISSUE TITLE
General Cleanup of Legacy Packages and Dead Code

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1026]
## Context

This is an open-ended request for someone to perform a cleanup of legacy packages, dead code, and any other areas of the codebase that may need attention. Over time, this codebase has evolved significantly, and as a result, there are likely unused dependencies in the package.json, as well as redundant or obsolete code throughout the project.

The goal of this issue is to:

Identify and remove dead code: This includes code that is no longer referenced or used, functions that are obsolete, or blocks of code that are unreachable.
Review and clean up legacy packages: Over time, many dependencies may have become outdated or unnecessary. A careful review of the package.json is needed to identify which dependencies can be safely removed or updated.
Address potential technical debt: As part of the cleanup process, we may find suboptimal code structures, workarounds, or temporary fixes that were implemented in earlier versions. Refactoring or removing these could improve maintainability.
Since the extent of this cleanup is unclear, this issue remains open-ended. There may be additional areas that require attention beyond the obvious, so part of the task will involve identifying these as well.

Anyone interested in tackling this should feel free to break this down into smaller tasks as needed or propose further improvements based on what is uncovered during the cleanup process.

**Comment by John-Paul-Larkin** [comment]
@DarrachBarneveld 
You got this fam 🥳

**Comment by DarrachBarneveld** [comment]
No JP, I got you

**Comment by NiallJoeMaher** [comment]
@DarrachBarneveld just checking to see if I should unassign?

**Comment by DarrachBarneveld** [comment]
I have just gotten around to a small pruning of the development branch. 

For the most part I took unused files/components/configurations/dependancies that have not been touched in 12months.

These are not active within the codebase currently.

I broke it up into 4 pull requests for clarity and easier code review.

https://github.com/codu-code/codu/pull/1198
https://github.com/codu-code/codu/pull/1199
https://github.com/codu-code/codu/pull/1200
https://github.com/codu-code/codu/pull/1201

The tool knip was used for analysing the codebase and though a knip configuration can be set up to add stronger linting and prune to the codebase simply running npx knip can give you a general overview.

**Comment by DarrachBarneveld** [comment]
It's important to note that component files that import certain dependencies that are not used within the codebase mean that these dependencies are not used, even though they are imported in the component file.

So, it's best to delete the components first and see where we stand. :)

**Comment by John-Paul-Larkin** [comment]
@DarrachBarneveld in with the 9th inning comeback!

> I broke it up into 4 pull requests for clarity and easier code review.

Four is the magic number!

**Comment by DarrachBarneveld** [comment]
Hahaha I have 2 more but I am unsure if they are worthy

**Comment by CarolinaCobo** [comment]
@DarrachBarneveld can we close this issue then? Or is there anything else you'd like to do related to it? :)
