### ISSUE TITLE
Remove anything relating to the SST package

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1027]
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

SST Serverless stack - is an open-source infrastructure-as-code tool for building on AWS with TypeScript, which allows us to easily manage resources on AWS and handle deployments for JS frameworks.

The project no longer utilises the SST package, so it can be removed from the codebase.

## Expected Behavior

Uninstall the SST package, and remove any references to it.
For instance there is a config file which can be safely deleted:
sst.config.ts 

There is also a script in the package.json which can be deleted
"sst:dev": "sst bind next dev",

It is also referenced in the .gitignore

You can do a search to see if it is referenced anywhere else

## Additional info

Any questions feel free to ask.

**Comment by dhaneshwaritendle** [comment]
Hi, I'm new to open-source contributions, and I'd love to work on this issue. Could I be assigned to it? Any guidance would be appreciated!

**Comment by John-Paul-Larkin** [comment]
> Hi, I'm new to open-source contributions, and I'd love to work on this issue. Could I be assigned to it? Any guidance would be appreciated!

Awesome Dhane. I will assign you.
The readme is excellent, so thats a great start.
If you run into specific issues, let us know.

**Comment by dhaneshwaritendle** [comment]
Thanks, John! I appreciate it. 😊 I’ve removed the SST package from the package.json, .gitignore, and deleted the sst.config.ts file. I did a quick search for any other references, but didn’t find anything else. Would love to get your feedback on the changes!
