### ISSUE TITLE
Remove toolbar from the alpha editor

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1028]
## Context

As part of "Meta issue : Editor #1022" we need to remove the editor toolbar.
We want to keep the interface as uncomplicated as possible, so we only include the features which are most important.
With this in mind, all editing features will be accessed through the slash menu and/or the tooltip.

## Expected Behavior

When removing the toolbar component. 

You should also remove the code for these unused features:
Strikethrough
Codeblock - icon is <> in a square.  - We should keep the code tags(which is just <>)
Left align
Center align
Right align
Exponent - x²
Subscript - x₀
Table

All features on the slash menu should stay.
Slash menu :
![Slash menu](https://github.com/user-attachments/assets/f8f1f5e8-090d-449c-8bb0-7ada55260f3c)

Specifically :
Text / Heading / Subheading / Quote / Code snippet / Bullet list / Numbered list

## Screenshots

This is the toolbar:

![Toolbar](https://github.com/user-attachments/assets/f6f68442-cee2-472f-8b2a-4e4c600342a9)

## Additional info

The alpha editor can be found at :

app>(app)>alpha>new

Any questions feel free to ask.

**Comment by Aditya-PS-05** [comment]
@John-Paul-Larkin 
I am interested in solving this issue. Can you assign this task to me?

**Comment by John-Paul-Larkin** [comment]
Absolutely @Aditya-PS-05 
I assigned you. 🥳

**Comment by John-Paul-Larkin** [comment]
HI @Aditya-PS-05,
We have many people looking for issues for Hacktoberfest, and we need this issue resolved as it is blocking others.
Have you made significant progress on this?
If not I will un-assign you, since you have two open issues.

**Comment by MichaelMoyles** [comment]
Hi @John-Paul-Larkin, I am happy to take this issue
For removing features, should the below also be removed or kept in the tooltip and slash menu (see screenshot)
1. Link
2. Bold
3. Italics
4. Code tags beside the italics

![Tooltip](https://github.com/user-attachments/assets/fdee992c-4bc5-49fc-801c-d2d372e8949e)

Should the below be removed as they are not currently in the tooltip and slash menu:
1. Color Selector for text
2. Highlighting
3. Underline
4. YouTube
5. Image upload & related functionality

**Comment by John-Paul-Larkin** [comment]
Awesome Micael. I will assign you!
>Link
Bold
Italics
Code tags beside the italics
YouTube
Image upload & related functionality

The code for the above functionality can stay, we will implement them later.

On the other hand 
>Color Selector for text
Highlighting
Underline

Can be safely removed. 
Thanks
