### ISSUE TITLE
Add `lang` attribute to the `<html>`

### ISSUE THREAD

**Issue by patrickhladun** [codu-code/codu#103]
To improve the accessibility score on google `lang` attribute could be added to the `<html>` element.

This can be done either by updating `_document.tsx` or by adding the internalisation setting `i18n` in `next.config.js`.

**Comment by NiallJoeMaher** [comment]
The `i18n` in `next.config.js` seems like the best approach according to some discussions I seen on `vercel/nextjs`.

The looks like an easy guide too:
https://melvingeorge.me/blog/set-html-lang-attribute-in-nextjs
