### ISSUE TITLE
Add a link to the readme referencing the Drizzle ORM documentation

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1030]
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

Drizzle is the object relational mapping tool used in the project.
[What is an ORM?](https://www.freecodecamp.org/news/what-is-an-orm-the-meaning-of-object-relational-mapping-database-tools/)
Currently it is not referenced in the readme, so we would like to add a link to the drizzle docs.

## Expected Behavior

Add another bullet point to the Code Contributions list, including a link to the Drizzle documentation.

## Screenshots

![Code contributions](https://github.com/user-attachments/assets/2b7d6680-9789-4460-a47f-4240e7a1f32e)

## Additional info

[Drizzle website](https://orm.drizzle.team/)

Any questions feel free to ask.

**Comment by leslyclopez11** [comment]
I would love to work on this as a beginner! Can I be assigned to it?

**Comment by John-Paul-Larkin** [comment]
> I would love to work on this as a beginner! Can I be assigned to it?

Absolutely leslyclopez11. 
I have assigned you the task.
If you need an help , just let us know.

**Comment by leslyclopez11** [comment]
Hello, I added drizzle to the README.md file. Here is the link to the pull request: https://github.com/codu-code/codu/pull/1033
