### ISSUE TITLE
Editor Title is too verbose

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1038]
## Context
As part of "Meta issue : Editor #1022"

The placeholder title on the Editor is currently "Add a title to your post here!"
This if overly verbose and we would like to change it.

## Expected Behavior

Change to simply "Title".

## Screenshots

![Current title](https://github.com/user-attachments/assets/df4fa862-245e-42a0-be89-1069b220d2ea)

## Additional info
The alpha editor can be found at :

app>(app)>alpha>new

Any questions feel free to ask.

**Comment by Prakhar29Sharma** [comment]
Hi @John-Paul-Larkin
I would like to work on this issue

**Comment by John-Paul-Larkin** [comment]
Hey @Prakhar29Sharma 
Since you have already contributed, would you be comfortable taking an issue with a bit more difficulty?
Looking over your Github I am sure you have the capability, and we would like to keep these issues for beginners.

**Comment by Prakhar29Sharma** [comment]
Oh ok no problem! 
I'll see if I can contribute to some other issues with bit more difficulty

**Comment by jaypopat** [comment]
Hi @John-Paul-Larkin, could you please assign me this issue? I’d love to make my first open-source contribution!

**Comment by John-Paul-Larkin** [comment]
Awesome. Thanks Jay.
