### ISSUE TITLE
Auto-apply markdown features: Enable WYSIWYG 

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1039]
## Context

As part of "Meta issue : Editor #1022"

We would like to simplify the feature set of the alpha editor. 
Previously, we were required to press the "Preview button" to see the result of any editing. 
We want to allow these markdown features :

H2                    ##
H3                    ###
Bullet points    *
Codeblocks      ```
inline code.      `
BlockQuotes   >

## Expected Behavior

When a user types markdown syntax, the editor should automatically recognize and implement the respective feature.
Similar to the behaviour demonstrated in the below GIF, the editor should instantly recognize markdown syntax and apply the relevant features without user intervention.

## Screenshots

Taken from medium.com 

![codeblocks example](https://github.com/user-attachments/assets/767d007f-8c62-49cf-96dd-a6d13ee83bae)

## Additional info

The alpha editor can be found at :

app>(app)>alpha>new

[TipTap docs](https://tiptap.dev/)

Any questions feel free to ask.

**Comment by John-Paul-Larkin** [comment]
@NiallJoeMaher 
Have a look at this, in particular the list of markdown features. Thanks.

**Comment by nawinsharma** [comment]
@John-Paul-Larkin @NiallJoeMaher , can you please assign me! i have nearly solved this issue!

[Screencast from 2024-10-06 02-03-42.webm](https://github.com/user-attachments/assets/be0841e4-fcdf-4546-82da-3d2d6c3059cc)
