### ISSUE TITLE
Fix Twitter( X.com ) card previews not displaying correctly when sharing links.

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1041]
## Context

When sharing an article link from codu.co on x.com, the preview image does not appear in the card. Instead, a placeholder for an image is shown. This issue seems to be related to the Open Graph (OG) metadata tags on the website, which might not be set up properly or are being misread.

## Expected Behavior

The social media post should display the relevant image from the Open Graph metadata on the article page.

## Screenshots

<img width="644" alt="Screenshot 2024-09-28 at 15 18 18" src="https://github.com/user-attachments/assets/b8263c09-653e-4145-821c-5026404caf4c">

## Additional info

Verify that the correct Open Graph tags, particularly og:image, are set in the HTML of the page. Ensure that the image being referenced is publicly accessible and the URL is correct.

**Comment by Sidopolis** [comment]
Hi @John-Paul-Larkin 
I would like to work on this issue

**Comment by John-Paul-Larkin** [comment]
Awesome Sidopolis. I have assigned you.

**Comment by John-Paul-Larkin** [comment]
Hi @Sidopolis 
How are you getting on with this?
Or will I reopen the issue for someone else?

**Comment by Sidopolis** [comment]
Sir you can give to someone else

Due to my semester exams

**Comment by MichaelMoyles** [comment]
Hi @John-Paul-Larkin, I would like to work on this issue

**Comment by John-Paul-Larkin** [comment]
Thanks @MichaelMoyles 
I assigned you
