### ISSUE TITLE
Setting up environment: Issue with running the "db:push": "drizzle-kit push" script 

### ISSUE THREAD

**Issue by chvainickas** [codu-code/codu#1043]
## Context

Trying to populate to populate the DB with dummy data. 

## Expected Behavior

After running both the     **"db:push": "drizzle-kit push"** and   **"db:seed": "npx tsx -r dotenv/config ./drizzle/seed.ts"** the DB should populate the Articles and Events with dummy data

## Current Behavior

Error in after running the first **db:push** command. Please see log below.

```
npm run db:push       


> codu@0.1.0 db:push
> drizzle-kit push

drizzle-kit: v0.22.8
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file '/home/ed/workspace/codu/drizzle.config.ts'
Using 'pg' driver for database querying
[✓] Pulling schema from database...
· You're about to add Tag_id_unique unique constraint to the table, which contains 10 items. If this statement fails, you will receive an error from the database. Do you want to truncate Tag table?


 Warning  You are about to execute current statements:

ALTER TABLE "Community" ALTER COLUMN "excerpt" SET DEFAULT '';
ALTER TABLE "Post" ALTER COLUMN "excerpt" SET DEFAULT '';
ALTER TABLE "user" ALTER COLUMN "bio" SET DEFAULT '';
ALTER TABLE "BannedUsers" ADD CONSTRAINT "BannedUsers_id_unique" UNIQUE("id");
ALTER TABLE "Bookmark" ADD CONSTRAINT "Bookmark_id_unique" UNIQUE("id");
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_id_unique" UNIQUE("id");
ALTER TABLE "Community" ADD CONSTRAINT "Community_id_unique" UNIQUE("id");
ALTER TABLE "Flagged" ADD CONSTRAINT "Flagged_id_unique" UNIQUE("id");
ALTER TABLE "Like" ADD CONSTRAINT "Like_id_unique" UNIQUE("id");
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_id_unique" UNIQUE("id");
ALTER TABLE "Event" ADD CONSTRAINT "Event_id_unique" UNIQUE("id");
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_id_unique" UNIQUE("id");

error: relation "BannedUsers_id_unique" already exists
    at /home/ed/workspace/codu/node_modules/drizzle-kit/bin.cjs:77696:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.query (/home/ed/workspace/codu/node_modules/drizzle-kit/bin.cjs:119635:26)
    at async pgPush (/home/ed/workspace/codu/node_modules/drizzle-kit/bin.cjs:122560:13)
    at async _Command.<anonymous> (/home/ed/workspace/codu/node_modules/drizzle-kit/bin.cjs:129681:7) {
  length: 103,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '873',
  routine: 'index_create'
}
```
## Screenshots

Drag and drop screenshots here to better describe your issue

## Steps to reproduce

Please provide detailed steps for reproducing the issue

Please follow the steps in [README](https://github.com/codu-code/codu/blob/develop/README.md) to step 6.

## Additional info

It is the same issue with docker running

**Comment by chvainickas** [comment]
Also should mention I am using Ubuntu 24.04

**Comment by John-Paul-Larkin** [comment]
Awesome, thanks for this Edward. I didn't run into this when seeding the db, so its good that you flagged this issue.

**Comment by JohnAllenTech** [comment]
Have you tried the db:nuke script? 

`npm run db:nuke` I think it is?

This will wipe your DB. Then try 

`npm run db:push`

**Comment by John-Paul-Larkin** [comment]
Great name for that command 🤣 
@chvainickas You should listen to John, he actually knows what he talking about 🚀

**Comment by chvainickas** [comment]
`
~/workspace/codu develop !3                                                                                                                                                                                                               anaconda3
> npm run db:nuke

> codu@0.1.0 db:nuke
> npx tsx -r dotenv/config ./drizzle/nuke.ts

This will delete all data. Are you sure? (y/n) y
{
  severity_local: 'NOTICE',
  severity: 'NOTICE',
  code: '00000',
  message: 'drop cascades to 18 other objects',
  detail: 'drop cascades to type "Role"\n' +
    'drop cascades to table account\n' +
    'drop cascades to table "BannedUsers"\n' +
    'drop cascades to table "Bookmark"\n' +
    'drop cascades to table "Comment"\n' +
    'drop cascades to table "Community"\n' +
    'drop cascades to table "Event"\n' +
    'drop cascades to table "Flagged"\n' +
    'drop cascades to table "Like"\n' +
    'drop cascades to table "Membership"\n' +
    'drop cascades to table "Notification"\n' +
    'drop cascades to table "Post"\n' +
    'drop cascades to table "PostTag"\n' +
    'drop cascades to table "RSVP"\n' +
    'drop cascades to table session\n' +
    'drop cascades to table "Tag"\n' +
    'drop cascades to table "user"\n' +
    'drop cascades to table "verificationToken"',
  file: 'dependency.c',
  line: '1213',
  routine: 'reportDependentObjects'
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

PostgresError: schema "drizzle" does not exist
    at ErrorResponse (/home/ed/workspace/codu/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/home/ed/workspace/codu/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/home/ed/workspace/codu/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '3F000',
  file: 'namespace.c',
  line: '3096',
  routine: 'get_namespace_oid'
}

Node.js v18.19.1
`

**Comment by chvainickas** [comment]
I have ran the DB:nuke and I guess something is not working

**Comment by John-Paul-Larkin** [comment]
The joys of development Edward. 🤣 
Maybe try deleting the docker container and creating a new instance?

**Comment by JohnAllenTech** [comment]
Can confirm I am seeing the same issue as @chvainickas 

Drizzle pushing breaking changes in minor versions it seems 🙃

Ill report back if I figure out whats up

**Comment by JohnAllenTech** [comment]
Ok not sure whats happening up I have a temp fix


https://github.com/user-attachments/assets/f33c4c72-5bf7-4558-8e5c-c85c93b85acf

For some reason my music came through on the recording. Thats not needed to get this working 🤣

**Comment by JohnAllenTech** [comment]
Or if your feeling like a hackerman 

docker rm -f codu-db && docker rmi -f $(docker images -q postgres) && docker volume prune -f

docker compose up

npm run db:push

npm run dev

**Comment by John-Paul-Larkin** [comment]
Music was a nice touch @JohnAllenTech 🤣

**Comment by chvainickas** [comment]
> Ok not sure whats happening up I have a temp fix
> 
>  Screen.Recording.2024-10-01.at.16.1.mp4 
> For some reason my music came through on the recording. Thats not needed to get this working 🤣

This worked perfectly, but now I am having trouble with the seeding, please advise. Let me know if I should open another ticket or if I should continue on this issue?

**Comment by chvainickas** [comment]
the log for reference

```
> npm run db:seed

> codu@0.1.0 db:seed
> npx tsx -r dotenv/config ./drizzle/seed.ts

Delete BannedUsers
Skipping BannedUsers
Delete Bookmark
Skipping Bookmark
Delete Comment
Skipping Comment
Delete Community
Skipping Community
Delete Flagged
Skipping Flagged
Delete Like
Skipping Like
Delete Membership
Skipping Membership
Delete account
Skipping account
Delete PostTag
Skipping PostTag
Delete RSVP
Skipping RSVP
Delete Post
Skipping Post
Delete Tag
Skipping Tag
Delete session
Skipping session
Delete verificationToken
Skipping verificationToken
Delete user
Skipping user
Delete Event
Skipping Event
Delete Notification
Skipping Notification
Database emptied
Start seeding, please wait... 
Error: ReferenceError: crypto is not defined
    at PgText.defaultFn (/home/ed/workspace/codu/server/db/schema.ts:176:32)
    at PgDialect.buildInsertQuery (/home/ed/workspace/codu/node_modules/src/pg-core/dialect.ts:470:35)
    at QueryPromise.getSQL (/home/ed/workspace/codu/node_modules/src/pg-core/query-builders/insert.ts:307:23)
    at <anonymous> (/home/ed/workspace/codu/node_modules/src/pg-core/query-builders/insert.ts:322:35)
    at Object.startActiveSpan (/home/ed/workspace/codu/node_modules/src/tracing.ts:27:11)
    at QueryPromise._prepare (/home/ed/workspace/codu/node_modules/src/pg-core/query-builders/insert.ts:317:17)
    at <anonymous> (/home/ed/workspace/codu/node_modules/src/pg-core/query-builders/insert.ts:332:16)
    at Object.startActiveSpan (/home/ed/workspace/codu/node_modules/src/tracing.ts:27:11)
    at QueryPromise.execute (/home/ed/workspace/codu/node_modules/src/pg-core/query-builders/insert.ts:331:17)
    at QueryPromise.then (/home/ed/workspace/codu/node_modules/src/query-promise.ts:31:15)
Seeding finished.
```

**Comment by John-Paul-Larkin** [comment]
Thanks @chvainickas 
@JohnAllenTech has already flagged this. Its an issue with the node version issue #1048

**Comment by JohnAllenTech** [comment]
Incase anyone ever needs this. Heres an improvement to the script

docker rm -f codu-db && docker rmi -f $(docker images -q postgres) && docker volume rm codu_db
