### ISSUE TITLE
Allow user to update email

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#1049]
Right now a user can't update their email once they have signed up (and won't change if they update it on their socials. 

We should add the ability to add a new email and confirm that email. 

## Expected Behavior

I'm expecting on the settings screen to have an "email settings" section

This should have the current email address and an input with the ability to update an email. 
This email should be saved as a temporary email (and not deleted the old email connected to the account) until it is verified. The verification should be done by clicking a link in an email. 

## Current Behavior

There is no way to update an email address for notifications.

## Screenshots

![Example of what this might look like in the settings](https://github.com/user-attachments/assets/c0f51b37-ad83-4d73-a435-cd0e6c834ec0)

**Comment by Nil2000** [comment]
Hi @NiallJoeMaher I would like to work on this issue.

**Comment by John-Paul-Larkin** [comment]
Awesome thanks @Nil2000 
I assigned you.
