### ISSUE TITLE
Site search not focusing on open

### ISSUE THREAD

**Issue by JohnAllenTech** [codu-code/codu#1051]
## Context

The site search bar isnt auto focusing when you click it
## Expected Behavior

Site search autofocus's

## Current Behavior

What is the current behavior?

## Screenshots

Attached screenshare

https://github.com/user-attachments/assets/8090ae2f-a565-4ee5-8923-292c5d19f14e
 

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Click 'search the site' textbox on the main page

## Additional info

Good first issue IMO

**Comment by ArinNigam** [comment]
I would like to work on this issue

**Comment by John-Paul-Larkin** [comment]
Thanks @ArinNigam.
We are having some issues around drizzle at the moment, but it should be fixed soon, just make sure to fetch the latest changes.

**Comment by NiallJoeMaher** [comment]
@ArinNigam you should be good to take this now! Everything seems to be back working

**Comment by babyo77** [comment]
added PR https://github.com/codu-code/codu/pull/1076

**Comment by NiallJoeMaher** [comment]
Hey @babyo77, thanks, but it's assigned to @ArinNigam, so unless they don't want this issue anymore, I'll close your PR.

**Comment by ArinNigam** [comment]
> Hey @babyo77, thanks, but it's assigned to @ArinNigam, so unless they don't want this issue anymore, I'll close your PR. 

Sure go ahead with his PR
