### ISSUE TITLE
Fix styling on "sort by" select on articles page

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1063]
## Context

We recently integrated the Catalyst component library into the project. However, the global styles in `globals.css` were conflicting with the new input components. To resolve this, PR #1042 was implemented, scoping the old styles under the "old-input" class. While this successfully fixed the issue on the settings page and editor, it inadvertently affected the styling of the "sort by" dropdown on the articles page.

## Expected Behavior
The "sort by" dropdown on the articles page should retain its original styling, unaffected by the changes introduced in PR #1042  

## Screenshots
![select ](https://github.com/user-attachments/assets/0c9be853-781c-407b-a7e9-32d37f4f06d9)

## Additional info

The articles page can be found at :
app/(app)/articles

**Comment by nawinsharma** [comment]
@John-Paul-Larkin can you assign me?

**Comment by John-Paul-Larkin** [comment]
Thanks NawinKumarSharma.  
I assigned you.
