### ISSUE TITLE
Create OG Image Component for shared Articles

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1066]
## Context

The current codebase has an OG image API that generates images with dynamic data on request. 
We need a component based on the Figma designs to handle this. 
The designs involve layers, images, and gradients, so its a good issue for someone looking to work on CSS skills.

Niall discussed this on the stream, which you can watch [here.](https://www.youtube.com/live/lFvdoPmXfzQ?si=LHWmhY1OTpcF6d_S&t=2864)

Check out the [Figma file.](https://www.figma.com/design/MvNb0ffqPj9kb4MrrRXlsK/Og-Image?node-id=0-1&t=B28Hd3rob8berxqj-1)

## Screenshots

![OG Image](https://github.com/user-attachments/assets/12fb7f39-1b76-448b-b4fa-4a46de70c558)

## Additional info

The API can be found at
app/api/og/route.tsx

**Comment by South-IN** [comment]
Can I work on this issue ?

**Comment by South-IN** [comment]
Do you want the image response to be like this ?

**Comment by John-Paul-Larkin** [comment]
> Do you want the image response to be like this ?

HI South in.
Yes the image should be dynamically created to match the designs found in the figma file. 
Do you want this issue assigned to you?

**Comment by South-IN** [comment]
Yes please assign this issue to me I am not sure I I'll be able to replicate the design but I'll try if I am not able to do it I'll unassign myself.

**Comment by John-Paul-Larkin** [comment]
Thanks South-IN. 

I believe in you. 🥳 

<img src="https://media0.giphy.com/media/W5ZUxqXT1lmiysXsDE/giphy.gif"/>

**Comment by NiallJoeMaher** [comment]
If you need the figma file so you can download the images to use in the design jump into the Discord and tag me. I'll send you the file. 

The design isn't responsive (since it's a fixed size). But has lots of layered images so it's a tough but fun one. We are here to help! <3

**Comment by John-Paul-Larkin** [comment]
Apologies, I thought you could view the figma file in through the link I shared.

**Comment by NiallJoeMaher** [comment]
You can view it but not pull out the needed images I think 🤔

**Comment by South-IN** [comment]
@NiallJoeMaher @John-Paul-Larkin thank you I'll mention you on discord.
