### ISSUE TITLE
Post changes disappears when clicking away from the post editor

### ISSUE THREAD

**Issue by patrickhladun** [codu-code/codu#107]
## Context

When editing a post or content user might lose the changes if not saved.

## Expected Behavior

The user should be able to click away from the browser and not lose the changes to the post.

## Current Behavior

When the post is edited and the user clicks away from the browser or changes the browser tab and then navigates back to the post editor all the content that was not saved disappears.

## Screenshots

![2022-11-08 11 36 15](https://user-images.githubusercontent.com/13404272/200623811-15404315-f03a-48a7-ac3e-9811dedec132.gif)

## Steps to reproduce

1. Open the post
2. Start making changes
3. Click away from the browser or a different tab in the browser
4. Click back on the browser tab with the post editor
5. The new unsaved changes will disappear

**Comment by NiallJoeMaher** [comment]
This was fixed by disabling refetch on the Query.
