### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by KavyaBS123** [codu-code/codu#1073]
## Expected Behavior
takes user to top of page as soon as its pressed

**Comment by John-Paul-Larkin** [comment]
Hey @KavyaBS123,
Could you please add more info to this issue.
Where would you expect this button to be? On the layout footer, on articles?
Are you planning to work on this yourself?
Thanks,
Jp

**Comment by KavyaBS123** [comment]
Hey @John-Paul-Larkin on layout footer I meant 
Such that it improved the UX of user on website.

**Comment by KavyaBS123** [comment]
Yeaa I am planning to work by myself.

**Comment by John-Paul-Larkin** [comment]
OK great @KavyaBS123 
I assigned you. Thanks.

**Comment by John-Paul-Larkin** [comment]
@KavyaBS123 

Hey,
Following a conversation with Niall Maher it was pointed out that this issue has been discussed at length [here.](https://github.com/codu-code/codu/discussions/581)
There was no outcome from that conversation, so it was decided to not go ahead with it.
As such I will close this issue now.
