### ISSUE TITLE
Adding feedback option in footer

### ISSUE THREAD

**Issue by Aditijainnn** [codu-code/codu#1075]
## Context

In the footer of website we can add feedback option where user can give rating

assign this issue to me under gssoc ext and hacktoberfest

**Comment by John-Paul-Larkin** [comment]
Hi @Aditijainnn 
We currently have this toolbar on articles. Is this the feedback functionality you are expecting?

<img width="451" alt="Screenshot 2024-10-06 at 15 52 19" src="https://github.com/user-attachments/assets/467d0059-2cc8-4e13-9972-cbf880da6662">

**Comment by Aditijainnn** [comment]
> Hi @Aditijainnn We currently have this toolbar on articles. Is this the feedback functionality you are expecting?
> <img alt="Screenshot 2024-10-06 at 15 52 19" width="451" src="https://private-user-images.githubusercontent.com/107807466/373956409-467d0059-2cc8-4e13-9972-cbf880da6662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNzkwOTUsIm5iZiI6MTcyODI3ODc5NSwicGF0aCI6Ii8xMDc4MDc0NjYvMzczOTU2NDA5LTQ2N2QwMDU5LTJjYzgtNGUxMy05OTcyLWNiZjg4MGRhNjY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwNTI2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzI0NmE1YmE3ZTdjNmUyOTI3MmZiMzRkYmM5ODQ1M2ZmMjk0YjkxM2RhNDgxNDY4OGIwMDJhZDc3MDdiODI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.usiLbF8itNB0xhmXdfD8Lk-XLlYfD9oeL9H1EBN8Kx0">

no basically a rate us option

**Comment by NiallJoeMaher** [comment]
Closing because this has absolutely no information.
