### ISSUE TITLE
Consolidate Name Inputs on Onboarding Form

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1080]
## Context

In the "additional-details" step of the onboarding form (slide one), users are currently asked to provide their "First name" and "Surname" using two separate input fields. We want to simplify this by replacing both inputs with a single "Fullname" field.

- Remove the "First name" and "Surname" input fields from the form.
- Replace them with a single "Fullname" input.
- Follow the current pattern and use the Catalyst input component.
- The "First name" and "Surname" fields should also be removed from the user table.
- The fullname field already exists in the user table (populated via GitHub login), and it should be used to set the initial value of the new input field.
- Remove any associated code and validation (including the Zod schema) related to the deleted inputs.
- Add Zod validation for the new "Fullname" input field.

## Screenshots

![Onboarding form slide one](https://github.com/user-attachments/assets/6f8168f3-b83b-44e6-8784-bf30851bfef9)

## Additional info

Note: The catalyst components can be found at :

components> ui-components

The onboarding form is found at

app>(app)>alpha>additional-details

Any questions feel free to ask.

**Comment by sahilpatel2712** [comment]
hey @John-Paul-Larkin, can you assign it to me? I would like to contribute.

**Comment by John-Paul-Larkin** [comment]
@sahilpatel2712 
I assigned you. Thanks.
PS Do you have linkedin?

**Comment by sahilpatel2712** [comment]
yes
