### ISSUE TITLE
Add a jobs posting page form

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#1082]
## Context

We want to be able to add job postings. The first task is creating a form for entering a job.
This issue concerns creating a responsive form where users can add a job posting. 

It should look something like this:

![Showing all of the placeholders and required fields for the jobs post](https://github.com/user-attachments/assets/b56ae2c1-4640-4f6c-94d8-c4f91f07478b)

## Expected Behavior

- We are using the following components (already in the codebase) and they should not need updating: https://catalyst.tailwindui.com/
- As for responsiveness, it should work like this page: https://catalyst-demo.tailwindui.com/settings
- It should have the same sized text and work as shown in that page too (https://catalyst-demo.tailwindui.com/settings)
- The labels and text values/placeholders should have the same as shown in the design (figma below)
- This page should be feature flagged with a flag called "course-video". For an example of a feature flag see https://github.com/codu-code/codu/tree/develop/app/(app)/feature-flag-example

This is a frontend-only task that requires only the frontend aspects. 

Another issue can be created to handle error handling and data validation.
Another issue can be created to handle wiring up to backend and stripe. 

## Additional info

Figma link to steal the text and placeholders: https://www.figma.com/design/EQIZDCfdHsQ9aG1YDK6QB5/Job-posting?node-id=0-1&t=7WoZSVfZOSM9W2aB-1

**Comment by slashexx** [comment]
Hi Niall ! Would love to take a stab at this one, can you assign it to me under the hacktoberfest label ?

**Comment by NiallJoeMaher** [comment]
Done @slashexx

**Comment by Nil2000** [comment]
I can try this one

**Comment by slashexx** [comment]
Hi, apologies I've got something coming up for the next few days so I won't be able to work on this. Hence I've unassigned myself, please assign this issue to someone else.

Apologies !
