### ISSUE TITLE
Remove Legacy Alpha Settings Page

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1087]
## Context

The /app/(app)/alpha/settings directory contains a copy of the normal settings page, initially intended for handling new fields from the onboarding form. This is now legacy and no longer needed. Please delete this directory.

Delete the /app/(app)/alpha/settings directory

**Comment by Aarohi-Sharma** [comment]
I will look at this and let you know soon.
edit: I have deleted the directory.
