### ISSUE TITLE
Post Sorting and Timestamp Display in "Your Posts" Section

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1088]
## Context

When users click on "Your Posts," they are presented with three tabs: Drafts, Scheduled, and Published.

Problem 1: Drafts Tab - Incorrect Sorting
In the Drafts tab, posts are not loaded in chronological order based on their last update. Although the posts load in the same order every time, newly added drafts can appear randomly in the list instead of appearing at the top.

Problem 2: Published Tab - Handling Edited Posts
In the Published tab, posts are currently ordered by the "Published on" date. While this behavior is correct, we want to account for posts that have been edited after being published.

## Expected Behavior
Problem 1:
Add a "Last updated at" timestamp to the bottom of each draft card.
Sort the posts in the Drafts tab in descending order, by the "Last updated at" timestamp (newest updates first).

Problem 2:
If a published post has been edited, replace the "Published on" date with the "Last updated" timestamp on the post's card.

Sort all posts chronologically, showing the most recent at the top. For edited posts, use the "Last updated" timestamp for sorting. For unedited posts, use the "Published on" date for sorting. Both edited and unedited posts should be sorted together, without giving precedence to either timestamp.
Also, if a post has been edited it should say "Last updated" instead of "Published on"

If this is unclear please watch the [livestream ](https://www.twitch.tv/codudotco) starting from 30:40, where we discuss this issue

## Current Behavior

Drafts have no sort order, or timestamp.

![Drafts posts](https://github.com/user-attachments/assets/20e2d3f1-0120-4a98-b912-f1a7937976b2)

**Comment by HarshitT00** [comment]
want to work on this one

**Comment by John-Paul-Larkin** [comment]
Awesome @HarshitT00 
I assigned you.

**Comment by HarshitT00** [comment]
Could you help me to setup the application.
Do not why getting 302 while signin

**Comment by HarshitT00** [comment]
Added a PR for this issue have a look and could you please add hacktoberfest label also
thanks
