### ISSUE TITLE
Adding Hover effect to buttons

### ISSUE THREAD

**Issue by swamimalode07** [codu-code/codu#1090]
## Expected Behavior

Adds hover effect to buttons

## Current Behavior

What is the current behavior?
![image](https://github.com/user-attachments/assets/4150623d-e13a-46f6-8f63-0532f5c0221a)
Doesnt have a hover effect

Kindly assign me this task under gactoberfest and gssoc-extd

**Comment by NiallJoeMaher** [comment]
Hey there, we have focus outline, which is enough for the moment.
