### ISSUE TITLE
Remove "Sign up today" banner when the user is logged in

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1091]
## Context
Currently, the homepage displays a "Sign up today to become a writer and get a free invite to our Discord community" banner. However, this banner should not be visible to users who are already logged in, as it is no longer relevant.

## Expected Behavior

Only show the "Sign up today" banner when the user is logged out.
When a user is logged in, the banner encouraging sign-up should be hidden.

## Screenshots

![Banner on homepage](https://github.com/user-attachments/assets/702aebdb-6d2f-4996-8669-967f4bcc6c2b)

**Comment by RangerCreaky** [comment]
Can I work on this?

**Comment by RangerCreaky** [comment]
Created a PR for this issue
