### ISSUE TITLE
Add Error Boundary and Server-Side API Calls for Recent Bookmarks Sidebar

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1097]
## Context

The Recent Bookmarks sidebar currently crashes the entire page if the API call fails. We need to improve the error handling so that the entire page is not affected by an API failure related to this component. 

## Expected Behavior

- Add an error boundary specifically around the SideBarSavedPosts component to handle failures gracefully.
- Ensure error handling applies to individual pieces of the component, so it does not affect the rest of the page.

## Screenshots

![Home page with recent bookmarks](https://github.com/user-attachments/assets/da0c94f2-c2f1-477e-9f26-7192ef346f85)

**Comment by HarshitT00** [comment]
Want to work on this one

**Comment by John-Paul-Larkin** [comment]
@HarshitT00 
Awesome, I assigned you.

**Comment by HarshitT00** [comment]
How to reproduce the error?

**Comment by John-Paul-Larkin** [comment]
@HarshitT00 
You can throw your own error.
The issue is to create an error boundary, so that it will be caught in the event of an error.

**Comment by HarshitT00** [comment]
@John-Paul-Larkin 

![image](https://github.com/user-attachments/assets/59f5e0d5-705b-447f-ad99-213ea50a20b9)


myBookmarks: protectedProcedure.query(async ({ ctx }) => {
    throw new Error("something wrong")
    
should do anything else to reproduce error

**Comment by John-Paul-Larkin** [comment]
@HarshitT00 
Hm... that seems to be handled so, but please wait until @NiallJoeMaher has a look at this.

**Comment by HarshitT00** [comment]
Yes, But I have made some changes in code to handle current situation in better way. If you want I can raise a PR

**Comment by John-Paul-Larkin** [comment]
Even better, thanks. Please put a WIP tag on the PR until Niall reviews this issue.

**Comment by NiallJoeMaher** [comment]
@HarshitT00 I left a comment. I think we don't need all the changes but some of them are great. I'll close this issue but you can see the comment in your PR. If you fix up based on my comment I'll merge it (and get you some of those sweet Hacktoberfest points).
