### ISSUE TITLE
[Bug] If logged in and click on down button on home screen no action

### ISSUE THREAD

**Issue by HarshitT00** [codu-code/codu#1098]
## Context

The down arrow button on home screen is not working when user is logged in

## Expected Behavior

If user is logged in then onClick down button it should move to articles
If user is not logged in then onClick down button it should move to get started banner

## Current Behavior

If user is logged in then onClick down button noting happen
If user is not logged in then onClick down button it should move to get started banner

## Screenshots

[Screencast from 2024-10-09 19-23-37.webm](https://github.com/user-attachments/assets/6ce6aca2-c597-4d60-b3d2-ad22d340042a)

## Steps to reproduce

click on down button when you are logged in

**Comment by HarshitT00** [comment]
If issue looks good then I can start working.

**Comment by John-Paul-Larkin** [comment]
@HarshitT00 

I cant reproduce this?
It is working fine for me on chrome.

**Comment by HarshitT00** [comment]
It is happening after the current PR merge to remove the banner if logged in.
Try running the local

**Comment by John-Paul-Larkin** [comment]
Ah.... I get you. Great catch, thanks.
I assigned you.
