### ISSUE TITLE
Update the Twitter icon

### ISSUE THREAD

**Issue by Jils31** [codu-code/codu#1100]
## Context

Please provide any relevant information about your setup

## Expected Behavior

The updated Twitter icon should be visible on the events page

## Current Behavior

The outdated icon is visible

![Screenshot from 2024-10-10 01-41-54](https://github.com/user-attachments/assets/3a7c963b-d902-487c-bc21-c1f85a5fb020)

**Comment by John-Paul-Larkin** [comment]
Hey @Jils31 
That is the footer of the meetup.com website, not the Codú site.
Maybe you should contact them to let them know, but it will always be Twitter to me! 🤣
