### ISSUE TITLE
Implement WYSIWYG for the alpha editor.

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1102]
## Context

We want to move away from the current "edit-then-preview" workflow and completely remove the box structure, for a WYSIWYG implementation of the editor.
As the user types, they should see the article exactly as it looks when it is published. 
Please check out the editor on medium.com for an example of the look and feel we are aiming for. 
Part of meta issue  #1022 

## Current Behavior

The (alpha) editor is historically a basic text box where users type content, then press "Preview" to see how the article will appear when published.  This "Preview" was removed in PR #1031 - Removed view preview button with its associated code

This preview system was initially designed to separate editing from final viewing. 

## Expected Behavior

- The editor should support WYSIWYG (What You See Is What You Get) functionality.
- Markdown features are already implemented: when a user types markdown, it automatically formats in real-time. This was done in PR #1068 - Add auto-apply markdown features on editor: Enable WYSIWYG
- As the user types, the editor should display the exact formatting and styling the article will have when published—no preview step needed.

## Screenshots

![alpha editor](https://github.com/user-attachments/assets/7768ace6-145d-4f5e-b966-ff9c2b29aa64)

## Additional info

The alpha editor can be found at :

app>(app)>alpha>new

Any questions feel free to ask.

**Comment by AuraOfDivinity** [comment]
I would like to work on this issue.

**Comment by John-Paul-Larkin** [comment]
Nice, thanks @AuraOfDivinity

**Comment by NiallJoeMaher** [comment]
Any progress on this? If you are busy we will need to reassign as we are blocked by this issue.

**Comment by AuraOfDivinity** [comment]
Hey @NiallJoeMaher, I've been quite busy over the past few days and had a chance to look into this task yesterday. It seems a bit more time-consuming than I expected. Could we assign it to someone else? Apologies for the delay on my end.

**Comment by dineshsutihar** [comment]
I want to work on this issue. Can you assign it to me? @NiallJoeMaher @AuraOfDivinity

**Comment by John-Paul-Larkin** [comment]
Awesome @dineshsutihar 
I assigned you.

**Comment by dineshsutihar** [comment]
@John-Paul-Larkin @NiallJoeMaher I have created a PR. Could you please review it?
