### ISSUE TITLE
Add Hover Effect to Popular Topics Buttons

### ISSUE THREAD

**Issue by PragyaTripathi990** [codu-code/codu#1104]
## Context

Currently, the buttons for popular topics do not have any hover effects, making them less interactive and visually appealing. Adding a hover effect will enhance the user experience by providing feedback when users interact with the buttons.

## Expected Behavior

Hover State Activation: The button visibly changes its appearance on hover.
Visual Change: The background color transitions smoothly from its default color to the specified hover color.
Transition Effect: The change occurs over a brief duration, providing a smooth visual effect.
Accessibility: The buttons remain accessible and usable on all devices.
Feedback Confirmation: Users feel a clear sense of feedback when interacting with the buttons.

## Current Behavior

The buttons for popular topics do not have any hover effects. When a user hovers over a button, there is no visual indication that the button is interactive.

## Screenshots

<img width="1465" alt="Screenshot 2024-10-10 at 11 57 16 PM" src="https://github.com/user-attachments/assets/7942876c-f162-42da-9e80-303bc6724aff">

## Steps to reproduce
Open your project and locate the HTML file with the buttons.
Add the CSS for hover effects in the corresponding CSS file.
Save changes and test in a web browser to ensure the hover effect works.
Commit changes to version control.
Create a pull request if contributing to a shared project.

**Comment by John-Paul-Larkin** [comment]
This issue has been suggested already. 
https://github.com/codu-code/codu/issues/1090

Hey there, we have focus outline, which is enough for the moment.
