### ISSUE TITLE
Adding error 404 page

### ISSUE THREAD

**Issue by taneeshaa15** [codu-code/codu#1110]
## Context

Please provide any relevant information about your setup

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Screenshots

Drag and drop screenshots here to better describe your issue

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Step 1
2. Step 2
3. etc

## Additional info

Provide any additional information here

**Comment by taneeshaa15** [comment]
@John-Paul-Larkin Please assign me this issue under hacktoberfest.

**Comment by pkspyder007** [comment]
@taneeshaa15 Please provide relevant details in the issue around the 404 page since we already have a not found catch all route this issue most probably is redundant.
