### ISSUE TITLE
Tags in home page not matching style 

### ISSUE THREAD

**Issue by CarolinaCobo** [codu-code/codu#1115]
## Expected Behavior

- The tags in the main page should have a border radius as the articles
- The writing challenge should have a border radius as the articles.

## Current Behavior

![Screenshot 2024-10-13 at 15 12 26](https://github.com/user-attachments/assets/2185d4b6-0706-4d00-8b0c-77c6836f0383)

## Steps to reproduce

Please provide detailed steps for reproducing the issue

## Additional info

Provide any additional information here

**Comment by askarthikey** [comment]
heyy @John-Paul-Larkin  i would like to work on this issue can you please assign me this

**Comment by John-Paul-Larkin** [comment]
Hi @askarthikey 
Thanks, but CarolinaCobo is currently assigned this issue.
