### ISSUE TITLE
Add onboarding complete check on login 

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1128]
## Context

We are introducing a new onboarding form to collect user metrics.
All users will be required to input this data.

## Expected Behavior

A new field should be added to the user table to track whether a user has completed the onboarding process.

Task:
- Add a new Date field in the user table with the name "onboardingCompletedAt".
- This field should be set with the current timestamp when the user finishes the final step of the onboarding process.
- On login, check if this field is null. If it is, redirect the user to the onboarding form and prevent them from accessing the site until the form is completed.

- Additionally, we would like to add a short message, explaining to existing users why we want to gather this information. This will not be necessary for new users. We should perform a check on the "createdAt" timestamp on the user table and only display the modal if the date is earlier than the introduction of the onboarding form.
- For now, just add a placeholder for the message, we will add it later.

## Additional info

The onboarding form is found at

app>(app)>alpha>additional-details

Any questions feel free to ask.

Connected issues
#1003
#1004 
#1005 
#1006 
#1008 
#1009

**Comment by arbazahmed07** [comment]
hey can you please assign me this @John-Paul-Larkin

**Comment by John-Paul-Larkin** [comment]
Thanks @arbazahmed07 
I assigned you.

**Comment by arbazahmed07** [comment]
> Thanks @arbazahmed07 I assigned you.

hey |
how to update the dot env file @John-Paul-Larkin

**Comment by John-Paul-Larkin** [comment]
The readme contains all the information you need.
Have a look here:
https://github.com/codu-code/codu?tab=readme-ov-file#environment-variables

**Comment by arbazahmed07** [comment]
> The readme contains all the information you need. Have a look here: https://github.com/codu-code/codu?tab=readme-ov-file#environment-variables

im getting some errors

**Comment by John-Paul-Larkin** [comment]
Hi @arbazahmed07 
Will I un-assign you from this issue?
