### ISSUE TITLE
Bugfix: Slash Menu Not Functioning in Alpha Editor

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1130]
## Context

After merging PR #1068, the slash menu in the alpha editor stopped functioning. The issue appears to have originated from changes introduced in that PR.

## Expected Behavior

When a user presses the "/" key, the slash menu options should be displayed on the screen. This functionality worked correctly prior to PR #1068.
Pull a commit prior to this PR to see how it should work.
 
## Current Behavior

Currently, pressing the "/" key does not seem to trigger any action, and the slash menu does not appear.

## Screenshots

Slash menu :
![Slash menu](https://github.com/user-attachments/assets/f8f1f5e8-090d-449c-8bb0-7ada55260f3c)

**Comment by therurouni** [comment]
Hii @John-Paul-Larkin.I would like to work on this issue.Can u assign me this issue?

**Comment by John-Paul-Larkin** [comment]
Thanks @PAVAN507-STAR 
I assigned you.

**Comment by John-Paul-Larkin** [comment]
hi @PAVAN507-STAR 
How are you getting on with this issue?

**Comment by therurouni** [comment]
I’ve tried to reset the commit and see what happens but it seems multiple folders were deleted in the mentioned pr and some other pr’s too. So rn im trying to see if i can implement the feature without the deleted folders somehow ,btw do u have  any idea what are the folders that got deleted but are required to implement the feature?

**Comment by John-Paul-Larkin** [comment]
@PAVAN507-STAR 
Unfortunately I do not. If you roll back to an older commit you will be able to see the implementation. Thanks.

**Comment by NiallJoeMaher** [comment]
This one might be fixed in the design updates PR that is open. I haven't tested it but I saw from the code it looked promising.

**Comment by therurouni** [comment]
@NiallJoeMaher I have seen many folders like custom edit and some other folders are deleted so should i bring them back  in this pr or were they deleted on purpose in some pr
