### ISSUE TITLE
Bugfix : Image uploads not working

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1131]
## Context

Image uploads are currently failing in the development environment.

const { mutate: getUploadUrl } = api.event.getUploadUrl.useMutation();

This throws the following error:

> Property 'event' does not exist on type 'CreateTRPCReactBase

The event TRPC route was removed in #1068 as the event functionality was no longer needed. However, the getUploadUrl functionality is still required for image uploads.

## Expected Behavior

The getUploadUrl procedure should be restored and image uploads should work as expected.

It is likely this functionality should be shared with the other parts of the site which require image uploads. Id the settings page.

## Current Behavior

Image uploads are not functioning due to the missing getUploadUrl method.

## Screenshots

![Screenshot 2024-10-15 at 15 10 44](https://github.com/user-attachments/assets/ee68a24c-5dd5-4d9d-a035-163544c0af8f)

## Steps to reproduce

Open the editor and attempt to upload an image.

**Comment by kmahesh18** [comment]
assign me ..i'll resolve this

**Comment by askarthikey** [comment]
heyy @John-Paul-Larkin please assign me this....i'll resolve this

**Comment by NiallJoeMaher** [comment]
No longer an issue. This was fixed with #1126
