### ISSUE TITLE
Navigation Layout Missing on 404 Page

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1132]
## Context

The navigation layout does not appear on the 404 error page.

Example URLs:
https://www.codu.co/dsafasfd
https://www.codu.co/articles/feasdsfas

## Expected Behavior
The navigation should be present and accessible on the 404 page.

## Current Behavior
The navigation layout is missing on the 404 page. Users must use the browser's back button to return to the site.

## Screenshots

![404 - no layout](https://github.com/user-attachments/assets/3f97500a-918b-4bce-9619-9102156b8e2b)

## Steps to Reproduce
Go to any valid URL and modify it by adding random characters at the end.
Observe the 404 page that appears.
Notice that the navigation layout is missing.

**Comment by yashchaurasia667** [comment]
maybe i can fix this can you assign it to me?

**Comment by John-Paul-Larkin** [comment]
Thanks @yashchaurasia667 
I assigned you.

**Comment by yashchaurasia667** [comment]
do you guys have a discord or a slack or something i can join?

**Comment by arbazahmed07** [comment]
hey can you assign me this @John-Paul-Larkin  
i will solve by today

**Comment by NiallJoeMaher** [comment]
Hey @arbazahmed07, we will give @yashchaurasia667 another day to see if there are any updates first. You are next on the list if he decides he doesn't want it.

**Comment by yashchaurasia667** [comment]
I'll make a PR by tonight
