### ISSUE TITLE
Footer Nav Events link routing to 404 page

### ISSUE THREAD

**Issue by Shane-Donlon** [codu-code/codu#1134]
## Context

In the footer component the Events link routes to a 404 page.

Link address current is: [https://www.codu.co/https:/www.meetup.com/codu-community](https://www.codu.co/https:/www.meetup.com/codu-community)
## Expected Behavior
Link address should be: [https:/www.meetup.com/codu-community
](https:/www.meetup.com/codu-community)
Please describe the behavior you are expecting

## Screenshots
![screenshot of footer navigation bar with Events highlighted by a focus ring](https://github.com/user-attachments/assets/7ffe15bf-3fdd-4ae7-a3b4-02d7d61da2c0)

![screenshot of 404: NOT_FOUND error](https://github.com/user-attachments/assets/b301ab8d-50c3-4acc-a602-dceaa9cb9807)

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Go to any page
2. Scroll to bottom
3. Click events
4. New tab will open with 404 page

## Additional info

Provide any additional information here
Files to have a look in:
- Footer/Footer.tsx
- config/site_settings.ts

**Comment by John-Paul-Larkin** [comment]
Good spot. 
You want to take this @Shane-Donlon ?

**Comment by Shane-Donlon** [comment]
Yeah I'll take it @John-Paul-Larkin 

You can leave the privacy one if you want for another good first issue if someone needs it.

**Comment by John-Paul-Larkin** [comment]
Nice, I think you should take the other one too?
There are plenty of issues available now.

**Comment by Shane-Donlon** [comment]
Ah go on, I'll take that too.

I'll be logging another issue for the manifest file later, you can also assign that to me whenever you get a chance (not at my laptop now).

**Comment by arbazahmed07** [comment]
hey can you please assign me this @Shane-Donlon

**Comment by John-Paul-Larkin** [comment]
> hey can you please assign me this @Shane-Donlon

@arbazahmed07 This is already assigned to Shane
