### ISSUE TITLE
Update theme and background-color in Manifest file (Progressive Web App issue)

### ISSUE THREAD

**Issue by Shane-Donlon** [codu-code/codu#1137]
## Context

Please provide any relevant information about your setup

## Expected Behavior

Change the background and theme to black.

## Current Behavior
Update the loading screen when opening the progressive web app (PWA)on mobile to black background with white text.

## Screenshots
![white background with Codú written in black text in the middle](https://github.com/user-attachments/assets/e2adf09b-2567-42a6-aa8d-a3712319eaad)

For now it will just be a static color for both themes,
But depending on how the new redesign goes, might connect it to the theme-toggle later.

**Comment by John-Paul-Larkin** [comment]
On a roll....
