### ISSUE TITLE
Article page calling for bookmarks if if a user isnt logged in

### ISSUE THREAD

**Issue by JohnAllenTech** [codu-code/codu#1138]
## Context

Articles page is calling for bookmarks even when a user is not logged in.

This is causing errors in the console.

## Expected Behavior

Dont call for bookmarks if a user is not logged in

## Current Behavior

Calling for bookmarks when a user hasnt logged in

## Screenshots

<img width="1721" alt="image" src="https://github.com/user-attachments/assets/3392c8c0-74b0-4d8f-89e8-737788446d6f">
## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Go to https://www.codu.co/articles
2. Look at console

<img width="667" alt="image" src="https://github.com/user-attachments/assets/c3f315bf-4a1a-4a15-a2ca-c84e97b6a6aa">

## Additional info

Provide any additional information here

**Comment by kmahesh18** [comment]
hii @JohnAllenTech  assign me this... i can solve this error

**Comment by John-Paul-Larkin** [comment]
Great. Thanks @kmahesh18

**Comment by kmahesh18** [comment]
help me accessing db ... i'm unable to connect to it

**Comment by John-Paul-Larkin** [comment]
> help me accessing db ... i'm unable to connect to it

Do you have a specific issue?
The readme is excellent and breaks it down step by step.

**Comment by John-Paul-Larkin** [comment]
hi @kmahesh18 
Have you made progress or will I reassign this issue?

**Comment by kmahesh18** [comment]
I've tried but unable to make any progress....I've unassigned myself

> hi @kmahesh18 Have you made progress or will I reassign this issue?

**Comment by shanksxz** [comment]
@JohnAllenTech, I'd love to work on the issue
