### ISSUE TITLE
Validation is absent in the Jobs Create page

### ISSUE THREAD

**Issue by Nil2000** [codu-code/codu#1140]
## Context

Validation is absent in the `/jobs/create` page. (in the form specifically)

## Expected Behavior

There should be some kind of validation available for the required fields.

## Current Behavior

No validation error is shown in UI. (which should not be the case)

## Screenshots

![Screen shot of page](https://github.com/user-attachments/assets/c5c40800-4c42-404b-8c8d-ca30b3e55cd4)

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Go to `/jobs/create` page and put random values in the fields
2. Click on `Submit and checkout` button
3. No validation error is shown.

**Comment by Nil2000** [comment]
@NiallJoeMaher @John-Paul-Larkin I have made the PR already. Let me know if you agree with this issue.

**Comment by NiallJoeMaher** [comment]
Thanks for this @Nil2000. I've assigned it to you.
