### ISSUE TITLE
Issue: Transitioning Away from Global Styles in globals.css

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1160]
## Context

We currently have numerous global style classes defined in the globals.css file, which goes against the component-based styling approach promoted by Tailwind CSS. This can lead to unintended styling consequences throughout the project.

We plan to incrementally remove these styles.
As the first step in moving away from this approach, we need to:

Remove the .fancy-link and .fancy-link:hover classes from globals.css.
Copy their styles and apply them directly within the relevant components where they are used.

## Expected Behavior

Ensure that the updated components are tested before and after the change to verify that the styles (including the hover) remain consistent.

## Additional info
File can be found at:

/styles/globals.css

**Comment by wolfofdalalst** [comment]
Can you please assign me this issue?

**Comment by amankumarhq** [comment]
I have fixed this issue in PR #1164 as part of Hacktoberfest.
Please have a look.

**Comment by wolfofdalalst** [comment]
I am unassigning myself from this issue if the pr has already been created.

**Comment by John-Paul-Larkin** [comment]
My apologies @wolfofdalalst 
I didnt catch that a different user did this PR.
This is your issue if you still want it?

@amankumarconnect 
Stealing issues like this is against the open source policy. I will close your PR.
Please feel free to take another issue, but you must ask to be assigned to it before you do a PR.

**Comment by wolfofdalalst** [comment]
Yes can you reassign me, so that I can start working on it right-away.

**Comment by amankumarhq** [comment]
My apologies, @John-Paul-Larkin  and @wolfofdalalst . I didn’t realize it was considered stealing. I thought that whoever opens a PR first would get assigned to the issue afterward.

**Comment by wolfofdalalst** [comment]
@John-Paul-Larkin @NiallJoeMaher 
I have created pr #1170, can you please review and suggest changes if required.
