### ISSUE TITLE
Issue: Transitioning Away from Global Styles in globals.css - **remove .input-base**

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#1161]
## Context

We currently have numerous global style classes defined in the globals.css file, which goes against the component-based styling approach promoted by Tailwind CSS. This can lead to unintended styling consequences throughout the project.

We plan to incrementally remove these styles.
As the first step in moving away from this approach, we need to:

Remove the .input-base class from globals.css.
Copy the styles and apply them directly within the relevant component where they are used.

## Expected Behavior

Ensure that the updated components are tested before and after the change to verify that the styles (including the hover) remain consistent.

## Additional info
File can be found at:

/styles/globals.css

**Comment by mumtazmumtazfb** [comment]
I would like to complete this task. Can you please assign it to me?

**Comment by John-Paul-Larkin** [comment]
Thanks @mumtazmumtazfb 
I assigned you
