### ISSUE TITLE
Give warning of unsaved changes if user tries to navigate before saving content

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#117]
If the user navigates while editing a post the user should be prompted with an alert to confirm the navigation so they don't lose unsaved changes.

If the user has saved all changes this prompt can be ignored.

**Comment by xiaoniuniu89** [comment]
I can pick this up!

**Comment by NiallJoeMaher** [comment]
Sweet! If you have any questions feel free to ask in the open source chat in our Discord! 

Thanks for helping.

I had made a custom hook but never got it finished. I can try find the WIP if it's helpful

**Comment by xiaoniuniu89** [comment]
Sure, that would be great! I have in mind something that might work also. I can also take something else if you are close to finishing this one though. Im easy either way!!

**Comment by NiallJoeMaher** [comment]
I didn't go too far with it because there was a few kinks. I was just stealing code from this thread: https://stackoverflow.com/questions/63064778/next-js-warn-user-for-unsaved-form-before-route-change

**Comment by xiaoniuniu89** [comment]
great !! I will check it out! Thanks

**Comment by xiaoniuniu89** [comment]
UPDATE: Have a functioning untested version of this using confirm dialogs. It would be nice to get this working with the modal in the components folder though. Will work on it during the week but most likely next weekend I will have time to work on it properly.

**Comment by EvanBurbidge** [comment]
@xiaoniuniu89  @NiallJoeMaher  is this issue still required as the app has autosave functionality? The autosave seems to work fairly fast, the only case I can see this being required is if the autosave fails and you try navigate away from the page?

**Comment by xiaoniuniu89** [comment]
this issue is done, should be closed @NiallJoeMaher
