### ISSUE TITLE
Back to top

### ISSUE THREAD

**Issue by Zaid-B24** [codu-code/codu#1213]
## Context

When a user clicks on view more articles on home page, /articles is opened and new posts starts to appear. if a user keeps on scrolling, there is no option to take the user back to the top of the page.

## Expected Behavior

Add a button in the bottom right of /articles page with onclick functionality that takes the user back to top of the home page.

## Current Behavior

When user keeps on scrolling in /articles page user has to scroll all the way up to the home page or use scroll bar.

## Screenshots

![scroll](https://github.com/user-attachments/assets/d551bad0-20ab-4d1a-8a24-9b6b6f16a827)

## Steps to reproduce

1. Visit https://www.codu.co/
2. scroll down and click on more articles
3. scroll down a bit more.

**Comment by John-Paul-Larkin** [comment]
Hey @Zaid-B24 
Thanks for the idea, but this issue has been suggested numerous times before. 
There is a discussion [here](https://github.com/codu-code/codu/discussions/581)
