### ISSUE TITLE
Article preview doesn't look as intended on LinkedIn and Twitter

### ISSUE THREAD

**Issue by sonngdev** [codu-code/codu#151]
## Context

Thank you for the great work on the Writing editor. However, I'm seeing some issues when sharing an article on social media.

## Expected Behavior

- Twitter: The card type should be [Summary card with large image](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image).
- LinkedIn: The image from `og:image` should be used as the article preview.

## Current Behavior

- On Twitter, the preview image is right but it is cropped and can hardly be seen. This is because the card type is Summary.
- On LinkedIn: The first image from the article is used as the article preview, even though `og:image` points to a different image. If an article doesn't include any image, it wouldn't have any preview image.

## Screenshots

<img width="623" alt="Screenshot 2023-02-04 at 9 35 57 a m" src="https://user-images.githubusercontent.com/28614996/216760856-7753ce20-f93c-4b51-a8c2-bde63cd30fa5.png">

<img width="546" alt="Screenshot 2023-02-04 at 9 49 27 a m" src="https://user-images.githubusercontent.com/28614996/216760859-46ebec02-8ac6-4c19-85fc-6b1e7bbea38c.png">

<img width="551" alt="Screenshot 2023-02-04 at 9 49 07 a m" src="https://user-images.githubusercontent.com/28614996/216760861-cf3c8a8b-ccf5-4285-af44-26ee515bec13.png">

## Steps to reproduce

Just try sharing any article on Twitter/LinkedIn

## Additional info

I can take a look at this issue if you assign it to me.

**Comment by sonngdev** [comment]
Update: I resolved the issue on Twitter, but am still having no idea why LinkedIn behaves the way it does.

**Comment by NiallJoeMaher** [comment]
@thanhsonng how did you resolve the issue on Twitter? 

I think I need to put a CDN in front of the function that generates the image on LinkedIn. It might not be as instant as I hoped for when I generate the preview. 😢 

I'll ask @jh3y to have a look into image generation since I know his works perfectly on his site. ❤️

**Comment by sonngdev** [comment]
@NiallJoeMaher I drafted #152, you can take a look on how I resolved Twitter.

**Comment by NiallJoeMaher** [comment]
This should work when we get Cloudfront setup #169
