### ISSUE TITLE
Add CodePen embed

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#154]
## Context

Currently we have some custom components for YouTube and CodeSandbox.

You can embed a YouTube video in Markdown by doing the following:
```
{% youtube src="https://www.youtube.com/embed/G7kzLpvbFYo" /%}
```

We should be able to do similar with a Codepen. 

It would make it easier for some people who want tor reference codepen in their articles. 

## Expected Behavior

Either extend the CodeSandbox behaviour to allow URL's from other embeds or create a new custom Node that allows the embed of a codepen from the source. 

## Current Behavior

Currently there is no Codepen embed.

**Comment by sonngdev** [comment]
I have opened a PR for this issue at #156
