### ISSUE TITLE
Add event for user signup on Fathom analytics

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#160]
## Context

Currently the only way to track new user signup is by checking the database. 

By adding an event to Fathom analytics on signup we should be able to track new user stats in the analytics 

## Expected Behavior

In Fathom we should be able to track new user signups

## Additional info

Docs [here](https://usefathom.com/docs/features/events).

**Comment by EvanBurbidge** [comment]
PR opened
