### ISSUE TITLE
Add a copy link option to share options

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#164]
## Context

Currently when opening the extra options on the post sidebar (or footer on mobile) you have the option to share to LinkedIn or Twitter. 

We should give the user the option to "Copy to clipboard" so that they can share the link easily elsewhere.

## Expected Behavior

The user should have the option to "Copy to clipboard" so that they can share the link easily elsewhere.

This should copy the link to the devices clipboard so it can be easily pasted into whatever platform the user is using to share the link. 

## Current Behavior

Screenshot attached:

<img width="405" alt="Screenshot 2023-02-12 at 15 03 48" src="https://user-images.githubusercontent.com/12615742/218334380-2a4bd588-06b0-4a69-ae6a-09d2ce368a51.png">

**Comment by doriandevelops** [comment]
I'll take this!

**Comment by NiallJoeMaher** [comment]
@dorian-dominguez are you still up to play with this one? I don't know how I missed the reply 😢

**Comment by CBID2** [comment]
I can try it with @dorian-dominguez @NiallJoeMaher!

**Comment by NiallJoeMaher** [comment]
I think we have a package installed too that might help `copy-to-clipboard`. https://www.npmjs.com/package/copy-to-clipboard

Thanks for the help @CBID2 🦾

**Comment by CBID2** [comment]
> I think we have a package installed too that might help `copy-to-clipboard`. https://www.npmjs.com/package/copy-to-clipboard
> 
> 
> 
> Thanks for the help @CBID2 🦾 

Ok thanks

**Comment by sleithdylan** [comment]
@NiallJoeMaher Is it fine for me to pick this up as no one created a PR for it?

**Comment by NiallJoeMaher** [comment]
All yours, it's been vacant a while.

**Comment by CBID2** [comment]
> All yours, it's been vacant a while.

I was under the impression that this issue was solved @NiallJoeMaher.

**Comment by sleithdylan** [comment]
@NiallJoeMaher created a PR for this one 😄
