### ISSUE TITLE
Add ability to report posts/comments 

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#168]
## Context

With the incoming feature of comments it will be useful to have a way to report spam or abusive comments

## Expected Behavior

When reporting a post/comment a new page with a link to the post/comment should appear where you can add details of the abuse.

## Current Behavior

It doesn't exist

---

I'd like some input on places who are doing this well so please add some suggestions to this field so we can flesh out this issue.

**Comment by John-Paul-Larkin** [comment]
I gave this a go today. Didnt use any packages Niall :) Pretty happy with it, but not sure what to do with the report/data. I was thinking something like [Nodemailer](https://nodemailer.com/) to send the report to an admin, but im open to suggestions?

Also looking for feedback on the styling. I found the figma file, but I mostly just winged it.
https://youtu.be/tIwlSFcrehI

PS will i post on the discord or here? fell I would get word eyes on the discord.

**Comment by NiallJoeMaher** [comment]
Here is perfect! You've been on fire. 🔥 

This looks great and I think you should find somewhere I'm already sending emails in the codebase so there should be a utility. If not we can make that into an issue first and create that. 

What data will you send via the email? 

I was originally thinking something like a report page but this is a great simple solution that makes sure we have a reporting mechanism (ya know, before we have millions of users 💅 )

**Comment by John-Paul-Larkin** [comment]
>> You've been on fire. 
Im unemployed and learning. Open source is the next step. Already learned a ton this week. prisma, tailwind, trpc, and docker are all new to me and Git is fine is theory, but we only learn with practical application. When you get tired of me hogging the issues let me know. :)

>>I'm already sending emails in the codebase so there should be a utility.
Cool. Ill look into it.
>>
What data will you send via the email?
Just id/username of reporter and reportee, along with comment and article/post id.

ya know, before we have millions of users.
Its coming. There is already a good base of contributors. No doubt you have ideas for the site. Bring me in ill help make them happen.

**Comment by John-Paul-Larkin** [comment]
Think I have the email working, but cant test it as it uses Amazon SES. 
Just need to add an ADMIN_EMAIL to the process.env for the recipient who will recieve the reports.
I hardcoded the link to the codo.cu/articles/slug Hopefully it will work.
The email should look something this.  
![codu_reportjpg](https://github.com/codu-code/codu/assets/107807466/d497b541-a757-4d92-b3e6-3ac46e171c32)

**Comment by NiallJoeMaher** [comment]
I'm going to close this because we have more specific issues open and this is all WIP by @Fishamble
