### ISSUE TITLE
Add notifications for when a user has updates

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#174]
## Context

Currently there is no way to know when someone comments/likes your post. 

By building notifications into the app we could update the user whenever they have relevant things that they might be interested in. 

I suggest a simple version first but I'm open to suggestions.

**Comment by xiaoniuniu89** [comment]
I can take this!! Can start working on it next weekend.

**Comment by NiallJoeMaher** [comment]
@xiaoniuniu89 I've started a few pieces on this! Let me know closer to the weekend how you are doing, and I can share my progress if I haven't managed to get a basic version working.

**Comment by xiaoniuniu89** [comment]
I can do something else then, you can continue on this, I have no ideas for this yet anyways.

**Comment by NiallJoeMaher** [comment]
Initial working draft of this with #179
