### ISSUE TITLE
Embedded links in articles don't open new tab

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#175]
## Context

Embedded links in articles don't open a new tab.
Since we want to keep the user on the platform this should not be the behavior. 

## Expected Behavior

Alter the <a> node that is rendered by the markdown to open links in a new tab.

**Comment by xiaoniuniu89** [comment]
I can take this if nobody is working on it, Looks interesting, and I would like to understand how the markdown editor works!

**Comment by NiallJoeMaher** [comment]
@xiaoniuniu89 I could absolutely do with some help on this. Thanks!
