### ISSUE TITLE
Image upload inside post creation

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#181]
## Context

Currently, users have to use URLs outside of the platform to show images in posts. 
The user should be able to upload an image and get a snippet so they can add the image directly within the editor. 

Something similar to GitHub where you could drag in an image and be supplied a snippet would be fantastic (and the ideal solution) 

## Current Behavior
Currently, There is no upload option.

**Comment by NiallJoeMaher** [comment]
I'll take this one and try to come up with something simple as a first step. 🦾

**Comment by EvanBurbidge** [comment]
@NiallJoeMaher  where would the storage of these images be? S3?

**Comment by NiallJoeMaher** [comment]
This is WIP and is going to be part of the new editor checklist.
