### ISSUE TITLE
Feature/update request smaller auto save notification

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#183]
## Context

@pkspyder007 was finding the toast when autosaving articles to be a bit distracting.

## Expected Behavior

Create a more subtle notification to allow the user to know the article has been autosaved.

**Comment by NiallJoeMaher** [comment]
![Screenshot 2023-03-03 at 20 19 21](https://user-images.githubusercontent.com/12615742/222820846-67c25a38-2521-434b-b909-598c61aeb284.png)

Something like Medium might be nice and subtle. Their nav bar is sticky so it is always visible.

**Comment by patrickhladun** [comment]
I can work on this issue.

**Comment by NiallJoeMaher** [comment]
Awesome! Share what you are thinking in Discord 🥳

**Comment by NiallJoeMaher** [comment]
@patrickhladun I'm going to make a alpha editor page so you can safely add your changes and play with it. We can make an `EditorNav` component or an "edit" mode to be added to our current navigation so that we can toggle the behaviour of our navigation. 

This will be fixed today in #223

**Comment by NiallJoeMaher** [comment]
This was closed by #262
