### ISSUE TITLE
Remove automatic quotes and add new lines - Quote markdown block

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#188]
## Context

Because I can't include the authors name without it looking like parts of quotes I don't think the current format it what we should get. 

Currently if you use a Markdown quote while creating a post it auto adds quote symbols wrapping the block. 

## Expected Behavior
The quote format stays but the quote symbols are not added. 
New lines should work as expected too

## Current Behavior

What is the current behavior?
![Screenshot 2023-03-05 at 21 12 44](https://user-images.githubusercontent.com/12615742/222986326-af4d48c8-9aae-4a31-9dee-0c5c19bfd459.png)
![Screenshot 2023-03-05 at 21 13 05](https://user-images.githubusercontent.com/12615742/222986345-c4bb6347-bbca-4909-9312-4b3ba7b79b4b.png)
Seems like it could just be CSS on the ::before ::after elements:
![Screenshot 2023-03-05 at 21 13 40](https://user-images.githubusercontent.com/12615742/222986371-d02c0d06-d288-45a9-9177-63dbe1f20e86.png)

But the new lines do not work. 

## Steps to reproduce

Here's the markdown syntax for block quotes:
```
> First line
> Another line
>
> > Nested line
```

**Comment by xiaoniuniu89** [comment]
think softbreak will take care of the newlines. I was messing around with it a bit. Something like this should work, not sure if its what you are going for, this will change all blockquotes everywhere.

blockquote p::before,
blockquote p::after {
  content: none!important;
}

**Comment by MartiinWalsh** [comment]
Hey @NiallJoeMaher, I was just looking into this issue and it appears to be resolved.

Current behaviour:
- Editing:
![Screenshot 2023-05-17 at 20 29 59](https://github.com/codu-code/codu/assets/74657328/6c2abff4-7302-46ba-9b10-db5fac398412)


- Preview:
![Screenshot 2023-05-17 at 20 27 25](https://github.com/codu-code/codu/assets/74657328/09955185-6f42-46fd-9740-247e899a1a4a)

**Comment by NiallJoeMaher** [comment]
> Hey @NiallJoeMaher, I was just looking into this issue and it appears to be resolved.
> 
> Current behaviour:
> 
> * Editing:
>   ![Screenshot 2023-05-17 at 20 29 59](https://user-images.githubusercontent.com/74657328/239058423-6c2abff4-7302-46ba-9b10-db5fac398412.png)
> * Preview:
>   ![Screenshot 2023-05-17 at 20 27 25](https://user-images.githubusercontent.com/74657328/239058220-09955185-6f42-46fd-9740-247e899a1a4a.png)

Oh dang! Thanks for checking I didn't even know... 

At least that's another issue closed! 🥳
