### ISSUE TITLE
markdown editor shortcuts

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#190]
## Context

using some of the syntax for markdown editor can be difficult to remember/slow to type. It would be nice if we had some shortcuts like /media, /table, /image and the correct sytax would autocomplete for the user. 

## Expected Behavior

user can use a command like / and the editor will suggest some autocomplete options to generate markdown syntax like anchor tags, media iframes or tables etc.

## Current Behavior

User uses markdown syntax or custom tags from markdoc to write an article

**Comment by NiallJoeMaher** [comment]
This would be great! I'd love to see how you tackle this. Would be a handy way to add all sorts of features then. 🦾

**Comment by NiallJoeMaher** [comment]
We have shortcuts #201 🥳 

This my evolve in time and we can make issues for specific shortcuts.
