### ISSUE TITLE
Rich text editor view

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#197]
## Context

Some people are struggling with writing in markdown so it would be great to offer a simple rich text editor. 

## Designs

Rich text editor designs can be found here:
https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?node-id=34%3A163&t=IDwziUUI9kB13NqK-1

I'm a big fan of Medium so I've taken most of the inspiration from there. 

This paired with the shortcuts suggested by @xiaoniuniu89 (#190) would make an awesome experience.

### Note

I think this might be split into a few PRs and connected when it's all done so we can incrementally improve while getting ready for production.

**Comment by NiallJoeMaher** [comment]
As discurssed with @xiaoniuniu89 we are going to try and use https://www.slatejs.org/ and see where it goes.

**Comment by xiaoniuniu89** [comment]
I will start this week working on this feature!!!

**Comment by xiaoniuniu89** [comment]
Can we get a list of features for first draft of editor, let me know if anything can be added to this list.
Bold
Italic
Underline
link
Heading -> like medium - option to change from big to small?
Code Block
BlockQuote
Iframe embed - codesandbox, youtube etc
Image
lists

**Comment by xiaoniuniu89** [comment]
#321 issue for tracking bugs in the editor.

**Comment by xiaoniuniu89** [comment]
can close this, duplicated in tip tap story - also we will break this into smaller stories soon

**Comment by NiallJoeMaher** [comment]
Before anyone picks up this! I'm looking into a list of what we will/won't support for v1. Bare with me! <3

**Comment by xiaoniuniu89** [comment]
I will try finish this over the christmas! Last push
