### ISSUE TITLE
Refactor promptService

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#203]
## Context

the promptService is currently set up to only provide the service to one feature, the prompt that lets user know there are unsaved changes in their blog. It should be set up to be reusable to other components and take some props like <promptService message={}, prompt={} etc 

## Expected Behavior

a developer can use the promptService as a generic modal that takes in a few common arguments

## Current Behavior

the promptService is only set up to work with hard coded values for the blog editor to let user know they have unsaved changes.

**Comment by JohnAllenTech** [comment]
Sure I can take this. Can you assign it to me?

**Comment by NiallJoeMaher** [comment]
You're hooked! You can absolutely take this one. 🦾
