### ISSUE TITLE
Rebuild sponsor page with new designs

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#210]
## Context

To try get sponsors we need a better sponsor page

## Expected Behavior

The sponsor page that looks like the designs provided (some creativity or questions will be needed to make it responsive). 
https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?node-id=0%3A1&t=g5Mc4x2PfO7MW6dC-1

## Current Behavior

Has a page but not designed in the new style.

**Comment by viniirbr** [comment]
Can you assign that to me, please?

**Comment by NiallJoeMaher** [comment]
I'm going to close this and open up the issues separately to finish the page and get it production ready 🔥 Thanks for the work @viniirbr ❤️
