### ISSUE TITLE
Add MathJax library to support formulas and mathematical expressions

### ISSUE THREAD

**Issue by Ryagg** [codu-code/codu#214]
## Context

Currently, it is not possible to add formulas and mathematical expressions in a reader-friendly format. 

## Expected Behavior

Expressions like fractions, square roots, exponentiation, etc. should be displayed as intended. See screenshots below.

## Current Behavior

Depending on the input format, the expressions are either hardly readable, or just plain wrong because mathematical symbols are not rendered. Please see the screenshots below.

## Screenshots
**Example 1: expected behaviour**
![Example 1: expected behaviour](https://res.cloudinary.com/psbgbp/image/upload/v1680184762/screenshots/example1_correctly_rendered_mz7i7m.png)

**Example 1: current behaviour**
![Example 1: current behaviour](https://res.cloudinary.com/psbgbp/image/upload/v1680185855/screenshots/example1_current_behaviour_yzui8w.png)

**Example 2: expected behaviour**
![Example 2: expected behaviour](https://res.cloudinary.com/psbgbp/image/upload/v1680184771/screenshots/example2_correctly_rendered_z0mlfy.png)

**Example 2: current behaviour**
![Example 2: current behaviour](https://res.cloudinary.com/psbgbp/image/upload/v1680185944/screenshots/example2_current_behaviour_eg3aha.png)

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Enter the following snippet to a new Codú post. Please also note that the formula is displayed correctly below.
```math
n = (…(((b_{N}*B+ b_{N-1} )*B+ b_{N-2} )*B+ b_{N-3} )*B+⋯+b_{1} )*B+ b_{0}
```

Wrapping the code into $$ instead of a code block does not change the behaviour.

## Additional info

Please add the [MathJax library](https://www.mathjax.org/) to enable the use of mathematical expressions and formulas.

**Comment by AnuMessi10** [comment]
Hello, since this is an open PR, let me know if this feature is still needed and if I can be assigned to it? Cheers!

@NiallJoeMaher

**Comment by NiallJoeMaher** [comment]
As an update, we are building a new editor so we will add this as a feature request now since we are building from scratch.
