### ISSUE TITLE
Rebuild home page

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#231]
## Context

Please provide any relevant information about your setup

## Expected Behavior

The home page that looks like the designs provided (some creativity or questions will be needed to make it responsive).
https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?node-id=0%3A1&t=g5Mc4x2PfO7MW6dC-1
## Current Behavior

It is still using the original placeholder

## Screenshots
![Group 61](https://user-images.githubusercontent.com/12615742/230562165-49e2c0df-0ea0-43bd-9b1f-8ebdfd21d931.png)

Light mode components: 
![Group 62](https://user-images.githubusercontent.com/12615742/230562235-cdcdb786-bb2f-47c5-aad0-4e2ce7f540ac.png)

**Comment by sleithdylan** [comment]
Hey @NiallJoeMaher 

Just throwing this idea out there, I have already spoken to you about this but wouldn't it be cool to have instead an image of a moon with an astronaut on a rocket to have the same thing but using Three.js and then skies the limit on what you want to do with the 3D models.

I found a paid 3D illustration pack that has the models:

**Pack:** [Astronaut 3D Character Illustration](https://ui8.net/uigo-design/products/astronaut-3d-character-illustration)

**Comment by NiallJoeMaher** [comment]
@sleithdylan - Do you want to start it out to see what that would look like? That could be amazing. That could be a super eye catching landing page. If we got a decent example I'd find someone to make up some custom 3D models too.

**Comment by sleithdylan** [comment]
@NiallJoeMaher - I can try it in my own time when I am not too busy, don't assign anything yet as I am not sure if I can get around to it. But I will keep you updated if I do.

**Comment by NiallJoeMaher** [comment]
I was also thinking of using something like this as a first step: https://atroposjs.com/ And just use flat images. That might be good until we can get your expertise 😉

**Comment by NiallJoeMaher** [comment]
![space](https://github.com/codu-code/codu/assets/12615742/1c81863c-19bd-4ac7-ab7c-440cdc597dbc)
![moon](https://github.com/codu-code/codu/assets/12615742/d8143d6f-249c-421e-a944-3a8ff408dd39)
![spaceman](https://github.com/codu-code/codu/assets/12615742/09f30f9b-af16-4239-8d5f-8ea9c8db2102)

Adding the images here as reference too!

**Comment by sleithdylan** [comment]
@NiallJoeMaher Yeah, I saw the preview you posted. It looks great. But yes, we could move over to three.js down the road or something 😝

**Comment by serzhan181** [comment]
Hello! Is this feature still relevant? I am working on it and desktop version is somewhat done. I am curious if there's mobile design of this view since i couldn't find one in figma? Or am I free to improvise?

**Comment by NiallJoeMaher** [comment]
Hey @serzhan181! There is already a PR open for this one. I'll add a few more screens this evening. We have a lot coming, you can see the designs coming along here - https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?type=design&node-id=0%3A1&t=Al3c9nLcRXAYeYf1-1

**Comment by sonngdev** [comment]
is this issue still in active development or should I help?

**Comment by NiallJoeMaher** [comment]
I will have a version of this WIP at the moment. I've a few other pages I could send you if you want a stab?

I'll make a couple of issues and tag you @thanhsonng!
