### ISSUE TITLE
Excerpts not being generated when left empty

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#259]
## Expected Behavior

When a user creates a new post and publishes it without giving it an excerpt we should generate one from the start of the text.

## Current Behavior

This doesn't happen so there is a bug somewhere.

**Comment by JohnAllenTech** [comment]
Can you assign this to me. Should be easy enough to fix

**Comment by JohnAllenTech** [comment]
Hmmm think I have this working

So i just grab the first 156 chars from the article and prepopulate the excerpt text area with these.

However those chars might have the markdown syntax in them which isnt great. Doesnt seem like the excerpt is being rendered in markdown either just plain text.

I can probably parse the excerpt generated and go from markdown to plain text. What does everyone think? Ill attach a screen shot

![image](https://github.com/codu-code/codu/assets/46611809/557d4347-e828-49ad-8e8e-939ae8fa5e13)

**Comment by NiallJoeMaher** [comment]
I have a function in the backend that might handle this because I was going to add the excerpt to the database if it doesn't exist.

**Comment by JohnAllenTech** [comment]
Do you have the function name?

**Comment by NiallJoeMaher** [comment]
Let's see if this works: 
https://github.com/codu-code/codu/blob/76cfdc138c7c82939dfe64c59d0bf2e9f188fa68/server/trpc/router/post.ts#LL80C18-L80C18

Should bring you to the line
