### ISSUE TITLE
Add banner on sidebar for writing challenge

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#272]
## Context

To try and get people to signup and write we are going to show the temporary writing challenge. 

It will also help us get metrics on click-throughs. 

The first issue is to add a banner before we can track it: 

![challenge](https://user-images.githubusercontent.com/12615742/235794550-9277392b-c914-4e3d-a90d-7d4b427c6e18.png)
![Group 63](https://user-images.githubusercontent.com/12615742/235794634-ccc930ce-a27a-46ad-a270-e2625a49ec6f.png)

![Screenshot 2023-05-02 at 22 49 07](https://user-images.githubusercontent.com/12615742/235793555-afe86e48-91cc-4770-a234-9fbe3203e1fa.png)

**Comment by JohnAllenTech** [comment]
Are you thinking a reusable component for this or just the PNG/SVG in a div?

**Comment by NiallJoeMaher** [comment]
@JohnAllenTech - This image inside a container with the text: ![image](https://user-images.githubusercontent.com/12615742/236921538-e6d3c16e-fd56-457b-b003-f79affd201c9.png) and then the link going here: https://www.codu.co/articles/join-our-6-week-writing-challenge-quohtgqb

If that makes sense? 

The Figma for the site designs is here: https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?type=design&node-id=159%3A167&t=KETEwehLrAZbzaI8-1

**Comment by JohnAllenTech** [comment]
Sure. I hacked it together by just using the image you provided and displaying that.

![image](https://user-images.githubusercontent.com/46611809/236927027-55e25601-3564-4c85-90d9-b42944e7d5f1.png)

Ill do it properly tomorrow if you want a reusable component for future announcements

**Comment by NiallJoeMaher** [comment]
That's perfect @JohnAllenTech! I think open a PR with this for now and we can worry about migrating it to a reusable component after 🙌
