### ISSUE TITLE
Fix canonical URLs on Articles

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#283]
## Context

The canonicaol URL is not displaying in the meta data for articles
It is in this file: `pages/articles/[slug].tsx`

## Expected Behavior

If the user provides a canonical url we should show the canonical meta data.
This should be included in the `<head>` of the document. 

## Current Behavior

No canonical data being shown

**Comment by NiallJoeMaher** [comment]
Might be useful if you haven't come across canonical URLs https://yoast.com/rel-canonical/

**Comment by JohnAllenTech** [comment]
Sure I can grab this
