### ISSUE TITLE
Update alpha/sponsorship page with webp images and use CSS to tilt them. 

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#285]
## Context
Currently we are using .png files for the images and they are chunky and slow. For optimising we should use .jpeg or webp image formats to stop the images being so large. 

## Expected Behavior

Images have a more suitable extension and faster load times/ 

## Current Behavior

Slow stuttering loading of images because they are too detailed for PNGs. 

## Screenshot
The page can be seen here: https://www.codu.co/alpha/sponsorship

**Comment by sonngdev** [comment]
I can take this issue @NiallJoeMaher
