### ISSUE TITLE
Add no-index meta tag to alpha/sponship page

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#286]
## Context
To avoid the test page being indexed we should add a no-index flag.

This can be done by adding the meta tag to the page: `<meta name="robots" content="noindex">`

## Current Behavior

Indexed as a normal page. 

## Screenshot
The page can be seen here: https://www.codu.co/alpha/sponsorship

**Comment by kera-cudmore** [comment]
Would love to have a go of this issue :)

**Comment by NiallJoeMaher** [comment]
Absolutely!
