### ISSUE TITLE
alpha/sponsorship - Add download of a pdf to find out more button 

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#287]
## Context

The "find out more" button currently does nothing. This should should download a pdf be done with a anchor tag. 
Here's a guide: https://www.codu.co/articles/how-to-create-a-download-link-in-html-7psjkafo

## Expected Behavior

Users can download the attached PDF by pressing the button. 

[Link to PDF](https://github.com/codu-code/codu/files/11565972/v1.pdf)

## Additional info

Page can be found here: https://www.codu.co/alpha/sponsorship

**Comment by MartiinWalsh** [comment]
Hey, I can take this one. 
Just to confirm, should the PDF be downloaded instead of opening it in the browser when the 'find out more' button is clicked?
Also, is there a particular directory structure you would like to use for files? i.e. public/files/<pdf-file>

**Comment by NiallJoeMaher** [comment]
I originally thought to download it, but I think opening a new page with the PDF might be safer. I'm not sure if I would want to download things always. Thanks for the thought! I didn't even think of that 🙈

So let's say it opens in the browser, so instead of a download link, we can refer directly to the folder/file. 

Good question @martinw-dev! - Let's make it `public/sponsorship/docs/info.pdf`. Overly verbose but will keep things clean as we scale it.
