### ISSUE TITLE
[Feature Request] Welcome GitHub Action

### ISSUE THREAD

**Issue by CBID2** [codu-code/codu#292]
I noticed that there hasn't been any GitHub actions setup, so I was thinking of creating one that welcomes contributors, especially if they are new to the project.

**Comment by NiallJoeMaher** [comment]
@CBID2 - This is a fantastic idea! Would really like this. Do you have any ideas on how it greets? Or an example of one?

**Comment by CBID2** [comment]
> @CBID2 - This is a fantastic idea! Would really like this. Do you have any ideas on how it greets? Or an example of one? 

Here's two that I found @NiallJoeMaher: https://github.com/marketplace/actions/welcome-new-contributors

https://github.com/marketplace/actions/welcome-new-users

**Comment by NiallJoeMaher** [comment]
I should of closed this ages ago but as an FYI @CBID2 this is one of my favourite additions. Thanks! 🦾
