### ISSUE TITLE
[Feature Request] Security Policy needed

### ISSUE THREAD

**Issue by CBID2** [codu-code/codu#298]
## Context

The project's security  

## Expected Behavior

A full checklist

## Current Behavior

Hi @NiallJoeMaher! :) I just reviewed the project's [Community Standard Checklist](https://github.com/codu-code/codu/community) and noticed that it is not completely full due to missing a security policy
## Your Solution
I think we should add a security policy to the project because it will minimize the risk of receiving unauthorized commits and security is a top concern according to [this year's Open Source State Report](https://blog.opensource.org/the-2023-state-of-open-source-report-confirms-security-as-top-issue/). If approved, I'd be glad to implement this policy.

**Comment by NiallJoeMaher** [comment]
Awesome idea! @CBID2, you have eagle eyes. Thanks for this. Would you mind implementing it still?

**Comment by CBID2** [comment]
> Awesome idea! @CBID2, you have eagle eyes. Thanks for this. Would you mind implementing it still? 

Yep @NiallJoeMaher. I'll present it. Then, you give feedback and we'll take it from there.Sounds good?

**Comment by NiallJoeMaher** [comment]
I didn't see this reply! Very happy to give feedback @CBID2. Thanks!!!

**Comment by CBID2** [comment]
> I didn't see this reply! Very happy to give feedback @CBID2. Thanks!!!

Here it is @NiallJoeMaher: #306
