### ISSUE TITLE
[Feature request] Turn off comments on certain posts/articles

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#301]
## Context

For certain posts (eg. platform announcements), we should disable comments.
This is an admin specific so the update needs to be on the `Posts` model and should offer no comments section when flagged.

We don't need an interface since there will only be a handful of posts like this (for now anyway) and it will be easy enough to just update the DB directly as a first step. 

## Expected Behavior

Comments should be turned off on certain articles. 

## Current Behavior

Comments are always visible.

**Comment by viniirbr** [comment]
I can take this one, @NiallJoeMaher
