### ISSUE TITLE
Ability to embed CodePens/CodeSandbox in markdown

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#31]
Since I am guessing it will be primarily coding articles. Having interactive embeds would be handy.

**Comment by pkspyder007** [comment]
I'll pick this up

**Comment by pkspyder007** [comment]
I tried to make this work but current markdown library won't allow this, I'll give it another try with a different package with same features

**Comment by NiallJoeMaher** [comment]
I think we will need to migrate to https://markdoc.dev/ to make things a lot more flexible. But I am open to suggestions.

**Comment by jh3y** [comment]
Sounds kinda funky but we could do this with `ReactMarkdown` as a quick fix if you have an idea or we could settle on a way that people would be happy to write their CodePen snippet.

You can write any Markdown and have it swapped out with Custom Components. You could do something interesting like:

```html
<codepen id=id></codepen>
```

And have the `ReactMarkdown` take the attributes off of the tag and convert to an actual component.

```jsx
<CodePen id={id} />
```

I assume this would work based on [this](https://www.npmjs.com/package/react-markdown#use-custom-components-syntax-highlight).

**Comment by NiallJoeMaher** [comment]
Completed with #156
