### ISSUE TITLE
[Bugfix] Notifications list needs padding

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#310]
## Context

Currently the body of the notification has no space to breathe from the title.
We should add a `mb-4` to the title area to give the notifications and/or no notification better spacing.

## Expected Behavior

Content is not squashed against the title section. 

## Current Behavior

See below

## Screenshots

Provide any additional information here
![Screenshot 2023-06-14 at 19 57 43](https://github.com/codu-code/codu/assets/12615742/007cec51-bdfe-4cda-8536-aa367fde5e12)

**Comment by sonngdev** [comment]
I can take this issue

**Comment by NiallJoeMaher** [comment]
Absolutely!
