### ISSUE TITLE
[Feature] Show users website if they have added one in their profile

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#311]
## Context

Currently we allow users to add a URL to their profile.
We do not show this anywhere.

Add a users link to the end of their profile.

We are using hero icons for the links and a color of `blue-500` on the text for the link.

This should only show the domain of the link eg:
`https://www.niall.af` would show as `niall.af`
`https://www.niall.af/fun` would show `niall.af/fun`

## Expected Behavior
![Group 73](https://github.com/codu-code/codu/assets/12615742/4f7115b0-97e9-40f5-9f69-9a28fb832aae)

Ask any questions below!

**Comment by viniirbr** [comment]
could you assign this for me, sir?
