### ISSUE TITLE
Expanding menu Icon visible when highlighting blank lines

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#322]
We are trying to have a + icon when user goes to a blank line, the idea being that when clicked it will open an expanding menu where the user can select iframe, img etc.

At the moment if the user was to highlight all lines in the editor , the + icon would appear on **all** blank lines.

When the user highlights other text they should not see this + icon, they should only see on the line they are focused on. 

<img width="661" alt="Screenshot 2023-06-24 at 18 49 28" src="https://github.com/codu-code/codu/assets/84312595/53fb7b8a-e69c-4513-9680-2f384627f20d">

this functionality is in the custom paragraph plugin.

**Comment by jgyfutub** [comment]
can you assign me this issue?
