### ISSUE TITLE
Add space for advertising banner on articles and feed

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#33]
We need to make some money to get swag for contributors and events. I think the simplest start is having some non-invasive ads in the sidebar. If anyone has any alternative ideas, that would be great but would like to pilot this. 

I think we can start with a placeholder that brings people to the sponsors page.

**Comment by NiallJoeMaher** [comment]
Maybe something like this as an example ad
![image](https://user-images.githubusercontent.com/12615742/197576474-50860172-1398-4866-babf-c2faba4259aa.png)

**Comment by LauraMayock** [comment]
Hi Niall, I was looking into this one and apparently, the sidebar is the best way to go. A 300X600 sidebar on the right side is the most beneficial after the prime top-fold space.  I was thinking of creating a sticky sidebar with the above background image containing a link with a contact form/info. 
For mobile phones convert it to a banner under your main into info. 

Info on add placement
[https://setupad.com/blog/best-place-for-ads/](Add placement Optimization)

**Comment by NiallJoeMaher** [comment]
Thanks for reviving @LauraMayock  this idea to make me rethink it. I've been taking a look at how other useful blogs tackle it. 

I also saw my friend @flaviocopes's blog has a really good layout for this stuff, too so it might be useful to mimic. 

The sidebar shouldn't be sticky because I don't want the ads to be too invasive. 

I'll link in some designs shortly if you're interested in tackling it?

**Comment by NiallJoeMaher** [comment]
@LauraMayock here are the new designs that I just mocked up - Would love to know what you think: https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?node-id=0%3A1&t=jHbf9Gguovvbt3G8-1

**Comment by LauraMayock** [comment]
Looks Fab @NiallJoeMaher Would love to take it on.

**Comment by NiallJoeMaher** [comment]
Reach out on Discord if you need some help or want to bounce ideas.
