### ISSUE TITLE
Create Courses Page

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#333]
## Context

Under the `/alpha` route create a first version of the courses page. 

The desktop designs can be found on Figma [here](https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?type=design&node-id=343%3A163&mode=design&t=rIo2VOcs0uhcHE7G-1).

It should include the same navigation as all other pages. 

## Expected Behavior

It should look like this:
![image](https://github.com/codu-code/codu/assets/12615742/68517fee-0fc2-45d1-9fb5-a99616edd268)

Ideally, this would be responsive but I haven't designed it so I'm happy for some input here. 

## Screenshots

![image](https://github.com/codu-code/codu/assets/12615742/68517fee-0fc2-45d1-9fb5-a99616edd268)

**Comment by NiallJoeMaher** [comment]
@thanhsonng in case you are interested 😉

**Comment by sonngdev** [comment]
Sure, let me take this issue 😄
