### ISSUE TITLE
Create Course Overview Page

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#334]
## Context
As we hope to offer free courses, this is where users will be able to see their progress on a course. 

Under the `/alpha` route, create the first version of the course overview page.

A route like `/alpha/courses/web-development` might make sense for this one. 

The desktop designs can be found on Figma [here](https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?type=design&node-id=343%3A163&mode=design&t=rIo2VOcs0uhcHE7G-1).

It should include the same navigation as all other pages.

For this initial draft, the data can be hard coded, and we can make the data dynamic in a later issue.

So this task is purely frontend. 

## Screenshots

![image](https://github.com/codu-code/codu/assets/12615742/7e10eb73-9161-4184-b7e9-65bf02697675)

**Comment by serzhan181** [comment]
Looks good. Can i grab this one?)
