### ISSUE TITLE
Add link to "Learn More" on /alpha

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#341]
## Context

Currently the link from "Learn More" on the `/alpha` is empty. 
Add link to "Learn More" on /alpha.
The link should be `/articles/explore-the-benefits-of-being-a-part-of-cod-ety1wehv` which is an article on production that will show the benefits of joining Codú.

## Current Behavior

Nothing...

## Screenshots

![Screenshot 2023-07-04 at 08 28 32](https://github.com/codu-code/codu/assets/12615742/83b68701-6379-4ecf-8200-d2ae0e013858)

## Steps to reproduce

Go to `/alpha` to find the page. 
Click the "Learn More" button.

**Comment by sudarshansb143** [comment]
@NiallJoeMaher  Can you assign this to me ?

**Comment by sudarshansb143** [comment]
@NiallJoeMaher  Shall I put the final page URL as implemented following ?
```jsx
  <div className="mt-10 flex items-center gap-x-6">
                    <Link href="/get-started" className="primary-button">
                      Get started
                    </Link>
                    <a href="https://www.codu.co/articles/explore-the-benefits-of-being-a-part-of-cod-ety1wehv" className="leading-6 text-gray-900 font-semibold">
                      Learn more <span aria-hidden="true">→</span>
                    </a>
                  </div>
```

**Comment by NiallJoeMaher** [comment]
Simply `/articles/explore-the-benefits-of-being-a-part-of-cod-ety1wehv` should be fine! On prod it will reference the right place.

**Comment by sudarshansb143** [comment]
Got it.
