### ISSUE TITLE
Migrate to App Router (Next.js)

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#410]
## Context

To start using some of the new benefits and stay up with the cool kids, I'd like to migrate the project to use the [app router](https://nextjs.org/docs/app).

## Expected Behavior

There should be no visible behavior changes for the end user during this migration.
By the end of the migration, there should be no `pages` folder. 

## Additional info

As a test, I would suggest we start with only moving the `/alpha` route so that we can ensure it doesn't effect any of the public routes when we dive deeper. 

We can create sub-issues to break this one up into logical parts.

**Comment by NiallJoeMaher** [comment]
UPDATE: I tried to move things, and it looks like `next-auth` isn't too stable with it yet. But they are preparing for a 5.0 release, which should give the ability to use the app router.

**Comment by NiallJoeMaher** [comment]
Another update! I was wrong... I'll get back to this after my current PR is merged.

**Comment by s0ham075** [comment]
Hey can I help you with this?

**Comment by NiallJoeMaher** [comment]
@s0ham075 sure thing! The very first task will be getting a route to work with Next-auth. Once that's implemented we can go page by page as PRs. So if you are feeling brave you can start with the Next-auth for the API route. Or if not let me know and I'll get it done ASAP.

**Comment by s0ham075** [comment]
Thanks ! I will try to get it done, however if I am unable to do so I'll surely let you know
