### ISSUE TITLE
Create a Codú curriculum template

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#421]
## Context

To aid in our mission to teach people for free, we need a curriculum. 
I'll create this issue as a placeholder in case anyone thinks about the initial structure. 

We will need another issue which I'll create, surfacing anything from the Codú curriculum on the actual website. 
## Expected Behavior

We have a repository where people can contribute to the curriculum. 
It should be a simple text-only curriculum for version 1. 

## Current Behavior

We don't have a curriculum.

**Comment by apcoyne** [comment]
This is something I can actually help with ! Tag me in coach!

**Comment by NiallJoeMaher** [comment]
Yes sir! Let me know what you're thinking. 🦄

**Comment by NiallJoeMaher** [comment]
I've created a new repo - where I'll recreate all the issues around content for the curriculum: [https://github.com/codu-code/curriculum](https://github.com/codu-code/curriculum)

It's empty, but we can move discussions or additions to there.
