### ISSUE TITLE
Surface curriculum content on codu.co

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#422]
## Context

We have an issue #421 to start a curriculum for Codú! 🥳 

We need to surface this inside the website. So, we should surface the content inside the `/alpha` folder when the curriculum has a single template to prove the concept. 

## Expected Behavior

We expect users to be able to view the content from the curriculum repository (#421).

## Current Behavior

We don't have a course yet. 😢 

## Screenshots

We can develop screenshots and designs once we have the data surfaced.

**Comment by NiallJoeMaher** [comment]
Using Markdoc, like our current articles, create a way to dynamically show the markdown files in the `/curriculum` folder.

I'm open to suggestions on how we can make it more sophisticated, too (eg. quizzes, code challenges). 

Create a `/alpha/course/intro-to-react/introduction` route that surfaces the formatted article.

**Comment by John-Paul-Larkin** [comment]
Assign me please Niall. I will look at this tomorrow.

**Comment by John-Paul-Larkin** [comment]
Hi Niall,
Just a short video to see if I am going about this issue correctly.

https://youtu.be/K5n7CgiYys4
