### ISSUE TITLE
New Feature Request: Developer Interviews

### ISSUE THREAD

**Issue by kera-cudmore** [codu-code/codu#425]
## Context

My boss was recently interviewed for a blog where they interview different developers each week/month about their developer job, how they got started, what tech they use, what they're currently learning/excited about, book recs etc.

Thought this could potentially be a cool feature to add to the site, especially as we have such a wide range of developers at all stages using lots of different tech

**Comment by NiallJoeMaher** [comment]
Are you thinking a series or a weekly/monthly feature on developers answering questions?
A podcast or text format? 

Really fun idea tbh!

**Comment by kera-cudmore** [comment]
Hmmm... could be either/both to be honest!

I know that I'm always interested to know what other developers do for their jobs - but also what they're spending their free time learning/doing too

**Comment by s0ham075** [comment]
What if we show the skill or technology the user is learning on user profile page?? Similar thing could be done for the what they do at their job. Also we can create a timeline component which shows the previous such technologies the user was learning , essentially creating a roadmap of their journey, which we can customize to add the book, resources etc which they used to learn that particular technology

**Comment by NiallJoeMaher** [comment]
@kera-cudmore I'm thinking a podcast for some extra content 😉 
![codercast](https://github.com/codu-code/codu/assets/12615742/a2bf1509-3dad-474e-ab18-0f7b0f000e2a)

@s0ham075 I think it could be useful to be able to tag people's profiles with certain technologies eg someone could pick "AWS", "NODE", "JAVASCRIPT". Might help if we want to try and help people get job placements in the future too

**Comment by anyahush** [comment]
I think this is an awesome idea! I'm always curious as to what other devs do in their day-to-day jobs. Would be keen to help/contribute on this one :)
