### ISSUE TITLE
Refactor create page

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#426]
## Context

The create page is becoming quite hard to maintain. It would be good to extract the business logic out into a useCreatePage hook and/extract some of the jsx out like all of the wrappers. 

## Expected Behavior

As a developer, I can easily navigate the create page, so I can add/update features without relying on the search feature to get back to where I need.

## Current Behavior

The logic for updating and creating and fetching data is in one huge clump. The important jsx like, editor, preview etc is lost in a sea of jsx and it is hard to get to where you want.

**Comment by xiaoniuniu89** [comment]
can assign to me , will shoehorn refactoring business logic into a hook in my next pr re markdown support so we can clean this page up a bit

**Comment by NiallJoeMaher** [comment]
This might be easier with the new `/app` router too. When we can have errors and layouts in different files.

**Comment by John-Paul-Larkin** [comment]
Hi Daniel. Have you got to this yet? 
I wouldnt mind giving it a try.

**Comment by xiaoniuniu89** [comment]
go for it

**Comment by xiaoniuniu89** [comment]
I think we can close this. there is a useCreatePage hook that makes page more readable now.
