### ISSUE TITLE
Add light/dark theme to articles

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#432]
## Context

So we can give a better user experience we are working on a light/dark mode.

## Expected Behavior

We use Tailwind so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

## Current Behavior

By default, we only use a dark theme. 
You can see an example post here: https://www.codu.co/articles/hactoberfest-2023-with-cod-jh-6jzte

## Additional info

The background for light mode should be: `bg-neutral-100`
The text should be: `text-neutral-900`

**Comment by Mrst12** [comment]
Can I work on this please 😊 just need to know which page to code on as there is various pages linked to article (sorry to be thick dont want to step on  anyones toes, and first time doing open source so want to put code in the right file)

**Comment by NiallJoeMaher** [comment]
Not a problem! We will help out if you get stuck. 

It’s here: https://github.com/codu-code/codu/blob/develop/pages/articles/%5Bslug%5D.tsx

**Comment by Shrenik0321** [comment]
hey @NiallJoeMaher , would love to work on this issue if there weren't any updates

**Comment by Mrst12** [comment]
hi @NiallJoeMaher ive had a play around with dev tools to find out how to change the light/dark for the articles page ive attached the screenshots when i uncheck the box it has the right styles for light but not dark when its checked it has the right styles for dark but not light i have searched everywhere where can i change this code for light and dark mode it seems to be inherited from the components in the global css line 18 attached screenshot file, sorry but im not sure how to proceed as dont know where to change this inherited code 🤔
<img width="1792" alt="dev-tools-light" src="https://github.com/codu-code/codu/assets/66439480/8f756551-b918-4133-88ad-d384d99910e6">
<img width="1775" alt="dev-light" src="https://github.com/codu-code/codu/assets/66439480/c86bd9c4-0162-47ea-8918-cbdfa5c27429">
<img width="1778" alt="dev-tools-dark" src="https://github.com/codu-code/codu/assets/66439480/c2bb58e2-5b55-454c-a12f-4d37500e7054">

<img width="1757" alt="dev-dark" src="https://github.com/codu-code/codu/assets/66439480/1fd1b8a3-bc03-4377-9922-43b43a4b5242">
<img width="446" alt="css-18" src="https://github.com/codu-code/codu/assets/66439480/848b1b45-68f8-4a37-9464-63647b8233d4">

**Comment by NiallJoeMaher** [comment]
Let me take a look into it for you. Great job so far so don't panic. 🦾

**Comment by abhijeetgurle** [comment]
I can take this up @NiallJoeMaher.

**Comment by NiallJoeMaher** [comment]
Thanks, I haven't gotten around to it yet. 🦾

**Comment by NiallJoeMaher** [comment]
@abhijeetgurle, how is it going? Anything I can help with?

**Comment by abhijeetgurle** [comment]
@NiallJoeMaher I couldn't work on this issue yesterday. Will work on it today. Will let you know if help is needed.

**Comment by abhijeetgurle** [comment]
Can you check the PR @NiallJoeMaher ?
