### ISSUE TITLE
Add light/dark theme to articles feed page

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#433]
## Context

So we can give a better user experience, we are working on a light/dark mode.

## Expected Behavior

We use Tailwind so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

## Current Behavior

By default, we only use a dark theme. 
You can see the feed here: https://www.codu.co/articles

## Additional info

The background for light mode should be: `bg-neutral-100`
The text should be: `text-neutral-900`
The cards should have a background of: `bg-white`

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by NiallJoeMaher** [comment]
All yours! Thanks @pateldivyesh1323

**Comment by pateldivyesh1323** [comment]
@NiallJoeMaher current app is running on dark mode, can you tell me how to switch the modes so that I can develop light theme
