### ISSUE TITLE
Profile page should have light/dark mode

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#434]
## Context

So we can give a better user experience, we are working on a light/dark mode.

## Expected Behavior

We use Tailwind so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

## Current Behavior

By default, we only use a dark theme. 
You can see the feed here: https://www.codu.co/settings

## Additional info

The background for light mode should be: `bg-neutral-100`
The text should be: `text-neutral-900`
The cards should have a background of: `bg-white`
borders for light mode should be: `neutral-100`

If there is more questions let me know as I'm sure I've missed something!

**Comment by Danishkar** [comment]
Can i work on this?

**Comment by NiallJoeMaher** [comment]
@Danishkar I assigned you another. So if this is still open when it's done absolutely. 🦾

**Comment by pateldivyesh1323** [comment]
@NiallJoeMaher Now I can start working on this. Can I get this assigned?

**Comment by NiallJoeMaher** [comment]
All yours @pateldivyesh1323. Attach some screenshots to the PR so we can see it when you get it done. 🦾 Thanks!
