### ISSUE TITLE
Editor should have light/dark mode

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#436]
## Context

So we can give a better user experience, we are working on a light/dark mode.

## Expected Behavior

We use Tailwind, so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

## Current Behavior

By default, we only use a dark theme. 
You can see the editor here: https://www.codu.co/create

## Additional info

The background for light mode should be: `bg-neutral-100`
The text should be: `text-neutral-900`
The cards should have a background of: `bg-white`
borders for light mode should be: `neutral-100`

If there is more questions let me know as I'm sure I've missed something!

**Comment by pateldivyesh1323** [comment]
@NiallJoeMaher I would like to work on this.

**Comment by NiallJoeMaher** [comment]
@pateldivyesh1323 I've assigned another one to you already so once that PR is open you can check back here and I can assign it if nobody else has started. 😁

**Comment by pateldivyesh1323** [comment]
@NiallJoeMaher ok

**Comment by MuzhdaN** [comment]
Hi :) 
If this is not taken, can I take this one?

**Comment by NiallJoeMaher** [comment]
All yours @MuzhdaN

**Comment by Sidopolis** [comment]
HI Sir 
Can i get this one ?

**Comment by MuzhdaN** [comment]
Hi,

On the editor page, I've noticed that some texts are using a grayish color (text-neutral-400). However, in the above requirements you didn't specify a color for this, so I've applied text-neutral-500 to "how to use the editor part" section for test. I wanted to check with you to see if this is acceptable.

Additionally, the buttons currently have a white background in light mode. Do you want this to remain as is, or should I make any adjustments?

Thank you,

here is the screenshot for the editor page:

![Screenshot 2023-10-10 151052](https://github.com/codu-code/codu/assets/79607397/ccb9217a-37d4-4098-893c-0c8a4890ea1a)
