### ISSUE TITLE
Add a light/dark/system theme switcher

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#437]
## Context

Currently we have no way to toggle light and dark themes other than relying on system settings. 
We should give the user an option to toggle light/dark/system modes. 

## Expected Behavior

The user can easily change themes.
We should use next-themes: https://www.npmjs.com/package/next-themes

## Help with ideas please

I'm unsure where the best place is to locate this button/dropdown so happy to take some ideas before tackling.

**Comment by Prasanthisandaka2005** [comment]
Hello @NiallJoeMaher 

Myself Prasanthi Sandaka
Implementing a theme toggle is a great idea for enhancing the user experience on your platform. Here are a few ideas on where we could place this button/dropdown:

![Screenshot (51)](https://github.com/codu-code/codu/assets/122683084/bcc4d05d-06a8-401f-94b9-5e776f11fbc5)

I'm excited to take on the task of implementing the theme toggle feature. It's a valuable addition to your platform that will enhance the user experience. I'm eager to learn and make a positive impact. Can you please assign this to me?

**Comment by NiallJoeMaher** [comment]
Hey @Prasanthisandaka2005! I was thinking of something a little more subtle. If we can I like to use [hero icons](https://heroicons.com/) (since it's already installed) like in here: https://syntax.tailwindui.com/

With the default state of the system, we can have the light/dark modes. 

Maybe even putting this in the footer will suffice for now, and we can figure out some better, more evident placing when it's working. 

Let me know what you think. 🦾

**Comment by DarrachBarneveld** [comment]
Added a basic demo
![giphy](https://github.com/codu-code/codu/assets/130994206/c93edc9d-c95f-48c1-865b-367f5fe8974c)

**Comment by NiallJoeMaher** [comment]
@DarrachBarneveld nice! Open up a PR. This will do nicely for now. 🦾 If you need help, let me know.

**Comment by NiallJoeMaher** [comment]
Closed with #442
