### ISSUE TITLE
Update Twitter icon in footer to be new "X" icon

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#439]
## Context

Update the Twitter icon in the footer to the new "X" icon.

It should have the same size and styling of the current Twitter icon. 

The footer is on all pages so it should be easy to find!

**Comment by Prasanthisandaka2005** [comment]
Hey @NiallJoeMaher can you assign this to me?

**Comment by NiallJoeMaher** [comment]
Hey @Prasanthisandaka2005! I'll assign this when you have #440 merged. To give some other contributors a chance to pick it up, too. Thanks!

**Comment by Prasanthisandaka2005** [comment]
Hey Is it possible to submit my pull request on October 1st so that it will be counted for Hacktoberfest?

**Comment by Danishkar** [comment]
Can i work on this?

**Comment by NiallJoeMaher** [comment]
All yours @Danishkar!

**Comment by NiallJoeMaher** [comment]
Closed with #444
