### ISSUE TITLE
Articles "Share to Twitter" to "Share to X" 

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#440]
Update the text "Share to Twitter" to "Share to X" in the sharing panel in the article page.

You can view any article to see where this is.

## Screenshot
You can see it's current state here: 
<img width="881" alt="Screenshot 2023-09-28 at 21 59 11" src="https://github.com/codu-code/codu/assets/12615742/e6e9d1c5-d8bf-4ec3-a332-28769cda9075">

**Comment by Prasanthisandaka2005** [comment]
Hey @NiallJoeMaher can you assign this to me?

**Comment by var-rishabh** [comment]
Hey @NiallJoeMaher 
Its been 2 days and this issue is not resolved yet.

Can you please assign this issue to me, so that I can resolve this issue quickly.

**Comment by NiallJoeMaher** [comment]
@var-rishabh sure, I see the PR is open. In future it would be great if you made sure you were assigned first. Especially with Hacktoberfest there is a lot people that want to pick up their first issues.

**Comment by var-rishabh** [comment]
@NiallJoeMaher 
Thank you for your feedback and understanding. I'll definitely ensure I'm assigned before submitting any future pull requests.
Please can you check and review my PR #452 and merge it so I can contribute in this repo and hacktober as well. :)
