### ISSUE TITLE
Bump Next.js version to 13.5 

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#447]
## Context

There is performance benefits in Next.js 13.5,
Let's bump the version so we get it! 📈 

## Expected Behavior

Next.js should be at version 13.5

**Comment by Snowfall22** [comment]
interested

**Comment by NiallJoeMaher** [comment]
🪄 All yours @Snowfall22!

**Comment by Snowfall22** [comment]
thanks!

**Comment by NiallJoeMaher** [comment]
Closed with #450
