### ISSUE TITLE
Add dropdown option to filter by bookmarked on articles page

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#451]
## Context

Add dropdown option to filter by bookmarked on articles page.

## Expected Behavior

When user is logged in they get an option to only show bookmarked articles.

## Current Behavior

current options are 'Newest' 'old' 'top'

## Screenshots
![bookmarks](https://github.com/codu-code/codu/assets/107807466/0168fd4c-4c0f-427e-b351-2b4334b91a37)

**Comment by NiallJoeMaher** [comment]
Ah! I know it's not obvious, but we do have a `saved` page actually: https://www.codu.co/saved

I think we probably need a better way of surfacing it, to be honest. 

If you click your profile icon you can see "saved posts".

Maybe we can look at adding a sidebar with "recent saves" or something like that like they have on Medium. 
<img width="1792" alt="Screenshot 2023-10-01 at 11 03 50" src="https://github.com/codu-code/codu/assets/12615742/6f1d1f4f-a0c1-4639-b0fc-e60be3371475">

Then when you click "See all" it will take you to the `saved` page.

**Comment by John-Paul-Larkin** [comment]
OK. well I already have the dropdown done. Just forgot to make a pull request. its pretty simple. You can have a look anyway and decide if you want to keep it. I have dropdown option as bookmarked, but could change to saved easily.
Ill have a go at implementing the sidebar.

**Comment by NiallJoeMaher** [comment]
Perfect, I'll close the current PR for the upcoming one. Great idea though. Something that I didn't think of.

**Comment by John-Paul-Larkin** [comment]
Right now the sidebar has a different width on the article page and the home page. As displayed in this image of them side be side. The home page sidebar has a col-span of 5, while the article page sidebar has a col span of 4. 
That appear to be the only difference. Is this for a partiular reason, styling or otherwise?
Will I extract these to a componet which can be shared between the pages? I can pass a prop to specify the col-span.
Or should I leave the home page alone?

![Screenshot 2023-10-02 221615](https://github.com/codu-code/codu/assets/107807466/e9eab2b0-f3c6-4b58-8d42-d1d733a03852)

**Comment by John-Paul-Larkin** [comment]
What i have so far. Styling feedback?
![Screenshot 2023-10-03 003907](https://github.com/codu-code/codu/assets/107807466/a315513d-d615-440c-a522-539ed9150fca)

**Comment by NiallJoeMaher** [comment]
Sorry I missed this till now! I like it. Just keep the saved posts for now. Also remove the pink border just to keep it clean and different. Maybe add the author under the title so the article title is up first and easier to spot on the small format. 

Thanks for this @Fishamble!
