### ISSUE TITLE
Footer should have light/dark mode

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#462]
## Context

Add a footer that can change with light and dark mode. 
So we can give a better user experience, we are working on a light/dark mode.

## Expected Behavior

We use Tailwind, so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

## Current Behavior

By default, we only use a dark theme. 
You can see the feed here: https://www.codu.co

## Additional info

The background for light mode should be: `bg-neutral-100`
The text should be: `text-neutral-900`
The cards should have a background of: `bg-white`
borders for light mode should be: `neutral-100`

If there is more questions, let me know as I'm sure I've missed something!

**Comment by NiallJoeMaher** [comment]
@pateldivyesh1323 I think this one is for you. ⚡️ Comment if you want it!

**Comment by pateldivyesh1323** [comment]
@NiallJoeMaher Yes, I would like to work on it.
