### ISSUE TITLE
Mobile Navbar refactor

### ISSUE THREAD

**Issue by DarrachBarneveld** [codu-code/codu#464]
## Context
Refactor the mobile elements. This will allow quick customisation and ui changes to both elements. Update minor style changes and add all theme changes.

## Expected Behavior
Same expected utility. Additional theme toggle on mobile devices. Drop down bar will be styled appropriately. Use of minor css animations for dropdown smooth flow on mobile device.

## Current Behavior
Current navigation will remain the same

What is the current behavior?
Current UI behaviour does not show theme toggle, has rigid dropdown menu

## Screenshots
![Screenshot 2023-10-02 at 10 00 44](https://github.com/codu-code/codu/assets/130994206/ca9ae95e-82d9-4b5b-814f-b8bd156c11d4)
Current Lightmode on Mobile

## Steps to reproduce

To reproduce, toggle light mode on and switch to mobile dev

## Additional info

Refactor so the Navbar folder will contain, Navbar.tsx and Mobile.tsx. 
All functionality will remain the same as before.

Let me know what you think :)

**Comment by NiallJoeMaher** [comment]
Closed with #473
