### ISSUE TITLE
Fix icon color on homepage

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#469]
## Context

The bouncing icon on the homepage should always be white:
<img width="1727" alt="Screenshot 2023-10-02 at 15 33 53" src="https://github.com/codu-code/codu/assets/12615742/04699340-6777-4276-a2bf-d61981489217">

It currently is going dark while in light mode. 

## Expected Behavior

Icon is always white.

**Comment by parinitapatil** [comment]
Could you assign a task to me, please?

**Comment by NiallJoeMaher** [comment]
@parinitapatil 🪄

**Comment by parinitapatil** [comment]
I'm sorry, but I'm having trouble finding code #469. Could you please give me more details or context so I can assist you more effectively?

**Comment by NiallJoeMaher** [comment]
@parinitapatil sure thing: https://github.com/codu-code/codu/blob/7ff8885f644ef13c886e027b91a129e77b832c3d/pages/index.tsx#L188C23-L201C29

The issue is being caused by `stroke="currentColor"`, I think it needs to be updated to `stroke="#ffffff"`

**Comment by parinitapatil** [comment]
I appreciate your kindness, thank you Sir

**Comment by NiallJoeMaher** [comment]
Closed with #472
