### ISSUE TITLE
Notifications page should have light/dark mode

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#470]
## Context

So we can give a better user experience, we are working on a light/dark mode.
Notifications page should have light/dark mode

## Expected Behavior

We use Tailwind, so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

## Current Behavior

By default, we only use a dark theme. 
You can see the editor here: https://www.codu.co/create

## Additional info

The background for light mode should be: `bg-neutral-100`
The text should be: `text-neutral-900`
borders for light mode should be: `neutral-100`

If there is more questions let me know as I'm sure I've missed something! 

Don't forget to test it with and without notifications.

**Comment by AnuMessi10** [comment]
Hi, kindly assign this to me, thanks.

**Comment by AnuMessi10** [comment]
Hey @NiallJoeMaher!

I was wondering if you have/could specify a shade for the placeholder's pulse animation containers in light mode.

Currently it looks something like this as it uses the `neutral-800` for background (set for the dark mode).

![image](https://github.com/codu-code/codu/assets/78202060/fccf41be-46da-43f8-9177-8dd23ae08b90)

Thanks

**Comment by NiallJoeMaher** [comment]
@AnuMessi10 `gray-300` should look good. 🦾 Thanks for asking!

**Comment by AnuMessi10** [comment]
Hi @NiallJoeMaher it's me again, I wanted to inquire if you also felt the need to change these **on hovering** over the "Mark as read" button for a notification:

- color of the check icon/svg
- background color of the "Mark as read" check button, currently set to `bg-slate-700` for the dark mode

I have attached a preview of the same in hovered and normal state

![image](https://github.com/codu-code/codu/assets/78202060/89481552-6900-49c1-a6cf-86fa6d51fe6a)

Let me know your thoughts on them, cheers!

**Comment by AnuMessi10** [comment]
@NiallJoeMaher I have added `gray-300` as the background color on hover for the "Mark as read" button in light mode and created a PR with the same, let me know if any additional changes are needed. 

Thanks

**Comment by NiallJoeMaher** [comment]
closed with #480
