### ISSUE TITLE
Mobile navigation menu/notification icons light mode 

### ISSUE THREAD

**Issue by DarrachBarneveld** [codu-code/codu#475]
## Context

Styling changes for the current mobile navigation icons is needed.

## Expected Behavior

Light mode hover and focus elements should reflect the current theming conventions.

## Current Behavior

Dark mode hover and focus theming is seen when in light mode

## Additional info
Icon colour on focus/hover - text-neutral-300
Icon background on focus/hover - bg-neutral-200
Icon outline on focus/hover -ring-orange-400
Use group tailwind classes to change colours between parent/child div hovers/focus

**Comment by pragyamishra56** [comment]
This is my first open source and I would like to contribute in every way possible. If you can assign this to me

**Comment by NiallJoeMaher** [comment]
@pragyamishra56 sorry this one is closed already!
