### ISSUE TITLE
Add support for Eslint

### ISSUE THREAD

**Issue by pkspyder007** [codu-code/codu#476]
## Context

We are currently working on improving Codu and we want to improve the code quality by incorporating ESLint into our development workflow. ESLint will help us enforce coding standards and catch potential issues in our JavaScript codebase.

## Expected Behavior

1. ESLint should be integrated into our project.
2. We should have a well-defined ESLint configuration that suits our project's requirements.
3. ESLint should be configured to run as part of our build process or during development, depending on our workflow.
4. We should document the ESLint setup and configuration for the team to reference.

## Current Behavior

Currently, our project does not have ESLint configured, and there are no linting rules in place. This means that our codebase may lack consistency, and potential issues might go unnoticed. We want to address this by setting up ESLint and establishing a consistent code quality standard.

**Comment by NiallJoeMaher** [comment]
All done 💚
