### ISSUE TITLE
Add support for Prettier

### ISSUE THREAD

**Issue by pkspyder007** [codu-code/codu#477]
## Context

We want to enhance our code formatting and consistency by integrating Prettier into our development workflow. Prettier will help us automatically format our code according to defined rules and conventions.

## Expected Behavior

1. Prettier should be integrated into our project.
2. We should have a well-defined Prettier configuration that aligns with our project's code style requirements.
3. Prettier should be configured to automatically format code files on save or as part of our build process, depending on our workflow.
4. We should document the Prettier setup and configuration for the team to reference.

## Current Behavior

Currently, our project does not have Prettier configured, and there are no code formatting rules in place. This can lead to inconsistent code styles throughout the codebase. We want to address this by setting up Prettier to ensure consistent and automated code formatting.

**Comment by elqessouartariq** [comment]
can you assign this to me ?

**Comment by NiallJoeMaher** [comment]
@elqessouartariq sure thing! When you run prettier it shouldn't change the current format of much in the app. So pease try keep the formatting the same as the codebase currently has.

**Comment by xiaoniuniu89** [comment]
sorry, i just saw this was assigned to you here. I set up a basic pre commit to run prettier that was just merged in. you can pull from develop and develop it from there if you like

**Comment by NiallJoeMaher** [comment]
Thanks @xiaoniuniu89!
