### ISSUE TITLE
Social Media Icon Change (X)

### ISSUE THREAD

**Issue by amrahs02** [codu-code/codu#479]
## Context
Since Twitter's name is changed to X and its logo is also changed, it should also change on your website

## Expected Behavior

I want to change the logo from Twitter to X

## Current Behavior
![Screenshot from 2023-10-03 23-34-17](https://github.com/codu-code/codu/assets/65103353/2d6f4dce-2474-46d3-b118-d5d8aca1e214)

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Open the Website
2. Scroll Down to the bottom
3. See the social media icons

Please add hacktoberfest label

**Comment by amrahs02** [comment]
Please assign this issue to me.

**Comment by pragyamishra56** [comment]
This is my first open source and I would like to contribute in every way possible. If you can guide and assign this to me

**Comment by amrahs02** [comment]
Hello,
@pragyamishra56 

Thank you for your interest in contributing to this open-source project. Since I created the issue, I would like to take the initial lead on resolving it.

If, for any reason, I find that I'm unable to complete the task or deliver the desired result, I will unassign it. Your willingness to contribute is appreciated, and I may seek your assistance if necessary.

Thank you for understanding.

Best regards,
Sandeep Sharma

**Comment by pragyamishra56** [comment]
@amrahs02  Thank you for the update. I'm here to support and contribute as needed. Your leadership is valued. Looking forward to collaborating.

**Comment by NiallJoeMaher** [comment]
Sorry, I missed this! This issue was open/closed already: https://github.com/codu-code/codu/issues/439

Looking forward to more ideas and contributions. 🦾
