### ISSUE TITLE
Fix animations on icon hover

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#484]
## Context

@DarrachBarneveld correct me if I'm wrong, but I think the original video you showed me had a nice smooth transition? 

The timing and stutter of the hover is jarring at the moment:

https://github.com/codu-code/codu/assets/12615742/6393f80b-01c2-4543-b4af-9dfa11d15d6a

## Expected Behavior

A nice subtle transition into/and out of colors.

**Comment by DarrachBarneveld** [comment]
Ah yes, the duration. Will update now

**Comment by NiallJoeMaher** [comment]
Closed with #490. Thanks @DarrachBarneveld
