### ISSUE TITLE
Change search bar placeholder text

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#486]
## Context

The search bar has a placeholder of "search".
This should be capitalized and become "Search".

![Screenshot of search bar](https://github.com/codu-code/codu/assets/12615742/1046e7ff-6dd1-4b1b-bc06-29392fa5538f)

## Expected Behavior

The placeholder is "Search" instead of "search"

## Steps to reproduce

The search bar can be found on the `/articles` route.

**Comment by Franqsanz** [comment]
Hello @NiallJoeMaher, in which file is it located?

**Comment by alphaprads** [comment]
if you have not assigned this to anybody i would love to work on this?

**Comment by NiallJoeMaher** [comment]
@Franqsanz https://github.com/codu-code/codu/blob/develop/components/ArticleSearch/SearchBar.tsx

**Comment by NiallJoeMaher** [comment]
Let me know if you don't want the issue and I can give it to @alphaprads 🦾

**Comment by NiallJoeMaher** [comment]
Closed by #489, thanks @Franqsanz
