### ISSUE TITLE
Debounce the search bar search

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#487]
## Context

Currently, the `/articles` page has a search bar (in `develop`, not live yet). 
Each keystroke currently starts a search. 
We should debounce the value so that the search only happens after a user stops typing. 

## Expected Behavior

I expect the value to be debounced for 500ms to limit the amount of requests. 

## Current Behavior

A search is requested on every keystroke.

**Comment by s0ham075** [comment]
Hey can I work on this?

**Comment by amrahs02** [comment]
please assign this issue to me

**Comment by NiallJoeMaher** [comment]
Sure thing @s0ham075! 

Hey @amrahs02, hopefully, there is another issue you can help out with. Looking forward to working with you.

**Comment by NiallJoeMaher** [comment]
This one is stale so anyone can take it now. Just leave a comment. 🦾

**Comment by MadhavKrishanGoswami** [comment]
I am working on this
