### ISSUE TITLE
Error after deployment: "Application error: a client-side exception has occurred"

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#491]
## Context

Currently, after deployment, we get an unknown error (I haven't inspected the cause). 
To enable testing of dev features this bug needs to be fixed.

The error says:
"Application error: a client-side exception has occurred (see the browser console for more information)."

But there are also errors in the console. 

## Expected Behavior

No error in the dev environment. 

## Current Behavior

What is the current behavior?

## Steps to reproduce

On Chrome or Safari:
Visit: https://www.dev1.codu.co/

## Additional info

![Screenshot 2023-10-05 at 08 31 55](https://github.com/codu-code/codu/assets/12615742/64860649-20cf-4452-8fda-7aac06be972a)

**Comment by xiaoniuniu89** [comment]
<img width="1027" alt="Screenshot 2023-10-05 at 08 54 51" src="https://github.com/codu-code/codu/assets/84312595/c3b9cc16-260b-40c4-a0b3-3a71938ea241">

allowed domains is incorrect maybe?

**Comment by xiaoniuniu89** [comment]
https://forum.sentry.io/t/event-submission-rejected-with-reason-cors/10389/2

**Comment by NiallJoeMaher** [comment]
Aha, I don't think I've set up the dev Sentry

**Comment by NiallJoeMaher** [comment]
I'll take a look a little later. Thanks @xiaoniuniu89

**Comment by NiallJoeMaher** [comment]
As an update! That fixed one error. But we still have a client error that I can only reproduce in a build:
1. `npm run build`
2. `npm run start`

**Comment by NiallJoeMaher** [comment]
My new assumption is it's from the partial migration to the new `/app` router as it seems builds were fine before #482

**Comment by xiaoniuniu89** [comment]
Import trace for requested module:
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
./node_modules/@aws-sdk/client-ses/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-ses/dist-cjs/SESClient.js
./node_modules/@aws-sdk/client-ses/dist-cjs/index.js
./utils/sendEmail.ts
./app/api/auth/authOptions.ts
./app/api/auth/[...nextauth]/route.ts

maybe rollback last changes ?

**Comment by NiallJoeMaher** [comment]
Fixed by downgrading to Next version to 13.4
