### ISSUE TITLE
my-posts should have light/dark mode

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#493]
## Context

So we can give a better user experience, we are working on a light/dark mode.

## Expected Behavior

We use Tailwind, so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

## Current Behavior

By default, we only use a dark theme. 
You need to be logged in to view this page.

You can see the feed here: https://www.codu.co/my-posts

## Additional info

The background for light mode should be: `bg-neutral-100`
The text should be: `text-neutral-900`
The cards should have a background of: `bg-white`
borders for light mode should be: `neutral-100`
Don't forget to test with no posts, drafts and published states. 

If there are more questions let me know as I'm sure I've missed something!

**Comment by Shritesh99** [comment]
Hi @NiallJoeMaher, Can I work on the issue?

**Comment by NiallJoeMaher** [comment]
Absolutely @Shritesh99
