### ISSUE TITLE
Editor: add support for tables

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#502]
## Context

the editor currently has not been enabled to use tables 

## Expected Behavior

a user should be able to add tables, insert new rows and headers and delete them - pay attention to gap cursor( making sure there is always a newline to escape to)

## Current Behavior

No support for tables

## Steps to reproduce

Please provide detailed steps for reproducing the issue
-

## Additional info

https://tiptap.dev/api/nodes/table

The main issue here will be styling, some tailwind utilities are conflicting with the OOTB styles.

**Comment by NiallJoeMaher** [comment]
I think I will go over some of these features and remove them for the time being or hide them. I want the editor to be as basic as possible until we find use cases it doesn't fit. I know @DarrachBarneveld has a PR open and if it's good we can add it but I just want to make sure we end up with an editor with fewer options 🦾 

One of my core philosophies for products is simplicity above all else.

**Comment by xiaoniuniu89** [comment]
We should think about how we would make tables cross compatible with older markdown posts then. I have it pretty much figured out how to render the markdown posts in the new editor but we would need support for tables (or else a codemod to render them into lists or something) 

We can add support for tables easily enough. That way older posts with table will render correctly. we **could** not give users the ability to add tables with buttons or slash commands or shortcuts etc

**Comment by xiaoniuniu89** [comment]
if you want less options then consider 

text align
tables
making older posts read only/render the old markdown editor
no syntax highlighting for code blocks

we can cut these out, fix the styles then we are pretty much good to go by the weekend!!

**Comment by xiaoniuniu89** [comment]
we can cut these out, fix the styles then we are pretty much good to go

**Comment by NiallJoeMaher** [comment]
Yeah, I think as much features as Medium to be honest for v2 and we can render the old versions the same way as currently until I come up with a magical way of fixing them. 

The syntax highlighting would be nice to have since it's a coding platform but absolutely not necessary to ship it and get feedback at least. It would be nice to get it shipped and have some feedback 🦾

**Comment by xiaoniuniu89** [comment]
sure, We have a small few issues left then in that case. Maybe we can finish it by the weekend. 

Closing this issue
