### ISSUE TITLE
Editor: Bubble menu H1 formatting

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#504]
## Context
sub story of #197 

## Expected Behavior

user should not be able to add any extra H1 tags to their post other than the title

## Current Behavior

the bubble menu still has an H1 formatting option

## Screenshots

<img width="353" alt="Screenshot 2023-10-08 at 21 44 03" src="https://github.com/codu-code/codu/assets/84312595/b94e906c-d4d4-44fd-9b05-18a29770e4c7">

## Steps to reproduce

Please provide detailed steps for reproducing the issue

go to alpha/create/new
write some text 
highlight it and select H1

## Additional info

check out the BubbleMenu.tsx and remove H1 as a formatting option

**Comment by NiallJoeMaher** [comment]
My thoughts on this is to have the h1 become h2 behind the scenes, and so on.

Just as a user experience it might be weird to have the missing h1 when we can just label it h1 and show a h2.

**Comment by xiaoniuniu89** [comment]
replace with A large/small text icon from your original figma. That would be easy fix also

**Comment by xiaoniuniu89** [comment]
think that is the same in medium also

**Comment by xiaoniuniu89** [comment]
changing behaviour of H1 to h2 and h2 to h3 is very easy to do - I leave it to whoever picks this up ;)

**Comment by NiallJoeMaher** [comment]
This was closed recently, we only have level 2/3 options "Heading" and "Subheading".
