### ISSUE TITLE
Editor: slash commands update

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#506]
## Context

story of epic #197 

## Expected Behavior

when the user types / they get a list of formatting features. We have since updated the editor to make use of more nodes such as iframe and pictures and such. Copy what is in the fixed navbar and make sure there is the equivelent in the slash commands

## Current Behavior

/ command menu has a few basic formatting options.

**Comment by John-Paul-Larkin** [comment]
I will take this.

**Comment by John-Paul-Larkin** [comment]
Hi Niu.
Just to be clear. Should I copy everthing from the fixed toolbar to the slash menu? 
The floating toolbar already has a number of text formatting features. The slash menu might be a bit crowded with every feature listed.

![Screenshot 2023-10-11 120722](https://github.com/codu-code/codu/assets/107807466/06ac0ae8-f1f1-497a-8052-d7fb8603015c)

**Comment by xiaoniuniu89** [comment]
@NiallJoeMaher can make a call on this. My opinion is put everything in as results are filtered as you type. 

You can have an overflow scroll on this if you need, I would expect most users to type / followed by what hey are looking for so stuff will filter out. 

Thanks!!!

**Comment by John-Paul-Larkin** [comment]
I will add them all so. Thanks.
