### ISSUE TITLE
Add focus state to theme button

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#516]
## Context

Add focus styles to the the theme button

Add the focus state to the theme icon so that it looks like the notifications icon when focused. It may need some padding too. 
Add screenshots to the PR

## Current Behavior

The default focus state. 

## Screenshots

Focus state should be like this:
<img width="427" alt="Screenshot 2023-10-12 at 21 36 25" src="https://github.com/codu-code/codu/assets/12615742/cfb3052a-dd6a-46a6-a1b3-2c2692f9126f">

Not this:
<img width="421" alt="Screenshot 2023-10-12 at 21 36 35" src="https://github.com/codu-code/codu/assets/12615742/758e65ea-b5df-49e9-9f95-b8320cdd4506">

**Comment by CarolinaCobo** [comment]
I'll take this one if that's okay
