### ISSUE TITLE
Fix theme icon color in light mode

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#517]
## Expected Behavior

The sun icon should have a default color of `neutral-400`.

## Current Behavior

The sun icon is currently black in light mode.

## Additional info

The sun icon should have a default color of `neutral-400`
<img width="418" alt="Screenshot 2023-10-12 at 21 38 29" src="https://github.com/codu-code/codu/assets/12615742/6f5c7b31-12e6-4abd-b151-6b6363e1feca">

**Comment by AnsellMaximilian** [comment]
Hey, @NiallJoeMaher. I'd like to have a take this on if that's okay.

**Comment by Neel-07** [comment]
hello @NiallJoeMaher can this issue be assigned to me.

**Comment by NiallJoeMaher** [comment]
@AnsellMaximilian sure thing!
