### ISSUE TITLE
Remove dark styles from the theme menu

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#518]
## Context

Fix the styles in the theme menu.

## Expected Behavior

On pressdown while in dark mode we have dark styles:
<img width="706" alt="Screenshot 2023-10-12 at 21 34 18" src="https://github.com/codu-code/codu/assets/12615742/b6225e99-449d-4569-9559-f3b3dbf4dcba">
It should be the same styles as the light mode:
<img width="529" alt="Screenshot 2023-10-12 at 22 00 20" src="https://github.com/codu-code/codu/assets/12615742/8f8b5ada-da5f-4293-8355-fd2d505112d8">

**Comment by seog-jun** [comment]
Can I have a try?

**Comment by NiallJoeMaher** [comment]
Join the discord and we will help if you get stuck.

**Comment by Joseph2001-braganza** [comment]
Can I submit a pull Request ?

**Comment by NiallJoeMaher** [comment]
Hi @Joseph2001-braganza, @seog-jun  is working on this I think. They'll let us know if they don't want it anymore. I'll be adding more issues later. 🦾

**Comment by seog-jun** [comment]
I'm working on it..! give me some time..

**Comment by NiallJoeMaher** [comment]
No rush! 🙌

**Comment by NiallJoeMaher** [comment]
Closed with #526

**Comment by Joseph2001-braganza** [comment]
Sure

> Hi @Joseph2001-braganza, @seog-jun is working on this I think. They'll let us know if they don't want it anymore. I'll be adding more issues later. 🦾

Sure
