### ISSUE TITLE
Add white background to topics in light mode

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#527]
On the homepage,

Currently, the topic buttons (on the homepage) inherit the light mode background color. 

They should have a background of white (`bg-white`).
And a grey border (`border border-neutral-300`)

Also add the same styles to the featured card above the topics. 

![Screenshot 2023-10-13 at 20 22 19](https://github.com/codu-code/codu/assets/12615742/98f5c7c8-9709-4fa8-aeab-7c8bbb15826d)

This should be updates to have a white background so they stand out like all the other clickable elements.

**Comment by Anemaygi** [comment]
Hi, can you assign me this task? Thank you!

**Comment by Anemaygi** [comment]
Hi, I've created the PR #533 to fix this issue
