### ISSUE TITLE
Fix the prompt dialog button

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#528]
## Context

We have a component used in to catch unsaved changes on an article so a user doesn't accidentally navigate away. 

It is commented out at the moment because since Next.js version 13 (and the app router) it no longer behaves as expected.

## Expected Behavior

Fix the PromptService component (components/PromptService/PromptService.tsx) so that it works in the new app router.
When it is complete we should be able to add them back into the editor so the user is warned if they are about to navigate away. 

## Current Behavior

It's totally broken. 🙃

**Comment by Joseph2001-braganza** [comment]
I can work on this issue.

**Comment by Joseph2001-braganza** [comment]
I suppose It should throw a prompt message when the user tries to navigate to another link, while writing a post ?

**Comment by NiallJoeMaher** [comment]
Yes it's working on the production site at the moment in case you want to see it.

This is when you are logged in and try to create an article (https://www.codu.co/create)

There is autosave functionality, but if the user is about to navigate away they see the modal in the screenshot. 

![Screenshot 2023-10-14 at 07 33 32](https://github.com/codu-code/codu/assets/12615742/dee180f6-86fc-4f66-80c5-2c3be5e50f5a)

**Comment by Joseph2001-braganza** [comment]
Yes I checked it.It works only once when I try to navigate back.Shouldn't it work every time when some one is navigating to different routes or once should work ? I will try to fix this issue.
In Production there is no theme like dark and light theme.Since in the dev when I try to change the theme to light the text in the post is also black, it camouflages with the  background color. 
<img width="1422" alt="Screenshot 2023-10-14 at 12 13 53 PM" src="https://github.com/codu-code/codu/assets/77545228/99dc5c02-2014-4d39-8174-210b8320df19">

**Comment by NiallJoeMaher** [comment]
Thanks for that! I've been opening issues for fixing this stuff so I'll add it to the pile of issues to pick up.

And since the change to the /app router we now use the next package called "next/navigation" which doesn't have the same hooks as before (and that's what caused it to break).

**Comment by NiallJoeMaher** [comment]
@Joseph2001-braganza let me know if you are tackling this or if I should release it. 🦾 Thanks!

**Comment by Joseph2001-braganza** [comment]
I was looking out for some potential solutions for this but couldn't find one.I guess due to the new version the Next Js team is developing it and still under development as per the github issue thread of Next Js.

**Comment by NiallJoeMaher** [comment]
Dang! This newest version of next has thrown some issues... 😢

**Comment by seog-jun** [comment]
@NiallJoeMaher  Can I have a look? I'm not sure there's a workaround for it

**Comment by NiallJoeMaher** [comment]
All yours @seog-jun! I have no idea yet.

**Comment by seog-jun** [comment]
@NiallJoeMaher  Huh.. there's no simple workaround here.. even version 14 doesn't come with `router.events`

**Comment by xiaoniuniu89** [comment]
we can close this!
