### ISSUE TITLE
Add light mode to topics and featured section (sidebar).

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#529]
## Context

In `/articles`:

Add light mode to topics and featured section (sidebar).

They should have a background of white (`bg-white`).
And a grey border (`border border-neutral-300`).
![Screenshot 2023-10-13 at 20 35 53](https://github.com/codu-code/codu/assets/12615742/bdfe97ee-3a13-4c60-9005-0025827ea423)

This should only be the styles while in light mode.

**Comment by MadhavKrishanGoswami** [comment]
Hello, I think i can work on this. Can this be assigned to me?
