### ISSUE TITLE
Light mode for comments section

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#530]
## Context

Update the comment section in the articles to have a `bg-neutral-300` in light mode and `black` in dark mode. 

![Screenshot 2023-10-13 at 20 42 54](https://github.com/codu-code/codu/assets/12615742/827cca62-13b2-4c64-9f85-756ef38d7faa)

The comments section is found under every article. 
You need to be logged in to see it.

**Comment by Larkuo** [comment]
Hello,
This looks interesting. Can I work on this? Can this be assigned to me?

**Comment by NiallJoeMaher** [comment]
Absolutely! Let me know if you get stuck with anything. 🙌

**Comment by Larkuo** [comment]
Thanks!
