### ISSUE TITLE
Fix title for users bio on articles

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#531]
Fix title for users bio on articles.

It should be `neutral-900` in light mode only (as it looks fine in dark mode). 

![Screenshot 2023-10-13 at 20 49 02](https://github.com/codu-code/codu/assets/12615742/a78a4b47-9f57-45a8-bdc4-a30c5d620f8f)

You'll find the component in: `components/BioBar/BioBar.tsx`

**Comment by Shubhgupta-coder** [comment]
pls assign this issue to  me

**Comment by abhijeetgurle** [comment]
@NiallJoeMaher Can I pick this up?
