### ISSUE TITLE
The downward-pointing button on the homepage has no functionality.

### ISSUE THREAD

**Issue by dev-palwar** [codu-code/codu#541]
## Expected Behavior
It should scroll the page to the next section when clicked 
Please describe the behavior you are expecting

## Current Behavior
Currently, it has no behavior. 

## Screenshots
![Screenshot 2023-10-14 at 14-37-27 Codú - The Web Developer Community](https://github.com/codu-code/codu/assets/102988552/a17105d0-76fe-4592-915a-a37b04958cff)

## Steps to reproduce
Just go to Hompage you'll find it.

**Comment by NiallJoeMaher** [comment]
Hey, I'm checking in our dev environment and it seems to be working? 🤔

https://www.dev1.codu.co/

**Comment by dev-palwar** [comment]
Nope this is not working at all should I share a video?

**Comment by NiallJoeMaher** [comment]
Yes please and whatever browser you're using. Thanks for this! 👏

**Comment by dev-palwar** [comment]
https://github.com/codu-code/codu/assets/102988552/324604a8-f0d8-4dc3-a9db-b3616256b3c2

I am using firefox

**Comment by NiallJoeMaher** [comment]
Aha, it's a browser thing then. I tested on Chrome. 

I have tagged it with Hactoberfest in case anyone wants to try fix it. 🦾

**Comment by abhijeetgurle** [comment]
@NiallJoeMaher @dev-palwar Created a PR for fixing this issue.

**Comment by NiallJoeMaher** [comment]
Perfect, if you don't mind in future leaving a comment on the issue to be assigned first that would be great. 🙌

**Comment by abhijeetgurle** [comment]
Sure, Thanks @NiallJoeMaher
