### ISSUE TITLE
Add a button that scrolls the page back to top

### ISSUE THREAD

**Issue by dev-palwar** [codu-code/codu#542]
## Expected Behavior
The button should have the functionality to smoothly scroll the page back to the top upon being clicked.

## Current Behavior
Right now, we have to manually scroll up the page, which can be a hassle, especially when reading blogs.

**Comment by NiallJoeMaher** [comment]
Any ideas on where something like this should be added or examples of blogs with it?

**Comment by dev-palwar** [comment]
Yeah, something like this
![Screenshot 2023-10-14 at 14-52-22 Create a workflow to display your latest articles on your GitHub profile](https://github.com/codu-code/codu/assets/102988552/3596c259-ad1a-408f-81a8-0f212d7d442b)

A button on the right side of the page similar to the one homepage that when clicked smoothly scrolls the page to the top

**Comment by MadhavKrishanGoswami** [comment]
I think I can work on this, just one thing where would I get the icon from?

**Comment by NiallJoeMaher** [comment]
@MadhavKrishanGoswami I'm trying to mock up something for the mobile design and then you can take it. 🦾

**Comment by akashsiddamshetty** [comment]
@dev-palwar @NiallJoeMaher  check this below screen shot i have created this button to scroll to top smoothly. I want to make pr. can you guys add hacktoberfest labels to this issue #542


<img width="1582" alt="Screenshot 2023-10-18 at 1 59 09 PM" src="https://github.com/codu-code/codu/assets/80561904/02a9bba2-8caf-445f-b5e3-2d5a606ada2a">

<img width="1582" alt="Screenshot 2023-10-18 at 2 07 37 PM" src="https://github.com/codu-code/codu/assets/80561904/3cd7a098-daaa-4081-a20d-affcc0877423">

**Comment by Bitnagar** [comment]
@akashsiddamshetty Great job! The icon looks good. IMO we should not use gray color because it looks dull and not visually appealing. We can try sticking to the design in 2nd screenshot or else we can use gradient color that is in our theme.

**Comment by akashsiddamshetty** [comment]
> @akashsiddamshetty Great job! The icon looks good. IMO we should not use gray color because it looks dull and not visually appealing. We can try sticking to the design in 2nd screenshot or else we can use gradient color that is in our theme.

@Bitnagar @NiallJoeMaher @dev-palwar  check this out. 
<img width="1582" alt="Screenshot 2023-10-18 at 3 51 45 PM" src="https://github.com/codu-code/codu/assets/80561904/db47de9e-6461-4e87-ba5d-f2c148b03c2d">

**Comment by NiallJoeMaher** [comment]
The problem is when we are on mobile. I just haven't seen a pattern on mobile I like. 😅 Any examples of sites doing it well?
