### ISSUE TITLE
Scroll bar on comments

### ISSUE THREAD

**Issue by John-Paul-Larkin** [codu-code/codu#543]
## Context
On chrome there is a scroll bar below every comment on the article page. This does not look good, especially when there are a numerous comments.

## Expected Behavior
Remove/hide scrollbar.

## Screenshots
In this image chrome is on the left, firefox is on the right. I have not tested any other browsers

![Screenshot from 2023-10-14 11-02-03](https://github.com/codu-code/codu/assets/107807466/4c948a88-ad56-439c-be2b-bb5e0aad3476)

**Comment by vrun1208** [comment]
Hi, @Fishamble! Can you provide me the url for the effective page.

**Comment by John-Paul-Larkin** [comment]
Hi Vrun.
If you click on any article, the comments will be at the bottom. Bear in mine that on localhost you will need to post a few comments yourself.
In the code the page is..
app/article/[slug]/page.tsx
and the component is..
components/Comments/CommentsArea.tsx

**Comment by vrun1208** [comment]
okay! i'll look into this

**Comment by NiallJoeMaher** [comment]
@vrun1208 any luck on this one?

**Comment by vrun1208** [comment]
@NiallJoeMaher, I am away right now, I'll try setting it up again and will update you asap

**Comment by vrun1208** [comment]
@NiallJoeMaher, Finished setting up! 🚀
will soon open a PR!!

**Comment by NiallJoeMaher** [comment]
Thanks @vrun1208! No panic, just checking in. 🦾
