### ISSUE TITLE
Change heading options in editor bubble menu

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#549]
## Context

In the bubble menu, we should change the icons to be a large and small headings.

Medium does this inline:

![Screenshot 2023-10-15 at 08 05 10](https://github.com/codu-code/codu/assets/12615742/d5b8dcca-f72e-40e3-91d4-d89fcae547fe)

This can be done using the existing icons that we use with Lucide - https://lucide.dev/icons/heading

## Expected Behavior

The bubble menu should only have **2 heading options**.
1. "Heading" (replace the current "Heading 1" text)
2. "Subheading" (replace the current "Heading 1" text)
3. Remove the "Heading 3" as an option.

Use the https://lucide.dev/icons/heading icon (already installed). 

![Screenshot 2023-10-15 at 08 11 03](https://github.com/codu-code/codu/assets/12615742/e2e8e870-64a5-4fad-a7e5-97339401b9c2)

## Steps to reproduce

For testing, the new editor can be found on `/alpha/new`.

**Comment by RajuGangitla** [comment]
@NiallJoeMaher can u assign this to me

**Comment by NiallJoeMaher** [comment]
Let me know if you need help. 🦾

**Comment by RajuGangitla** [comment]
Ok i will ask u if I need any help

**Comment by NiallJoeMaher** [comment]
Closed with #563
