### ISSUE TITLE
Migrate OG API to app router

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#550]
## Context

We have one last route to migrate to the `/app` router.
It generated the OG images (`pages/api/og/index.tsx`).
We should move this to the `/app` router.

## Expected Behavior

The OG image generation should still work as it does now but be served from an API route in the `/app` router.

## Steps to reproduce

Please provide detailed steps for reproducing the issue:
`GET` request to `http://localhost:3000/api/og?title=Hello%20world!`

**Comment by Bitnagar** [comment]
Hi @NiallJoeMaher . Hope you are doing well.

I have migrated the OG image generation endpoint to `/app/api`. Can i go ahead and send a PR?

**Comment by NiallJoeMaher** [comment]
Heck yes! Thanks 🙏
