### ISSUE TITLE
Light/Dark mode for comments

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#558]
## Context

Add a light/dark mode for comments section. Currently it only works in dark mode.
Here’s what it looks like in light mode:
<img width="888" alt="Screenshot 2023-10-17 at 15 26 24" src="https://github.com/codu-code/codu/assets/12615742/3b2c103f-d6fa-43ab-acd5-ec71c0e30bf2">

## Expected Behavior

We use Tailwind so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

## Current Behavior

By default, we only use a dark theme. 

## Additional info

In light mode:
- The background for light mode should be: `bg-neutral-100`
- The user name or title text should be: `text-neutral-900` 
- The bio text should be: `text-neutral-800`

**Comment by shakthi2003-ice** [comment]
@NiallJoeMaher Can you assign me this issue?

**Comment by shakthi2003-ice** [comment]
@NiallJoeMaher do you want any button to switch from light to dark or vice versa for the whole website or for comments section only? And can you tell me how to produce the issue?

**Comment by NiallJoeMaher** [comment]
We already have one. When you pull the code you'll see it (it's in the nav bar).

**Comment by shakthi2003-ice** [comment]
@NiallJoeMaher how to produce this issue?

**Comment by NiallJoeMaher** [comment]
When you create a comment on a post and toggle the light and dark mode you will see where the problem is. 

Follow the README.md to get setup. 

If you can't let me know and I'll release the issue and try to find some other issues you can jump on. 🦾

**Comment by shakthi2003-ice** [comment]
@NiallJoeMaher 
When I setup the code locally and when I type npc prisms db push I am getting this error

Can't reach database server at `127.0.0.1`:`5432`

Please make sure your database server is running at `127.0.0.1`:`5432`.

**Comment by NiallJoeMaher** [comment]
@shakthi2003-ice do you have docker and the [database running](https://github.com/codu-code/codu#database_url)? 

That usually means something isn't running where it's looking for it. 

https://github.com/codu-code/codu#database_url

**Comment by NiallJoeMaher** [comment]
Closed with #530
