### ISSUE TITLE
Make sure preview and live article formatting looks the same

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#56]
I've noticed that on the preview that bullet points look like they have a much bigger gap in the article preview.

**Comment by NiallJoeMaher** [comment]
Preview version:
![Screenshot 2022-10-07 at 09 06 53](https://user-images.githubusercontent.com/12615742/194504697-f92c04cb-9078-4e5b-b353-5afe31c3ab36.png)

Live article:
![Screenshot 2022-10-07 at 09 07 59](https://user-images.githubusercontent.com/12615742/194504917-78095f2b-96d9-4d04-ae62-648aa7274b8c.png)

**Comment by patrickhladun** [comment]
I can work on this one.

**Comment by NiallJoeMaher** [comment]
Thanks!

**Comment by NiallJoeMaher** [comment]
In production already - closing outdated issue.
