### ISSUE TITLE
On Alpha editor, don't allow bold/italic/strikethrough of headings

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#566]
## Context

To keep a consistent format, users should not be able to bold/italic/strikethrough the titles on pages.
This will help keep a somewhat consistent format.

## Expected Behavior

Disable the ability to add bold to headings. No bold/italic/strikethrough tags should be present in headers. 

## Current Behavior

Currently with keyboard shortcuts and the bubble menu (which can be seen by hovering over text in the body of an article) we can change the style of titles.  

## Screenshots

Drag and drop screenshots here to better describe your issue
![Screenshot 2023-10-20 at 09 33 26](https://github.com/codu-code/codu/assets/12615742/c2e352bb-516b-41ae-a391-de0197cf7c42)

## Steps to reproduce

1. While logged in, go to the new editor route `/alpha/new`.
2. Add some text and titles to the body.
3. Modify the title styles with bold/italic/strikethrough to see what should be removed.

## Additional info

Confirm that it isn't just styles that are showing and that the elements don't get any tags added to the DOM.

**Comment by MadhavKrishanGoswami** [comment]
I think I can do this.

**Comment by MadhavKrishanGoswami** [comment]
tried reproducing the issue, but I can't find the problem. There is no option to edit bold, italic, or strikethrough formatting for the titles on pages.

**Comment by NiallJoeMaher** [comment]
@MadhavKrishanGoswami  are you sure you are in the right editor? 
While logged in, go to the new editor route `/alpha/new`.

Example:

![Screenshot 2023-10-21 at 22 55 03](https://github.com/codu-code/codu/assets/12615742/9cddd739-da58-4401-a672-410cfa274a88)

Or in dev - https://www.dev1.codu.co/alpha/new

Let me know if you need help or want to pass this issue on. 🦾

**Comment by NiallJoeMaher** [comment]
@MadhavKrishanGoswami are you still looking after this one or should I release it? Thanks! 🦾

**Comment by MadhavKrishanGoswami** [comment]
Apologies for the delay, @NiallJoeMaher I am working on it Right now!

**Comment by NiallJoeMaher** [comment]
This is open again if anyone wants to take a look. 👀

**Comment by AnuMessi10** [comment]
@NiallJoeMaher  sure, I can have a look at it. Feel free to assign me this issue. Cheers!

**Comment by seog-jun** [comment]
@NiallJoeMaher Can you assign it to me? I'll have a look thanks.
