### ISSUE TITLE
New editor slash menu -  Fix "Heading" and "Subheading" options

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#567]
## Context

In the slash menu for the new editor we should have "Heading" and "Subheading" options. 

Currently we have "Heading 2" and "Heading 3"

![Screenshot 2023-10-20 at 09 38 33](https://github.com/codu-code/codu/assets/12615742/62993e44-2208-40e3-93e6-41c57e728a51)

The icons should be changed to be - https://lucide.dev/icons/heading which is already installed. 

## Expected Behavior
- In the slash menu we should have "Heading" and "Subheading" options. 
- The icons should have been replaced with - https://lucide.dev/icons/heading which is already installed. 
- The headings should have level 2 for headings (h2) and the text.
- And level 3 (h3) for subheadings.

## Steps to reproduce

For testing, the new editor can be found on `/alpha/new`.

**Comment by RajuGangitla** [comment]
@NiallJoeMaher can I go with this

**Comment by NiallJoeMaher** [comment]
Sure, I was about to make another issue which you could fix too if you don't mind from your last PR?
In the bubble menu: 
- To make sure the "heading" renders a level 2
- And "subheading" renders a level 3 

If you could add this to the PR that would be awesome.

**Comment by RajuGangitla** [comment]
ok
