### ISSUE TITLE
Fix copy to clipboard functionality on articles

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#571]
## Context

During a recent PR the "Copy to clipboard" option was removed accidentally.

**Old:**
![Screenshot 2023-10-21 at 12 17 01](https://github.com/codu-code/codu/assets/12615742/489d23c7-206c-4dc7-87cf-46028f92dfc8)

**New:**
![Screenshot 2023-10-21 at 12 24 03](https://github.com/codu-code/codu/assets/12615742/f229b501-e334-4586-8ac0-7f526108a2a6)

The logic is still here: https://github.com/codu-code/codu/blob/fb5436f9ae272879f0fa98dff46c4f699cc9c73d/components/ArticleMenu/ArticleMenu.tsx#L94C16-L94C16

It just needs to be wired up to an option on the menu. 

## Expected Behavior

- A user can see the "Copy to clipboard" option on the article menu.
- When clicked it should copy the article URL to to user's clipboard.

**Comment by burhanharoon** [comment]
hi @NiallJoeMaher, could you put me in charge of this issue? I'd be excited to work on it! Thanks!

**Comment by NiallJoeMaher** [comment]
Closed with #575
