### ISSUE TITLE
Remove comments in editor

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#572]
## Context

There are comments in the editor (https://github.com/codu-code/codu/blob/develop/app/create/%5B%5B...paramsArr%5D%5D/_client.tsx#L13C1-L13C83)

Remove these comments:
- https://github.com/codu-code/codu/blob/fb5436f9ae272879f0fa98dff46c4f699cc9c73d/app/create/%5B%5B...paramsArr%5D%5D/_client.tsx#L13C1-L13C83
- https://github.com/codu-code/codu/blob/fb5436f9ae272879f0fa98dff46c4f699cc9c73d/app/create/%5B%5B...paramsArr%5D%5D/_client.tsx#L237C1-L255C8
- https://github.com/codu-code/codu/blob/fb5436f9ae272879f0fa98dff46c4f699cc9c73d/app/create/%5B%5B...paramsArr%5D%5D/_client.tsx#L259-L265C15 

## Expected Behavior

No visible changes to the app.

**Comment by IamSudhir-Kumar** [comment]
Hey , @NiallJoeMaher can you assign it to me....
