### ISSUE TITLE
Add link to Code of conduct to footer

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#573]
## Context

Currently we have a code of conduct page that is only found if you know the URL.

Fix this by adding a link to the footer of the page.
As it is relative, the URL should use a `next/link` and link to `/code-of-conduct`.

## Expected Behavior

The footer has a "Code of Conduct" link that works.

![Screenshot 2023-10-21 at 12 47 27](https://github.com/codu-code/codu/assets/12615742/1eb147cc-9695-42df-9c06-592d5b35e3ba)

Test on mobile as we might need to tweak things if this breaks the layout on mobile. If it does, please suggest changes.

**Comment by AryanBakliwal** [comment]
Hi @NiallJoeMaher I would like to work on this one please assign me this.

**Comment by abhijeetgurle** [comment]
Can I take this up @NiallJoeMaher?

**Comment by NiallJoeMaher** [comment]
Hey @abhijeetgurle, I'm letting @AryanBakliwal take a shot at this one. If he releases it I'll give it to you.

**Comment by AryanBakliwal** [comment]
Sorry @NiallJoeMaher, I am having some issues with my local development machine, so I won't be able to complete this. Once again, sorry for the inconvenience

**Comment by abhijeetgurle** [comment]
Ideally, the docs are good enough to setup the local dev env. Let me know if you need any help in this. I can help. @AryanBakliwal

**Comment by NiallJoeMaher** [comment]
Love the support @abhijeetgurle! I can hand this off to you if the setup is too much. Open up an issue if the docs aren't clear. I'm trying to make things as easy as possible.

**Comment by abhijeetgurle** [comment]
Cool, thanks @NiallJoeMaher
