### ISSUE TITLE
Add light/dark mode to report modal

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#593]
## Context

Currently the modal for reporting comments/articles only displays in dark mode:
<img width="1719" alt="Screenshot 2023-10-24 at 11 31 53" src="https://github.com/codu-code/codu/assets/12615742/e99eb1cd-8a84-440e-a748-d1cc71612a21">

This should match the theming of the rest of the site to also support light mode. 

Add light/dark mode to report modal 

## Expected Behavior

We use Tailwind so we should enable this by having a default light mode and dark mode with the `dark:` prefix. 
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

In light mode:
- The background for light mode should be: `bg-neutral-100`
- The user name or title text should be: `text-neutral-900` 
- The bio text should be: `text-neutral-800` 

Don't forget to test in both light/dark modes. 

## Current Behavior

No support for light mode. 

## Steps to reproduce

1. Go to any article
2. Select the menu on the left
3. Select "Report article" to view the modal

**Comment by NiallJoeMaher** [comment]
@Fishamble since this is your baby I can give this issue to you or if you like I can pass it on to someone else. 🦾

**Comment by John-Paul-Larkin** [comment]
I have to look after my baby. 👶🍼  :smile:

**Comment by pateldivyesh1323** [comment]
@NiallJoeMaher If this is not taken, I would like to work on this.

**Comment by NiallJoeMaher** [comment]
It's done already by @Fishamble! Sorry I should have closed it yesterday
