### ISSUE TITLE
Fix always open menu on article sidebar after selection

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#594]
## Context

After selecting a option on the sidebar menu or cllicking away the menu should close.

Here's an example of it staying open when you open the report modal:

<img width="1719" alt="Screenshot 2023-10-24 at 11 31 53" src="https://github.com/codu-code/codu/assets/12615742/e99eb1cd-8a84-440e-a748-d1cc71612a21">

Make sure this behavior is the same on mobile too! 🦾 

## Expected Behavior

The menu should close after you choose and option or click away from the menu. 

## Steps to reproduce

1. Go to any article
2. Select the menu on the left
3. Select "Report article" to view the modal

**Comment by RajuGangitla** [comment]
@NiallJoeMaher can I work on this issue

**Comment by NiallJoeMaher** [comment]
Absolutely @RajuGangitla

**Comment by seog-jun** [comment]
If there's no one working on it, can I have a look?

**Comment by AnuMessi10** [comment]
Hey @NiallJoeMaher it's me again, I have already implemented this functionality for production grade web apps, let me know if you can assign this to me. Cheers! 😄

**Comment by NiallJoeMaher** [comment]
> If there's no one working on it, can I have a look?

It's all yours if you want! Let me know if you don't want it anymore so I can assign to @AnuMessi10

**Comment by seog-jun** [comment]
Then let me give it a shot and if I'm not figuring it out, I'll give it to @AnuMessi10 and you can create PR. Give me some time to do that thanks!

**Comment by seog-jun** [comment]
Status update: there was progress in closing `Popover Panel` when clicking `Report Article` but `Modal` disappears right away as `Popover Panel` is closed. Still figuring out how to close `Popover` only.
