### ISSUE TITLE
When opening report modal the menu shouldn't be above the modal background

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#595]
## Context

When opening the report modal the side menu and options are very visible and should be hidden behind the modal backdrop like the rest of the page,

Here's a screenshot that shows the current behaviour:

<img width="1719" alt="Screenshot 2023-10-24 at 11 31 53" src="https://github.com/codu-code/codu/assets/12615742/e99eb1cd-8a84-440e-a748-d1cc71612a21">

Make sure this behavior is the same on mobile too! 🦾 

## Expected Behavior

The menu should be behind the modal background and not on top like the Modal. 

## Steps to reproduce

1. Go to any article
2. Select the menu on the left
3. Select "Report article" to view the modal

**Comment by LemonDrop847** [comment]
Would like to solve this. Can you assign me?
