### ISSUE TITLE
Sidebar menu in lightmode should have white background

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#597]
**This issue is for first time contributors to Codú!** 

## Context

In light-mode, the menu should be white it is currently off white but all of the highest elements in the page should be white.

<img width="757" alt="Screenshot 2023-10-24 at 12 01 30" src="https://github.com/codu-code/codu/assets/12615742/bd7d1e52-db9a-4976-b473-6c9fa62c3609">

## Expected Behavior

Background of the menu should be `bg-white`.
Make sure dark/light mode still work. 
Test on desktop and mobile

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Go to any article
2. Look at the side menu / or footer menu on mobile.

**Comment by LemonDrop847** [comment]
Hey! Would like to work on this, can I get assigned?

**Comment by NiallJoeMaher** [comment]
Absolutely @LemonDrop847

**Comment by PrathameshSonje** [comment]
Hi! can you assign me this issue?

**Comment by NiallJoeMaher** [comment]
@PrathameshSonje sorry, @LemonDrop847 got dibs on this one for the moment. I'll tag you if they change their mind. 🦾

**Comment by LemonDrop847** [comment]
Added a PR, please review.
