### ISSUE TITLE
Add manifest.ts file 

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#606]
## Context

With Next 13, there is a new way to handle manifest data:
https://nextjs.org/docs/app/api-reference/file-conventions/metadata/manifest

## Expected Behavior

Have a `manifest.ts` file with some good baseline standards.

Here's what you will need:

```
import { MetadataRoute } from 'next'
 
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Codú',
    short_name: 'Codú',
    description: 'A free network and community for web developers. Learn and grow together.',
    start_url: '.',
    display: 'standalone',
    background_color: '#fff',
    theme_color: '#fff',
    icons: [
      {
        src: '/favicon.ico',
        sizes: 'any',
        type: 'image/x-icon',
      },
    ],
  }
}
```

## Current Behavior

This isn't implemented.

**Comment by AnuMessi10** [comment]
Hi @NiallJoeMaher, let me know if you can assign this to me. Cheers!

**Comment by NiallJoeMaher** [comment]
@AnuMessi10 all yours!

**Comment by AnuMessi10** [comment]
@NiallJoeMaher I have made the PR (#607), let me know if any additional changes are required. 😄
