### ISSUE TITLE
Question: What can we do to improve to SEO

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#610]
## Context

What can we do to improve SEO?

The goal is to drive more organic traffic to the Codú site by optimizing the existing site, so I’m open to inputs since I’m not an SEO expert…

**Comment by garyb1** [comment]
Adding this video link from Prismic, the [Technical SEO for Developers | 2023 Checklist ](https://www.youtube.com/watch?v=BkDH55WDiDU&ab_channel=Prismic) recommended by Kevin Powell. Hope this helps!

**Comment by xiaoniuniu89** [comment]
we have some perf issues around the home page image animation, we should make an issue for that . that should help seo a little.

**Comment by NiallJoeMaher** [comment]
@xiaoniuniu89 going through a couple of design ideas at the moment and will hopefully throw it out because it's definitely the heaviest piece of the page.

**Comment by garyb1** [comment]
@NiallJoeMaher  @xiaoniuniu89 Yeah, great idea to look into the home page image 😊

I was thinking about the images used. Harry Roberts (Css Wizardry) uses a [low quality image placeholder technique](https://csswizardry.com/2023/09/the-ultimate-lqip-lcp-technique/) on his website which is really cool. He uses a base64 data:image as the fallback. You can see this on his website with the  --base64 custom property. I'm sure this is possible with [next/image](https://nextjs.org/docs/pages/api-reference/components/image)?

The dark background image initially fetched on codu.co has size w=3840&q=75 which is also very large.
