### ISSUE TITLE
Add passwordless login

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#612]
## Context

- To allow users without a GitHub account to join, we should allow users to sign up with email
- The preferred method would be passwordless

## Expected Behavior

- User can use their email to signup and login. 
- A user that signs up will be required to add some basic data to their account before being able to create posts (the same data we get from GitHub). 

## Current Behavior

We only have GitHub login

**Comment by DarrachBarneveld** [comment]
Id love to try this. Been meaning to use passwordless for a good while now 👍

**Comment by JohnAllenTech** [comment]
What Auth provider should be used? Or will you roll your own basic auth? ( don’t recommend this)

**Comment by JohnAllenTech** [comment]
My recommendation https://supertokens.com

free for <5k MAU

**Comment by sleithdylan** [comment]
@JohnAllenTech Since we are already using Next Auth, I think we should stick with that and then for the email provider to send out the emails we should use something like SendGrid, MailChimp or AWS SES.

**Comment by NiallJoeMaher** [comment]
We have SES already working thankfully! I use it for sending Discord invites and reports.

**Comment by JohnAllenTech** [comment]
Looking into this at the minute. Dont want to ask for it yet until I am confident I have time to deliver. Are we okay with using the SMTP creds from SES? Doesnt seem to be an easy way to use the existing nodemailer transporter 

https://next-auth.js.org/providers/email

**Comment by NiallJoeMaher** [comment]
@JohnAllenTech yes! That's what they are there for. If you can lock it behind the alpha env variable initially, that would be great because @John-Paul-Larkin is working on an onboarding flow, which will mean when we have a new user, they can set up their account, too. 🦾

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher this is going a little too easy... The bones are there. Can you throw my name on this please


https://github.com/codu-code/codu/assets/46611809/fb4a7304-ba12-4db7-a183-b2a311d80431


This is pretty rough and its hardcoded to one email but its working 🚀 

Some guidance needed
- Sign in email. Can we format this like the welcome email?
- Any guidance on how you would like the user to enter their email address to receive the sign in email?

**Comment by NiallJoeMaher** [comment]
Yes on the email! That's something we can clean up too so the simpler the better for the moment anyway. 

For the input on this, we can hide it for now, because we will need the onboarding flow so the user can add their details. 

But something like this if you want to get ahead of it and we can hide it behind a flag it for now:

![Showing an example login flow with an input and button for sign in / sign up](https://github.com/codu-code/codu/assets/12615742/1631167c-5242-4dea-bf84-8cba0165e37b)

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher the user can add their details with the current flow I demo'd? Is there more needed?

Sure the rest makes sense.

**Comment by NiallJoeMaher** [comment]
@JohnAllenTech - Ah yes it does! That's perfect. I just need to make sure the user actually hits "save" then. With GitHub we pull in the data first. I might be missing something here but I think this is good!

**Comment by John-Paul-Larkin** [comment]
We can redirect to the onboarding form instead?
We will need to update this settings page to include the extra fields.

**Comment by NiallJoeMaher** [comment]
The onboarding form isn't finished yet! So the only option is what you currently have

**Comment by JohnAllenTech** [comment]
Any idea what these lines are called? They look like hyphens. I thought they were `<hr>` but dont seem to support the behaviour described

<img width="410" alt="image" src="https://github.com/codu-code/codu/assets/46611809/79d473ca-71df-43f2-a2c9-0eaf1759ddc6">

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher how do you feel about this email template?
<img width="1397" alt="image" src="https://github.com/codu-code/codu/assets/46611809/b5aaed6c-52b8-4070-adde-9747f4c377be">

and heres where I have gotten to with login page
<img width="1724" alt="image" src="https://github.com/codu-code/codu/assets/46611809/f4ade143-94fa-42bb-8b46-d4a43bd9c184">

Still confused about the ---- ----- on either side of 'or continue with'

**Comment by JohnAllenTech** [comment]
This was completed in #785
