### ISSUE TITLE
Improving Automated Accessibility Checks

### ISSUE THREAD

**Issue by garyb1** [codu-code/codu#644]
I think we could do a number of things to improve a11y in the codu codebase. 
Some suggestions are:

1. Adding automated checks to Github actions. See how [canaxess implemented automating accessibility testing](https://www.canaxess.com.au/articles/gotta-catch-em-all/).
2. Add [Eslint jsx a11y](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) to our eslint plugins
3. Add [jest-axe](https://maxrozen.com/automatic-a11y-testing-with-jest-axe) to any unit tests being carried out. This also uses axe-core behind the scenes.
4. Ensure all PR's have meaningful alt text with the [Github alt text bot](https://github.com/github/accessibility-alt-text-bot).

**Comment by NiallJoeMaher** [comment]
This was a fantastic addition! Thanks @garyb1

**Comment by garyb1** [comment]
@NiallJoeMaher no problem! 🙂 I didn't get to do step 1 but can always create another issue for that

**Comment by NiallJoeMaher** [comment]
My bad! Lets keep it open until then in case someone wants to pick it up.
