### ISSUE TITLE
bug: Toploader loads endlessly on CMD + click

### ISSUE THREAD

**Issue by tomcru** [codu-code/codu#672]
## Context

on Mac

## Expected Behavior

Toploader should not trigger on CMD + click or when clicking on external links. 

## Current Behavior

Toploader triggers on external link clicks & loads endlessly on CMD + click

## Screenshots

<img width="1056" alt="Screenshot 2023-12-12 at 16 37 22" src="https://github.com/codu-code/codu/assets/35841182/0051eb2b-14c8-42a3-a942-8a9aa489e1e4" alt="a Screenshot of the Top loading bar being stuck on codu.co">

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Go to https://www.codu.co
2. CMD + click on any item in the nav bar (or any link)
3. Visit the original page

## Additional info

I can PR this issue, I would replace the current package with a drop-in replacement & a much more up-to-date library: [Holy Loader](https://github.com/tomcru/holy-loader) (this is my library) - keeping the original look 1:1, but removing the bugs.

**Comment by NiallJoeMaher** [comment]
And it looks like you found a bug with my github-action bot too 😂 What an interesting bug on the loader! Great find. And sure thing, I'd be happy to accept the PR.
