### ISSUE TITLE
Scroll bug after a draft save is triggered on new post

### ISSUE THREAD

**Issue by gdomaradzki** [codu-code/codu#68]
https://www.loom.com/share/2aab0262c3f2400b80281f0b2bcbe892

**Comment by jh3y** [comment]
Could you confirm which browser this is in? Thanks for the video 🙏 Makes reproducing way easier when you can see exactly how things are caused.

**Comment by gdomaradzki** [comment]
This happened in Chrome Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by NiallJoeMaher** [comment]
I haven't been able to reproduce this. 🤔

**Comment by NiallJoeMaher** [comment]
Closing because I haven't be able to reproduce this. Feel free to reopen if you can reproduce.
