### ISSUE TITLE
Unable to view published articles on a mobile device

### ISSUE THREAD

**Issue by CallumDennisIE** [codu-code/codu#681]
## Context

Desktop - Windows laptop with Chrome browser
Mobile - Chrome DevTools &IPhone 11 Pro Max with Safari

## Expected Behavior

When on a mobile device, selecting published articles should show the articles the logged in user has published.

## Current Behavior

When on a mobile device, selecting published articles will still continue to show draft articles and not completed ones

## Screenshots
![codu-bug-mobile-draft](https://github.com/codu-code/codu/assets/110825112/e1943668-4f32-48bc-a5c8-78a0053cbb25)
![codu-bug-mobile-published](https://github.com/codu-code/codu/assets/110825112/5a976913-77ef-490c-87e7-439d423613bc)

![codu-bug-desktop-draft](https://github.com/codu-code/codu/assets/110825112/cee29482-11a2-4537-9e2d-1c406ff71030)
![codu-bug-desktop-published](https://github.com/codu-code/codu/assets/110825112/9a1a221a-c2f8-480f-842b-2d942cfec96c)

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Log In to an account that has previously published articles on a mobile device
2. Create a test draft article
3. Navigate to 'My Posts' via the burger menu
4. Click on the 'Drafts' dropdown and select 'Published'
5. See if the published articles appear

**Comment by NiallJoeMaher** [comment]
Sorry I missed this! Great find. Thanks for spotting this!
