### ISSUE TITLE
[Bug] Canonical URL is set to undefined when republishing post

### ISSUE THREAD

**Issue by sleithdylan** [codu-code/codu#686]
## Context

I noticed whenever I make changes in my posts and republish them I have to keep putting in my Canonical URL again, would it not be better to check if the canonicalUrl is not null and then pull it into the input so that it auto-populates for you and then you don't have to keep putting it in?

## Expected Behavior

After I make changes to an existing post, I expected the input of the **Canonical URL** to be auto-populated with the **canonicalUrl** that was saved in the database so that I do not need to keep re-entering it.

## Current Behavior

When I first create a post, I add in my **Excerpt**, **Topics** and then I usually click into **Advanced Settings** and add in my **Canonical URL** also but what if I make an error in my post and I needed to edit it?  Well I would go ahead and edit it and then I would republish it, if I didn't change any of the settings previously and just clicked **Save Changes** It would save but without my **Canonical URL** that I previously used since it is undefined at this point.

## Screenshots

When I first added my **Canonical URL**, this is the form data that is sent to the database

![chrome_7vK703hVrs](https://github.com/codu-code/codu/assets/30472715/d5ff780a-980f-4aab-b26e-03e19c1dae5d)

After I edit a post and just click **Save Changes**,  this is the form data that is sent to the database

![chrome_apPaXET2IH](https://github.com/codu-code/codu/assets/30472715/b4e0cbd6-075e-4466-86ea-1b7c9003affb)

## Additional Information

After spending time writing this I did notice that in the database, if the input is empty it does not make the canonicalUrl null again and it will update if you do put in another URL however you can argue this could be a bad UX issue since the user just like me thought that I was updating the **Canonical URL** to be empty.

Please close if this was the intended way of doing it, I just thought I would bring it up :)

**Comment by NiallJoeMaher** [comment]
This is a great find! Definitely needs to be fixed. 🦾
