### ISSUE TITLE
Validate username

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#719]
## Context

Usernames for user accounts on Codú should only contain alphanumeric characters and dashes (-).
A user was spotted using their email as their username which we obviously don't want. We need to validate and clean invalid usernames too!

## Expected Behavior

Usernames for user accounts on Codú should only contain alphanumeric characters and dashes (-).

## Current Behavior

Validation isn't stopping special characters. 

Provide any additional information here

**Comment by Maczi01** [comment]
Please assign this to me.
