### ISSUE TITLE
Dynamically create preview images for blog articles

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#72]
## Context

Based on something I see Medium and other good blogging platforms it would be cool to dynamically generate a OG image like seen here on [jhey.dev](https://jhey.dev/writing/how-to-make-a-pure-css-3d-package-toggle/):
![Screenshot 2022-10-23 at 14 38 39](https://user-images.githubusercontent.com/12615742/197395518-bd34e47b-868d-4578-b4fc-93fdda7d7769.png)

I expect it to look something like this: 
![image](https://user-images.githubusercontent.com/12615742/197395719-1109ac3a-1f91-4c0a-9f12-b198f5ffecb0.png)

## Expected Behavior

Each article has its own OG preview showing the title of the article and the branding of Codú. 

## Current Behavior

Currently we don't have OG images.

**Comment by jh3y** [comment]
I'd like to play! 🪙 🕹️ 😅
