### ISSUE TITLE
Add dynamic meta data for SEO

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#74]
Currently, we get no SEO or OG previews based on the data provided in the blog posts. 

We should leverage the data of the post to create a social preview similar to what I have done on my own blog here:
[https://github.com/NiallJoeMaher/website/blob/main/pages/blog/%5Bslug%5D.js](https://github.com/NiallJoeMaher/website/blob/main/pages/blog/%5Bslug%5D.js)

This will help with SEO and just generally better findability of content. 

We have a default OG image, and I have created issue #72 to work on a nice OG preview image that is unique for each post.

**Comment by NiallJoeMaher** [comment]
As my SEO skills are rusty, I will take any pointers on things we are missing here too! ❤️

**Comment by CarolinaCobo** [comment]
I'll take this one!
