### ISSUE TITLE
For SEO - What are the must have meta tags for optimal performance? 

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#76]
Question for any SEO gurus - What are the must have meta tags for optimal performance of our blog posts?

**Comment by NiallJoeMaher** [comment]
Also might be worth noting what we should have for non-blog post pages, too (if there are any differences).

**Comment by jucasoliveira** [comment]
Customized Metatag Image.
For that , Vercel OG Image package is the best 
https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images

**Comment by NiallJoeMaher** [comment]
Oooh dang! 

> Customized Metatag Image. For that , Vercel OG Image package is the best https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images

Oh dang! I think this is what @jh3y was telling me about. I was just talking about the text or tags, but this looks rad! 🔥

**Comment by jh3y** [comment]
Yep! I'll be integrating this tonight hopefully 🤞
