### ISSUE TITLE
Appending callback to url when hitting Sign in button on Nav

### ISSUE THREAD

**Issue by JohnAllenTech** [codu-code/codu#777]
## Context

If you spam click the sign in button it keeps appending 'www.codu.co%2Fget-started%3FcallbackUrl%3Dhttps%253A%252F%252Fwww.codu.co%252F' to the url.
<img width="1203" alt="image" src="https://github.com/codu-code/codu/assets/46611809/ab33fbd3-40ee-4906-aa61-3c7b7be3c83d">

## Expected Behavior

The url would update on first click and would not update on subsequent clciks

What is the current behavior?

The url is appended with 'www.codu.co%2Fget-started%3FcallbackUrl%3Dhttps%253A%252F%252Fwww.codu.co%252F' each time.

## Steps to reproduce

1. Navigate to https://www.codu.co/
2. Click Sign in button in Nav
3. Click Sign in button in Nav again
4. Look at the url

## Additional info

No loss in functionality as far as I can tell so maybe not a big deal

**Comment by JohnAllenTech** [comment]
@the-Tiege this might be a nice one to pick up

**Comment by JohnAllenTech** [comment]
Looked at this one last night. Its a bit of a mind melt. Seems to be an issue with next-auth but I cant surface the logs. Log surfacing seems to be a known issue with next-auth.

**Comment by IdrisGit** [comment]
Hi, I have looked into the code, and the issue seems to be that on the "Sign in" button click event, the' signin ()` method from NextAuth is being called without any arguments. This is causing the current page URL to be appended to the callback URL.

You can assign it to me, I can look into this issue.

**Comment by IdrisGit** [comment]
I have opened up a PR for the fix, let me know if you need any details or have suggestions.
