### ISSUE TITLE
Display message when there's no published articles on profile page

### ISSUE THREAD

**Issue by CarolinaCobo** [codu-code/codu#78]
As a user, I think there should be a message displaying when you have no articles published in case people mistake this for data not loaded.

Screenshot of current empty state:
<img width="663" alt="Screenshot 2022-10-24 at 19 38 37" src="https://user-images.githubusercontent.com/58437550/197600783-e0702ba2-4f9e-4a3c-bff4-e9442a2d9c06.png">

**Comment by CarolinaCobo** [comment]
I'll take it, thanks!

**Comment by NiallJoeMaher** [comment]
Great idea! I've assigned this to you now.
