### ISSUE TITLE
Error 404 if the username has an accent on any letter

### ISSUE THREAD

**Issue by AdrianBailador** [codu-code/codu#789]
## Context

If a username has an accent, in this case it is on the letter "á" this should not be accepted as it will cause a 404 error in the account.

## Expected behaviour

It is expected that you will be able to load the profile in a completely normal way, whether or not you have accents in the user profile.

## Current behaviour

If the username has an accent your profile link will return a 404.

## Steps to reproduce

https://www.codu.co/adrián-bailador-panero-3he

I have solved the problem by changing my user name without an accent

https://www.codu.co/adrian-bailador-3he

**Comment by John-Paul-Larkin** [comment]
Hey @AdrianBailador 
If I remember correctly you did a PR to fix this?
