### ISSUE TITLE
Typing a tag that already exists causes strange behaviour

### ISSUE THREAD

**Issue by JohnAllenTech** [codu-code/codu#821]
## Context

Easier to show in video

## Expected Behavior

The tag would not be removed and maybe a alert is show saying 'topic already added'

## Current Behavior

What is the current behavior?

https://github.com/codu-code/codu/assets/46611809/42f09a98-ab38-41cf-9d73-0dce001fe071

## Screenshots

- None

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Add a tag
2. Try to add a tag with the same name

## Additional info

- none

**Comment by Maczi01** [comment]
Assign me pls
