### ISSUE TITLE
Migrate tRPC endpoints to Drizzle

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#827]
## Expected Behavior

We are trying to move from Prisma to Drizzle and have started to migrate.
There are a tonne of endpoints that need to be migrated to Drizzle. 

If you want to take an endpoint, just let me know which one is below, and you can take it. 

One PR per endpoint, **please**, since it'll make it easy to test. 🧪

**Comment by JohnAllenTech** [comment]
I looked into some of these previously. Drizzle and Prismas query API dont overlap completely unfortunately. Are you happy with the querys being recreated in standard SQL?

**Comment by JohnAllenTech** [comment]
Prisma VS Drizzle docs https://www.prisma.io/docs/orm/more/comparisons/prisma-and-drizzle#:~:text=Drizzle%20exposes%20the%20underlying%20filter,by%20looking%20at%20string%20filters.

Its from Prisma so I assume theres pros aswell
