### ISSUE TITLE
Replace react-markdown with Markdoc

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#83]
Currently we are using `react-markdown` and hitting some limitations that could be fixed if we used [Markdoc](https://markdoc.dev/) instead.

**Comment by NiallJoeMaher** [comment]
The reasoning is we want to have custom nodes to allow us to achieve #30 and #31 so if anyone has better suggestions I would love to hear them. 🦾

**Comment by pkspyder007** [comment]
Working on a list of changes we need to make in application code to accomplish this.
will share the update in the issue thread soon.
