### ISSUE TITLE
Groups not switching to light mode 

### ISSUE THREAD

**Issue by JohnAllenTech** [codu-code/codu#830]
## Context

Components dont seem to have a light mode version

## Expected Behavior

Should change when in light mode

## Current Behavior
Doesnt change when in light mode

## Screenshots

https://github.com/codu-code/codu/assets/46611809/8f599b29-87ca-4566-9734-b0ff9c1e609c

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Go to http://localhost:3000/hub?tab=groups
2. Switch between light mode and dark mode

**Comment by realshaunoneill** [comment]
This can prob be closed now I think since the above was merged @NiallJoeMaher 
Looks like GH didn't auto close it 😭

**Comment by NiallJoeMaher** [comment]
Thanks @realshaunoneill
