### ISSUE TITLE
Misaligned like count on sideBarData 

### ISSUE THREAD

**Issue by JohnAllenTech** [codu-code/codu#875]
## Context

This is on Production codu and dev

## Expected Behavior

Number is centered

## Current Behavior

Number is not centered

## Screenshots

<img width="96" alt="image" src="https://github.com/codu-code/codu/assets/46611809/c2015cc8-ef31-4e72-88bb-532a31c7ff3b">

## Steps to reproduce

Go here https://www.codu.co/articles/join-our-6-week-writing-challenge-quohtgqb

## Additional info
- None

**Comment by Maczi01** [comment]
PR here:

https://github.com/codu-code/codu/pull/883
