### ISSUE TITLE
Bookmarked posts not appearing as bookmarked on frontpage

### ISSUE THREAD

**Issue by JohnAllenTech** [codu-code/codu#895]
## Context

Bookmarked posts arent appearing as bookmarked on the front page

## Expected Behavior

They should show as bookmarked

## Current Behavior

They arent showing as bookmarked

## Screenshots

<img width="1244" alt="image" src="https://github.com/codu-code/codu/assets/46611809/fa8dbb74-deb8-4c4d-bb46-94cc18e0d3ed">
## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Bookmark a post that appears in the trending posts
2. Navigate to front page and refresh until you see post
3. its not shown as bookmarked

## Additional info

Giraffes are 30 times more likely to get hit by lightning than people.

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher can close this. solved in #894. Confirmed it in dev

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher still seeing this issue? I noticed you added the hacktoberfest label

**Comment by John-Paul-Larkin** [comment]
@JohnAllenTech  
I think NIall just added tag to all open issues. I will close this 👍
