### ISSUE TITLE
Comment Controls are missing after authentication

### ISSUE THREAD

**Issue by Shane-Donlon** [codu-code/codu#919]
## Context

Please provide any relevant information about your setup

## Expected Behavior
I want to be able to delete and edit my comments

## Current Behavior
After I log in I can no longer delete or edit my comments.

**Comment by Aditya-PS-05** [comment]
Hey @NiallJoeMaher ,
I am interested in solving the issue. Please assign it to me.

**Comment by Aditya-PS-05** [comment]
@Shane-Donlon , 
Hey can you ive me more context into this, as far as I am trying, I am able to edit and delete the comments even after many login or logouts.

**Comment by Shane-Donlon** [comment]
Hey - this was resolve(by someone else) but never closed off, I'll close it off now.
