### ISSUE TITLE
.gifs don't work on image upload once processed

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#998]
## Context

The initial preview of a gif shows as expected but after it is processed by the lambda it loses the motion. 

This is because during the resize the gif is losing its format. 

## Expected Behavior

gifs can be resized but should still work. 

Code can be found in `/cdk/lambdas/uploadResize`

**Comment by JohnAllenTech** [comment]
Oh wow.... my gif people need me!

Can you document the flow of how an image gets resized @NiallJoeMaher  or @John-Paul-Larkin ?

Is it

1. User adds image to an article
2. Image gets sent to lambda to be resized ?
3. If image is a gif its now broken?

**Comment by NiallJoeMaher** [comment]
Yes, you'll see it in the CDK lambdas folder. From memory it's just because we convert those gifs to a static image
